### ISSUE TITLE
Exception message "java.lang.IllegalStateException: couldn't determine local port. Please set spring.boot.admin.client.instance.service-base-url." is thrown when startup with amqp service

### ISSUE THREAD

**Issue by liyj144** [codecentric/spring-boot-admin#1009]
Include dependency in pom.
```
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-starter-client</artifactId>
    <version>2.0.4</version>
</dependency>
```

Include hystrix stream or amqp in pom to use rabbitMQ stream.
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-amqp</artifactId>
</dependency>
```

Start up spring boot application, in start up trace we can see below message, but the application can be success register to spring boot admin. I just want to know how to solve this error trace.

```
2018-11-17 19:58:53.461 ERROR [fmc-order-service-web,,,] 79298 --- [gistrationTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.IllegalStateException: couldn't determine local port. Please set spring.boot.admin.client.instance.service-base-url.
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceBaseUrl(DefaultApplicationFactory.java:98)
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getServiceUrl(ServletApplicationFactory.java:58)
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementBaseUrl(ServletApplicationFactory.java:73)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:150)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:71)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:154)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:71)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2018-11-17 19:58:53.568  INFO [fmc-order-service-web,,,] 79298 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [127.0.0.1:5672]
2018-11-17 19:58:53.630  INFO [fmc-order-service-web,,,] 79298 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rabbitConnectionFactory#63d75087:0/SimpleConnection@328c6f65 [delegate=amqp://fmc@127.0.0.1:5672//dev_fmc, localPort= 53489]
2018-11-17 19:58:53.696  INFO [fmc-order-service-web,,,] 79298 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'fmc-order-service-web-1.springCloudBusOutput' has 1 subscriber(s).
2018-11-17 19:58:53.699  INFO [fmc-order-service-web,,,] 79298 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
```

**Comment by joshiste** [comment]
Are you deploying a .war-file to a servlet container?
Please provide a complete project to reproduce the issue.

**Comment by liyj144** [comment]
Sorry for this bug report. This exception is shown when i use eureka and SBA at the same time. When i remove SBA from project, it works fine. Just close it.  #1010
