### ISSUE TITLE
Problem with HTTPS-only configuration with HTTP2 enabled

### ISSUE THREAD

**Issue by masbaehr** [codecentric/spring-boot-admin#1016]
Hi, i'm trying to use spring boot admin with a HTTPS-only application. (http2 enabled!)
The exact configuration works fine when i change to a http connection

versions:
compile group: 'org.springframework.boot', name: 'spring-boot', version: '2.1.0.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-autoconfigure', version: '2.1.0.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.1.0.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version: '2.1.0.RELEASE'
	compile group: 'org.springframework.security', name: 'spring-security-core', version: '5.1.1.RELEASE'
	compile group: 'de.codecentric', name: 'spring-boot-admin-starter-client', version: '2.1.1'

the error when client is trying to register with admin: 
```java
java.lang.IllegalStateException: Calling [asyncError()] is not valid for a request with Async state [MUST_DISPATCH]
	at org.apache.coyote.AsyncStateMachine.asyncError(AsyncStateMachine.java:440) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:494) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.Request.action(Request.java:430) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:382) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:239) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:72) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

**Comment by joshiste** [comment]
please provide a comlete project to reproduce the error

**Comment by masbaehr** [comment]
Unfortunately it's too hard to provide a complete project, as it would require correctly signed certificates to work in the first place, else you would see SSL exceptions all over the place. 

May i ask what the recommended configuration for the admin is? Should i rather go with webflux instead of tomcat/web.

To exclude things i have now configured the admin to HTTP (while maintaining the clients HTTPs only) and the same arror arises. Note: The /actuator and /actuator/health endpoinds are accessible perfectly via a browser

```gradle
plugins {
  id 'org.springframework.boot' version '2.1.0.RELEASE'
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}

repositories {
    jcenter()
}

archivesBaseName = 'spring-boot-admin'
ext['tomcat.version'] = '9.0.12'

dependencies {
	 
	compile group: 'de.codecentric', name: 'spring-boot-admin-starter-server', version: '2.1.1'
	compile group: 'org.springframework.cloud', name: 'spring-cloud-starter', version: '2.0.2.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.1.0.RELEASE'
	compile group: 'javax.servlet', name: 'javax.servlet-api', version: '4.0.1'
	 
}

```

I will try to setup a demo client URL with signed certificate can be publicly accessed though, just give me some time :)

**Comment by joshiste** [comment]
please provide a attached zip-file or a github repo.

**Comment by masbaehr** [comment]
I found out the reason.. There were 2 problems
1st: I had to import the Let's encrypt X3 DER certificate to the java keystore. 

Then however the next problem seems to be related with HTTP2. If i turn on HTTP2 support it will still fail. With HTTP1.1 "server.http2.enabled=false"  on the CLIENT application. It will run.

Probaly this can be improved by using a different way to communicate. I've tested this in a plain java app and it works fine


```java

	HttpClient client = HttpClient.newHttpClient();
    	HttpRequest request = HttpRequest.newBuilder()
    	      .uri(URI.create("https://serverwithhttp2enabled:9480/actuator"))
    	      .build();
    	client.sendAsync(request, BodyHandlers.ofString())
    	      .thenApply(HttpResponse::body)
    	      .thenAccept(System.out::println)
    	      .join();
```

**Comment by masbaehr** [comment]
I'm closing this since the error is probably not caused by spring-boot-admin, but it seems to be an incompatibility while connecting with netty to tomcat9+h2 as protocol.

Now i've switched client and server to Undertow and it is working fine even with http2
