### ISSUE TITLE
Require minimum number of instances

### ISSUE THREAD

**Issue by Nalha** [codecentric/spring-boot-admin#1033]
I want the ability to require a minimum number of instances of a service. 

Currently it can see if a service is up and running or not but fails to see a problem if someone would turn scale down to 0 or delete the entire kubernetes workload, it would simply disappear from the Application list and Wallboard with no error.

I could turn off auto-deregistration but that would require manual purging of services after every image version update since k8s simply redeloys and deletes the services with new names and everything.

If there is a way to do this currently I've failed to find it and I'm sorry in advance.

**Comment by NicoBijl** [comment]
Anyone working on this? I am trying to setup Spring Boot Admin for our k8s cluster, but right now if we do a redeploy , the old services remain visible as offline. This should not happen in my opinion (or be configurable)

**Comment by joshiste** [comment]
@NicoBijl 
If you are using spring-cloud.kubernetes:
Stopped applications should disappear. Be aware that you need to add a `@EnableScheduling` to the SBA server so that the discovery client starts a watcher that keeps the services in sync (see https://github.com/spring-cloud/spring-cloud-kubernetes/issues/385)

If you are using spring-boot-admin-client: There is an option that the services derigister on shutdown...

**Comment by poludov** [comment]
Anyone working on this? 

I think this is a really useful feature. 
Today out team have more than 20 microservice in production and we use SBA and we liked it! 

But now there is one case then SBA does not show the real picture. If microservice is currently not working, then it is not displayed on the panel. However, one idle microservice can be a serious problem for the entire system. I would like to see this problem on the SBA-wallboard.

**Comment by phil-schneider** [comment]
@poludov this is actually an open source project. So get the code, try to understand and try to solve/implement the feature.
The main maintainer is just doing this is his spare time. If He does not need the feature or does not find it this usefull He will not implement it. 
You want or need it try to implement it. I ☺️😁

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.

**Comment by thanks-git** [comment]
Hi Have you encountered this problem again ？ @andreashouben  
 java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
 Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET health [DefaultWebClient]
 Stack trace:
                at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
                at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:279)
                at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:418)
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
                at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:270)
                at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:285)
                at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
                at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
