### ISSUE TITLE
reactor.retry.RetryExhaustedException: de.codecentric.boot.admin.server.eventstore.OptimisticLockingException: Verison 1 was overtaken by 1 for

### ISSUE THREAD

**Issue by matzegebbe** [codecentric/spring-boot-admin#1059]
Hi!

Versions:
spring-boot-admin-server: ***2.0.4***
spring boot version: ***2.0.7.RELEASE***
spring cloud version: ***Finchley.SR2***

we are using spring boot admin with eureka service discovery.

Since last week I got the following error in one of our environments also after many restarts and waiting over 24h (spring boot admin is not working)

The spring boot admin application is still running and always throws that error. The local connection is also not working

**de.codecentric.boot.admin.server.eventstore.OptimisticLockingException: Verison 1 was overtaken by 1 for 2097190b8467**

On another environment the same spring boot admin image runs in exactly the same version. Any ideas whats the root cause for that? I also restarted our eureka peers

```
2019-01-08 10:21:51.126 ERROR [appcon,,,] 1 --- [or-http-epoll-4] d.c.b.a.s.services.StatusUpdateTrigger   : Resubscribing after uncaught error

reactor.retry.RetryExhaustedException: de.codecentric.boot.admin.server.eventstore.OptimisticLockingException: Verison 1 was overtaken by 1 for 2097190b8467
	at reactor.retry.DefaultRetry.retry(DefaultRetry.java:130)
	at reactor.retry.DefaultRetry.lambda$apply$1(DefaultRetry.java:115)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:357)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:241)
	at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:735)
	at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:894)
	at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:297)
	at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:106)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:157)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:163)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:198)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:130)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:773)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:543)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:523)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:409)
	at reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:131)
	at reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186)
	at reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onComplete(FluxMapSignal.java:213)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:130)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:245)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:130)
	at reactor.ipc.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:380)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)
	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:345)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:338)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:404)
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:631)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:138)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: de.codecentric.boot.admin.server.eventstore.OptimisticLockingException: Verison 1 was overtaken by 1 for 2097190b8467
	at de.codecentric.boot.admin.server.eventstore.ConcurrentMapEventStore.createOptimisticLockException(ConcurrentMapEventStore.java:123)
	at de.codecentric.boot.admin.server.eventstore.ConcurrentMapEventStore.doAppend(ConcurrentMapEventStore.java:93)
	at de.codecentric.boot.admin.server.eventstore.ConcurrentMapEventStore.lambda$append$2(ConcurrentMapEventStore.java:71)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:67)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:30)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:160)
	... 58 common frames omitted

**Comment by joshiste** [comment]
> Any ideas whats the root cause for that?

Currently not. Are you using hazelcast? Are there maybe two instances registered to eureka having the same health-url?

**Comment by matzegebbe** [comment]
We are not using hazelcast.

I double checked the different health urls in the eureka and they all have different names and health urls like http://9acd85a7de8c:6565/manage/info (6565 management port, 9ac = docker hostname)

![image](https://user-images.githubusercontent.com/3482021/50910742-ba68eb00-142e-11e9-8eb0-f86d1e61c3d2.png)

``` 
reactor.retry.RetryExhaustedException: de.codecentric.boot.admin.server.eventstore.OptimisticLockingException: Verison 0 was overtaken by 0 for 04bf78cad707
```

Shouldn't the exception care if the version is the same? lastVersion >= events.get(0).getVersion() in my case 0 and 0

```
        long lastVersion = getLastVersion(oldEvents);
        if (lastVersion >= events.get(0).getVersion()) {
            throw createOptimisticLockException(events.get(0), lastVersion);
        }
```

https://github.com/codecentric/spring-boot-admin/blob/070eec3a665daab05a5bf5ff9d26fc8dc56f8ad5/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/eventstore/ConcurrentMapEventStore.java#L91

**Comment by joshiste** [comment]
> Should the exception happen when the version is the same? lastVersion >= events.get(0).getVersion() in my case 0 and 0

No since then there would be two events with the version 0.

**Comment by matzegebbe** [comment]
I updated to

```
<java.version>1.10</java.version>
<spring-boot-admin.version>2.1.1</spring-boot-admin.version>
<spring-cloud.version>Greenwich.RC2</spring-cloud.version>
<spring.boot.version>2.1.2.RELEASE</spring.boot.version>
```

I still get these errors but only on startup for a few seconds. After that the application is quiet and working fine!

```
2019-01-18 13:11:53.882  WARN 1 --- [or-http-epoll-2] d.c.b.a.s.s.EndpointDetectionTrigger     : Unexpected error while handling PooledSlicedByteBuf(ridx: 0, widx: 120, cap: 120/120, unwrapped: PooledUnsafeDirectByteBuf(ridx: 282, widx: 282, cap: 1024))
```
and 
```
reactor.retry.RetryExhaustedException: de.codecentric.boot.admin.server.eventstore.OptimisticLockingException: Verison 1 was overtaken by 1 for 09357343899a
```

I also explicit set hazelcast.enabled: false

/close ?

**Comment by asibross** [comment]
FYI, I am seeing that same error.

**Comment by joshiste** [comment]
@asibross can you give me some details about your setup? Are you using some sc-disvocery or hazelcast?

**Comment by asibross** [comment]
I have my own registration based on Discovery. Its very similar to the existing InstanceDiscoveryListener only that I don't use the DiscoveryClient but rather make a call to Eureka endpoint directly and parse the data. The reason I am doing it is to support multiple region which the discovery client does not support.

**Comment by asibross** [comment]
Looks like this issue manifests when both InstanceDiscoveryListener and StatusUpdaterTrigger are in play.
If I disable the StatusUpdaterTrigger (just for debugging), I don't see that error anymore.

**Comment by asibross** [comment]
There seem to be a race condition here:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/StatusUpdater.java#L64

Between the time the immutable instance is retrieved from the repository until the call to update the status info, another registration event can occur using the same version of the instance.

**Comment by joshiste** [comment]
> If I disable the StatusUpdaterTrigger (just for debugging), I don't see that error anymore.

Thats obvious, as the stacktrace tells StatusUpdaterTrigger is part of the issue.
