### ISSUE TITLE
Couldn't retrieve status for Instance: consul , port : 8300

### ISSUE THREAD

**Issue by godpit** [codecentric/spring-boot-admin#1062]
But, i can not find the port 8300, how to set that?

**Comment by godpit** [comment]
Couldn't retrieve status for Instance(id=8c783b08a061, version=0, registration=Registration(name=consul, managementUrl=http://127.0.0.1:8300/actuator, healthUrl=http://127.0.0.1:8300/actuator/health, serviceUrl=http://127.0.0.1:8300/, source=discovery), registered=true, statusInfo=StatusInfo(status=UNKNOWN, details={}), statusTimestamp=2019-01-09T03:05:03.607Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://127.0.0.1:8300/actuator/health)}), buildVersion=null)

**Comment by godpit** [comment]
spring boot 2.0.1, spring boot admin 2.0.1

**Comment by joshiste** [comment]
I guess the "consul" service is not really a spring boot service. You may want to exclude it via setting `spring.boot.admin.discovery.ignored-services`

**Comment by godpit** [comment]
the consul is a registry center , replace with eureka

**Comment by godpit** [comment]
2019-01-09 15:26:55.555  INFO 3937 --- [           main] o.s.c.c.b.ConsulInboundMessageProducer   : started org.springframework.cloud.consul.binder.ConsulInboundMessageProducer@2820b369
2019-01-09 15:26:55.626  INFO 3937 --- [ctor-http-nio-1] d.c.b.a.server.services.StatusUpdater    : Couldn't retrieve status for Instance(id=8c783b08a061, version=0, registration=Registration(name=consul, managementUrl=http://127.0.0.1:8300/actuator, healthUrl=http://127.0.0.1:8300/actuator/health, serviceUrl=http://127.0.0.1:8300/, source=discovery), registered=true, statusInfo=StatusInfo(status=UNKNOWN, details={}), statusTimestamp=2019-01-09T07:26:55.457Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://127.0.0.1:8300/actuator/health)}), buildVersion=null)

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-buffer-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345) ~[netty-transport-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-transport-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-transport-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-transport-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[netty-transport-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) ~[netty-common-4.1.23.Final.jar:4.1.23.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]

2019-01-09 15:26:55.687  INFO 3937 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8764 (http) with context path ''

**Comment by sandy3004** [comment]
I am also facing the same issue .

[ctor-http-nio-3] d.c.b.a.server.services.StatusUpdater    : Couldn't retrieve status for Instance(id=6783039ebea0, version=0, registration=Registration(name=spring-boot-application, managementUrl=http://d6e38a0ba946:8080/actuator, healthUrl=http://d6e38a0ba946:8080/actuator/health, serviceUrl=http://d6e38a0ba946:8080/, source=http-api), registered=true, statusInfo=StatusInfo(status=UNKNOWN, details={}), statusTimestamp=2019-08-21T14:11:43.363Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://d6e38a0ba946:8080/actuator/health)}), buildVersion=null, tags=Tags(values={}))

java.net.UnknownHostException: d6e38a0ba946
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_201]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[na:1.8.0_201]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[na:1.8.0_201]
