### ISSUE TITLE
[1.5.7] o.a.coyote.http11.Http11Processor#log:182 - The host [vortex-win.:8080] is not valid

### ISSUE THREAD

**Issue by paulvi** [codecentric/spring-boot-admin#1067]
When using SBA 1.5.7 with Spring Boot 1.5.17  (thanks to https://github.com/vojtechruz/spring-boot-admin/tree/1.x example)
and `server.port=8080` in `application.properties`

I got error about `[vortex-win.:8080] is not valid` that I think is not appropriate, should not happen.

```
11:28:22.180 [http-nio-8080-exec-3] INFO  o.a.coyote.http11.Http11Processor#log:182 - The host [vortex-win.:8080] is not valid
 Note: further occurrences of request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: The character [:] is not valid after a period in a domain name.
	at org.apache.tomcat.util.http.parser.HttpParser$DomainParseState.next(HttpParser.java:928)
	at org.apache.tomcat.util.http.parser.HttpParser.readHostDomainName(HttpParser.java:842)
	at org.apache.tomcat.util.http.parser.Host.parse(Host.java:66)
	at org.apache.tomcat.util.http.parser.Host.parse(Host.java:40)
	at org.apache.coyote.AbstractProcessor.parseHost(AbstractProcessor.java:286)
	at org.apache.coyote.http11.Http11Processor.prepareRequest(Http11Processor.java:1203)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:776)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joshiste** [comment]
looks to me that you hostname contains a dot?

**Comment by paulvi** [comment]
OK
