### ISSUE TITLE
Spring Boot admin Shows Instance down on PCF

### ISSUE THREAD

**Issue by Vibhor116** [codecentric/spring-boot-admin#1090]
I am trying to integrate SBA to my business application and when I'm trying to deploy into PCF , i'm running on error as shown in image below.
<img width="817" alt="sba" src="https://user-images.githubusercontent.com/19369705/52645845-9e61d900-2f07-11e9-9b42-8093314d9150.PNG">

my application.properties are as follows 

```spring.boot.admin.client.url=https://sba-demo.pcf.yyy.com
spring.application.name=some-service-sba
spring.boot.admin.client.prefer-ip=true

spring.boot.admin.client.management-url=https://some-service-sba.pcf.yyy.com/manage
spring.boot.admin.client.health-url= https://some-service-sba.pcf.yyy.com/manage/health
spring.boot.admin.client.service-url= https://https://some-service-sba.pcf.yyy.com

management.endpoints.web.base-path=/manage
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
```
My relevant POM.xml is as follows 

```
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>
	<dependency>
			<groupId>io.pivotal.spring.cloud</groupId>
			<artifactId>spring-cloud-services-starter-config-client</artifactId>
	</dependency>
    <dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-starter-client</artifactId>
    <version>2.0.1</version>
	</dependency>
```
Logs on PCF @SBA server 

```
2019-02-12T20:55:38.471+05:30 [APP/PROC/WEB/0] [OUT] java.lang.IllegalStateException: Calling [asyncError()] is not valid for a request with Async state [MUST_DISPATCH]
2019-02-12T20:55:38.471+05:30 [APP/PROC/WEB/0] [OUT] 2019-02-12 15:25:38.470 ERROR 25 --- [nio-8080-exec-8] o.a.catalina.connector.CoyoteAdapter : Exception while processing an asynchronous request
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:239) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:382) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.Request.action(Request.java:430) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:512) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AsyncStateMachine.asyncError(AsyncStateMachine.java:440) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] java.lang.IllegalStateException: Calling [asyncError()] is not valid for a request with Async state [MUST_DISPATCH]
2019-02-12T20:55:42.127+05:30 [APP/PROC/WEB/0] [OUT] 2019-02-12 15:25:42.127 ERROR 25 --- [io-8080-exec-10] o.a.catalina.connector.CoyoteAdapter : Exception while processing an asynchronous request
```

It's working fine when I'm running in on  localhost .

Environment info 

Spring boot 2.0.5
Java 8

Any ideas ?

**Comment by joshiste** [comment]
for PCF at best use the spring cloud discovery client for cloudfoundry and read this short hints on it:
https://codecentric.github.io/spring-boot-admin/current/#_cloudfoundry

**Comment by Vibhor116** [comment]
@joshiste 

After reading the docs i"ve changed 

```
spring.boot.admin.client.management-url=https://some-service-sba.pcf.yyy.com/manage
spring.boot.admin.client.health-url= https://some-service-sba.pcf.yyy.com/manage/health
spring.boot.admin.client.service-url= https://https://some-service-sba.pcf.yyy.com
```
to

```
spring.boot.admin.client.**instance**.management-url=https://some-service-sba.pcf.yyy.com/manage
spring.boot.admin.client..**instance**.health-url= https://some-service-sba.pcf.yyy.com/manage/health
spring.boot.admin.client.**instance**.service-url= https://https://some-service-sba.pcf.yyy.com
```
and it worked fine for me .

Does the later configuration  is only applicable to PCF  ? what's the difference between those two?
