### ISSUE TITLE
java.lang.IllegalArgumentException: Event 2 doesn't match exptected version 1

### ISSUE THREAD

**Issue by codingDriver** [codecentric/spring-boot-admin#1149]
Sometimes the spring boot admin server logs a lot of error messages:

```
class java.lang.IllegalArgumentException occurred in current ReST call
java.lang.IllegalArgumentException: Event 2 doesn't match exptected version 1
	at org.springframework.util.Assert.isTrue(Assert.java:136)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:217)
	at de.codecentric.boot.admin.server.domain.entitiesInstance.apply(Instance.java:211)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:205)
	at de.codecentric.boot.admin.server.domain.entities.EventsourcingInstanceRepository.lambda$find$3(EventsourcingInstanceRepository.java:64)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:273)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:331)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1505)
	at reactor.core.publisher.MonoCollectList$MonoBufferAllSubscriber.onComplete(MonoCollectList.java:123)
	at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:333)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:198)
	at reactor.core.publisher.MonoCollectList$MonoBufferAllSubscriber.onSubscribe(MonoCollectList.java:90)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:59)
	at reactor.core.publisher.MonoFilterFuseable.subscribe(MonoFilterFuseable.java:44)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:56)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:56)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:85)
	at reactor.core.publisher.MonoRetryWhen.subscribe(MonoRetryWhen.java:50)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$DeferredResultSubscriber.connect(ReactiveTypeHandler.java:440)
	at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler.handleValue(ReactiveTypeHandler.java:155)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler.handleReturnValue(ResponseBodyEmitterReturnValueHandler.java:139)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Before we got these ERROR messages, we got the following INFO messages:

```
Couldn't retrieve status for Instance(id=6e3360c11887, version=42, registration=Registration(name=foobar, managementUrl=http://b81b3ae18874:8085/foobar/actuator, healthUrl=http://b81b3ae18874:8085/foobar/actuator/health, serviceUrl=http://b81b3ae18874:8085/foobar, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={}), statusTimestamp=2019-04-24T10:18:50.176Z, info=Info(values={}), endpoints=Endpoints(endpoints={httptrace=Endpoint(id=httptrace, url=http://b81b3ae18874:8085/foobar/actuator/httptrace), caches=Endpoint(id=caches, url=http://b81b3ae18874:8085/foobar/actuator/caches), health=Endpoint(id=health, url=http://b81b3ae18874:8085/foobar/actuator/health), liquibase=Endpoint(id=liquibase, url=http://b81b3ae18874:8085/foobar/actuator/liquibase), heapdump=Endpoint(id=heapdump, url=http://b81b3ae18874:8085/foobar/actuator/heapdump), mappings=Endpoint(id=mappings, url=http://b81b3ae18874:8085/foobar/actuator/mappings), scheduledtasks=Endpoint(id=scheduledtasks, url=http://b81b3ae18874:8085/foobar/actuator/scheduledtasks), configprops=Endpoint(id=configprops, url=http://b81b3ae18874:8085/foobar/actuator/configprops), beans=Endpoint(id=beans, url=http://b81b3ae18874:8085/foobar/actuator/beans), threaddump=Endpoint(id=threaddump, url=http://b81b3ae18874:8085/foobar/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://b81b3ae18874:8085/foobar/actuator/metrics), conditions=Endpoint(id=conditions, url=http://b81b3ae18874:8085/foobar/actuator/conditions), jolokia=Endpoint(id=jolokia, url=http://b81b3ae18874:8085/foobar/actuator/jolokia), info=Endpoint(id=info, url=http://b81b3ae18874:8085/foobar/actuator/info)}), buildVersion=null, tags=Tags(values={}))
io.netty.channel.ConnectTimeoutException: connection timed out: b81b3ae18874/10.0.0.117:8085
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:570)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)
```
Yes, we have some network problems in our test environments -sometimes ;) But it looks like that the internal instance state of the spring boot admin and the clients (docker apps) diverge. The ERROR logs kills out docker environment.

We use:
spring boot and spring boot admin 2.1.4.RELEASE
The versions of the spring boot admin client are not all up-to-date

**Comment by joshiste** [comment]
Are you using hazelcast?

**Comment by mohitsingh89** [comment]
Same is happening in our case, generating lots of logs with the below kind of messages: 
**Event 100 doesn't match expected version 1**
Not using Hazelcast.

**Comment by codingDriver** [comment]
> Are you using hazelcast?

No! We don't use hazelcast

**Comment by pigxcloud** [comment]
same problem

**Comment by mielecmichal** [comment]
Still occurring 

```
java.lang.IllegalArgumentException: Event 96 doesn't match exptected version 1
	at org.springframework.util.Assert.isTrue(Assert.java:136)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:217)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:211)
	at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:205)
	at de.codecentric.boot.admin.server.domain.entities.EventsourcingInstanceRepository.lambda$find$3(EventsourcingInstanceRepository.java:64)
```

**Comment by rflammia** [comment]
Me too

**Comment by rflammia** [comment]
I had the same problem. restarted admin and it's gone

**Comment by tiaoxixiaoji** [comment]
same problem, too 
spring-boot-admin-server 2.1.4
