### ISSUE TITLE
Can't send mail on state change (Spring Boot 1.3.0RC1)

### ISSUE THREAD

**Issue by Hodkinson** [codecentric/spring-boot-admin#119]
When adding spring mail properties (using Spring Boot 1.3.0RC1), got the following exception at start up.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.codecentric.boot.admin.notify.MailNotifier]: Factory method 'mailNotifier' threw exception; nested exception is java.lang.NoSuchMethodError: de.codecentric.boot.admin.config.MailNotifierConfiguration.mailSender()Lorg/springframework/mail/javamail/JavaMailSender;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 23 more
Caused by: java.lang.NoSuchMethodError: de.codecentric.boot.admin.config.MailNotifierConfiguration.mailSender()Lorg/springframework/mail/javamail/JavaMailSender;
	at de.codecentric.boot.admin.config.MailNotifierConfiguration.mailNotifier(MailNotifierConfiguration.java:47)
	at de.codecentric.boot.admin.config.MailNotifierConfiguration$$EnhancerBySpringCGLIB$$ac78481a.CGLIB$mailNotifier$0(<generated>)
	at de.codecentric.boot.admin.config.MailNotifierConfiguration$$EnhancerBySpringCGLIB$$ac78481a$$FastClassBySpringCGLIB$$f2e9d2ac.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
	at de.codecentric.boot.admin.config.MailNotifierConfiguration$$EnhancerBySpringCGLIB$$ac78481a.mailNotifier(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
```

**Comment by joshiste** [comment]
Are you using Spring Boot Admin 1.2.x with Spring Boot 1.3.0? For the server this won't work. The master branch has been updated to Spring Boot 1.3.0

**Comment by Hodkinson** [comment]
I am, yes. Thanks for the update.
