### ISSUE TITLE
Unable to start admin due some ClassCastException

### ISSUE THREAD

**Issue by staleks** [codecentric/spring-boot-admin#120]
Hi,

I've followed README.md file, with some "small" modifications since I am using Gradle instead of Maven.

so here is the build.gradle
```
dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Brixton.M1"
	}
}

dependencies {
	
	compile('org.springframework.cloud:spring-cloud-starter-eureka-server')
	compile('org.springframework.cloud:spring-cloud-starter-zuul')
	
	compile 'de.codecentric:spring-boot-admin-server:1.2.4'
	compile 'de.codecentric:spring-boot-admin-server-ui:1.2.4'
	
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

Main application file is:
```
@SpringBootApplication
@EnableDiscoveryClient
@EnableAdminServer
public class SpringBootAdminServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringBootAdminServerApplication.class, args);

	}
}
```

and last but not least, application.yml file:
```
info:
  version: 1.0.0
  
server:
  port: 8585
  
spring:
  application:
    name: ESBAA
  cloud:
    config:
      enabled: false    
      
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
```

So once I try to start application, here is the output
```
2015-10-31 00:13:36.031 ERROR 13458 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at de.codecentric.boot.admin.registry.StatusUpdater.queryStatus(StatusUpdater.java:92) ~[spring-boot-admin-server-1.2.4.jar:1.2.4]
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:70) ~[spring-boot-admin-server-1.2.4.jar:1.2.4]
	at de.codecentric.boot.admin.config.AdminServerWebConfiguration$2.onApplicationEvent(AdminServerWebConfiguration.java:136) ~[spring-boot-admin-server-1.2.4.jar:1.2.4]
	at de.codecentric.boot.admin.config.AdminServerWebConfiguration$2.onApplicationEvent(AdminServerWebConfiguration.java:132) ~[spring-boot-admin-server-1.2.4.jar:1.2.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at de.codecentric.boot.admin.registry.ApplicationRegistry.register(ApplicationRegistry.java:86) ~[spring-boot-admin-server-1.2.4.jar:1.2.4]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:79) ~[spring-boot-admin-server-1.2.4.jar:1.2.4]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onApplicationEvent(ApplicationDiscoveryListener.java:57) ~[spring-boot-admin-server-1.2.4.jar:1.2.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:109) ~[spring-cloud-netflix-core-1.1.0.M1.jar:1.1.0.M1]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	... 19 common frames omitted
Wrapped by: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration'; nested exception is java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:847) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:667) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:342) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:980) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at rs.in.staleksit.evidencija.spring.boot.admin.server.SpringBootAdminServerApplication.main(SpringBootAdminServerApplication.java:15) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.0.M5.jar:1.3.0.M5]
```

NOTE: I've already started Eureka server at port 8761.
This is because I would like not to change each of services but to have 2nd setup as explained in README.md document. Spring Boot Admin app. should contact Eureka Server and fetch needed information from there.

Can you please help me on this issue? 
Thank you

**Comment by staleks** [comment]
Ok, to put more info in investigation of this issue.

I've checked more logs and found that on Spring Cloud Config Server (another component of my system), I was receiving 404. 
I checked the reason for this, and found out that I had this in application.yml of Spring Cloud Config Server
```
management:
     context-path: /admin
```

As a side effect, spring cloud config wasn't be able to find

localhost:8888/health, but rather it was moved to localhost:8888/admin/health

Once I get this to default one, Spring Boot Admin was able to start.


Now I can get admin-ui but I can see just 3 services:
- config server (port: 8888)
- itself, spring boot admin (port: 8585) and
- zuul (port: 8765)

I have other services, 2, 3 more microService that I can see from eureka side, but those are not visible from Spring Boot Admin app.

**Comment by joshiste** [comment]
Can you debug into the `ApplicationDiscoveryListener.discover()`? Please have a look if the discoveryClient returns all services and all instances to the services?

**Comment by joshiste** [comment]
@staleks any findings?

**Comment by staleks** [comment]
Hi,

you just made your point :)

You are 100% right, so this part is producing exception:

```
public void discover() {
		for (String serviceId : discoveryClient.getServices()) {
			for (ServiceInstance instance : discoveryClient.getInstances(serviceId)) {
				registry.register(convert(instance));
			}
		}
	}
```

**Comment by joshiste** [comment]
Can you try a snapshot from https://oss.sonatype.org/content/repositories/snapshots to see if all your problems are gone?

**Comment by staleks** [comment]
My spot light goes to this:

Please note that there is `convert(instance)`.

I've debbuged a bit more:

```
String healthUrl = append(managementUrl, healthEndpoint);
```

When I execute this: I've got
```
2015-11-07 21:28:32.895 DEBUG 10116 --- [  restartedMain] o.s.web.client.RestTemplate              : GET request for "http://192.168.1.103:8888/health" resulted in 404 (Not Found)
```

which is clearly not ok, since it has mngmt part /admin before /health.

**Comment by joshiste** [comment]
This is related  to #94 unfortunatly the DiscoveryClient exposes not enough informations. But if all your eurekat apps have the same mgmt-path you can set `spring.boot.admin.discovery.management.context-path=/admin`

**Comment by staleks** [comment]
Actually, your previous suggestion fixed that stuff.

**Comment by staleks** [comment]
I've just downloaded it and start all 4:
- eureka
- cloud config server
- my microService and
- spring boot admin

Everything is fine so far.


Related to your last post, I am even wondering if I will need config server to have /admin, but
that was some example that I've used in process of evaluation.

Can you tell me, what is road map for 1.3.0-SNAPSHOT ?
Release comming soon ?

**Comment by staleks** [comment]
Further more, I've noticed that services that has log defined, I don't need jolokia anymore? Am I right?

**Comment by joshiste** [comment]
I think it will happen just right after spring-boot 1.3.0.RELEASE.

For logfile acces you don't need jolokia, but for changing loglevels.

Since your issues are resolved I'm closing this issue.

**Comment by staleks** [comment]
yes, you can close. 

Thank You for support.

**Comment by sallampalli** [comment]
I think I have a similar situation.
 I am trying to centralize Eureka, Zuul, Config Server, SpringBoot Admin Server etc.. in a single component.
(Using spring cloud parent 1.0.0.RELEASE and SpringBootAdmin 1.3.2)

@SpringBootApplication
@EnableAdminServer
@EnableEurekaServer
@EnableZuulProxy

This combination results in 

Could not autowire field: private org.springframework.cloud.netflix.zuul.filters.ProxyRouteLocator org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration$RoutesEndpointConfiguration.routeLocator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.netflix.zuul.filters.ProxyRouteLocator.

If I remove AdminServer out of the picture, it works just fine. Also, how do I tell the AdminServer to use the same port defined for eureka but a different context path ?
