### ISSUE TITLE
 Event 0 must be greater or equal to 1

### ISSUE THREAD

**Issue by zhujiebing** [codecentric/spring-boot-admin#1231]
Hi,
when I start sba server after multiple client services,  sba show a warning log as follows。 

2019-08-03 14:19:23.703  WARN 16948 --- [TaskScheduler-1] b.a.s.d.e.SnapshottingInstanceRepository : Error while updating the snapshot with event InstanceRegisteredEvent(super=InstanceEvent(instance=694cb62e0030, version=0, timestamp=2019-08-03T06:19:23.564Z, type=REGISTERED), registration=Registration(name=cvnavi-mss-auth-center, managementUrl=http://DESKTOP-6CSCCCJ.mshome.net:18001/actuator, healthUrl=http://DESKTOP-6CSCCCJ.mshome.net:18001/actuator/health, serviceUrl=http://DESKTOP-6CSCCCJ.mshome.net:18001/, source=discovery))

java.lang.IllegalArgumentException: Event 0 must be greater or equal to 1
    at org.springframework.util.Assert.isTrue(Assert.java:136)
    at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:215)
    at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:209)
    at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository.lambda$updateSnapshot$5(SnapshottingInstanceRepository.java:100)
    at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository$$Lambda$927/197941885.apply(Unknown Source)
    at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
    at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository.updateSnapshot(SnapshottingInstanceRepository.java:98)
    at de.codecentric.boot.admin.server.domain.entities.SnapshottingInstanceRepository$$Lambda$580/1216889437.accept(Unknown Source)
    at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
    at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
    at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:474)
    at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:253)
    at reactor.core.publisher.UnicastProcessor.drainFused(UnicastProcessor.java:277)
    at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:310)
    at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:386)
    at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
    at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:248)
    at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:168)
    at de.codecentric.boot.admin.server.eventstore.InstanceEventPublisher.lambda$publish$0(InstanceEventPublisher.java:44)
    at de.codecentric.boot.admin.server.eventstore.InstanceEventPublisher$$Lambda$926/1731430927.accept(Unknown Source)

Thank you very much!

**Comment by joshiste** [comment]
please provide a project to reproduce the issue.

**Comment by zhujiebing** [comment]
> please provide a project to reproduce the issue.

Hi, as follows。
https://github.com/zhujiebing/sbaconsul

First run config and then run config2 finally run monitor.  
and it can reproduce. 

Thank you very much!  Thank you for your time and I look forward to your reply.

**Comment by joshiste** [comment]
Are any infrastructure components needed?

**Comment by zhujiebing** [comment]
> Are any infrastructure components needed?

only need consul server.  I am using consul_1.4.4_windows_amd64.

Thanks.

**Comment by zhujiebing** [comment]
Hi,
can you reproduce it?    

Thank you for your time and I look forward to your reply.

**Comment by zhujiebing** [comment]
> Are any infrastructure components needed?

Hi,
can you reproduce it?

Thank you for your time and I look forward to your reply.

**Comment by joshiste** [comment]
What i've figured out so far: The snapshot was updated in between because of optimistic lock exceptions and doesn't need to be updated when the event is consumed by the snapshot updating function. Therefore the logged exception is a bit irritating but doesn't do any harm.

That's why I'm not going to realease this fix for the 2.1.x branch.

**Comment by zhujiebing** [comment]
Thank you!

**Comment by zhujiebing** [comment]
> What i've figured out so far: The snapshot was updated in between because of optimistic lock exceptions and doesn't need to be updated when the event is consumed by the snapshot updating function. Therefore the logged exception is a bit irritating but doesn't do any harm.
> 
> That's why I'm not going to release this fix for the 2.1.x branch.

Hi,
When will 2.1.7 version be released?  Thank you !
