### ISSUE TITLE
Exception occurred: Calling [asyncError()] is not valid for a request with Async state

### ISSUE THREAD

**Issue by Ask149** [codecentric/spring-boot-admin#1274]
I have referenced the above issue #1039 , but did not receive any answer to my error.

While developing a simple Spring Boot Admin application using Custom UI, I have encountered the below exception: 

`java.lang.IllegalStateException: Calling [asyncError()] is not valid for a request with Async state [MUST_DISPATCH]
	at org.apache.coyote.AsyncStateMachine.asyncError(AsyncStateMachine.java:440) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:512) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.Request.action(Request.java:430) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:401) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:239) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]`

Could you please look into the above issue, and help to find an appropriate solution.

Thanks in advance!

**Comment by joshiste** [comment]
The answer is the same as in https://github.com/codecentric/spring-boot-admin/issues/1039#issuecomment-449599963

**Comment by liangxiong3403** [comment]
upgrade tomcat version tosolve problem;

1. spring-boot:2.2.0.RELEASE
2.`<tomcat.version>9.0.29</tomcat.version>`
3.spring-boot-admin-starter-server：2.2.0
4.spring-boot-admin-starter-client：2.2.0
