### ISSUE TITLE
A large number of exceptions, leading to exhaustion of disk space

### ISSUE THREAD

**Issue by beiketianzhuang** [codecentric/spring-boot-admin#1321]
**Question**
It looks like the program has done a lot of retries. Can you avoid such endless retries?
`retryWhen(Retry.any() .retryMax(Long.MAX_VALUE).doOnRetry(ctx -> log.warn("Unexpected error", ctx.exception())))`

**Bug report**
[WARN] d.c.b.a.s.n.NotificationTrigger: Unexpected error
reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
	at reactor.core.Exceptions.failWithRejected(Exceptions.java:249)
	at reactor.core.publisher.Operators.onRejectedExecution(Operators.java:807)
	at reactor.core.publisher.FluxSubscribeOn.subscribe(FluxSubscribeOn.java:73)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)
	at reactor.core.publisher.FluxDoFinally.subscribe(FluxDoFinally.java:73)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7923)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(FluxRetryWhen.java:184)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onNext(FluxRetryWhen.java:230)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:275)
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:849)
	....
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3072123c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@11f7104b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:549)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:648)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681)
	at reactor.core.scheduler.Schedulers.workerSchedule(Schedulers.java:904)
	at reactor.core.scheduler.ExecutorServiceWorker.schedule(ExecutorServiceWorker.java:43)
	at reactor.core.publisher.FluxSubscribeOn.subscribe(FluxSubscribeOn.java:69)

**Comment by jim213** [comment]
Have you repaired it? How to solve it?

**Comment by beiketianzhuang** [comment]
> Have you repaired it? How to solve it? I had the same problem

upgrade to the latest version
