### ISSUE TITLE
Issue Deploying the applicaiton to weblogic 12.2.1.3

### ISSUE THREAD

**Issue by jmpuyo** [codecentric/spring-boot-admin#1359]
Hello,

I am trying to deploy spring-boot-admin in our weblogic server in order to monitor our applications.

I have tried changing versions of the library and spring with no success. I am constantly getting the following issue:

<19-Feb-2020 11:16:15,883 o'clock CET> <Notice> <Stdout> <BEA-000000> <2020-02-19 11:16:15 [registrationTask1] WARN  d.c.b.a.c.r.ApplicationRegistrator - Failed to register application as Application(name=Spring boot admin server, managementUrl=http://localhost:7001/spring-boot-admin-java/actuator, healthUrl=http://localhost:7001/spring-boot-admin-java/actuator/health, serviceUrl=http://localhost:7001/spring-boot-admin-java) at spring-boot-admin ([http://localhost:7001/instances]): 404 Not Found: [<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN">
<HTML>
<HEAD>
<TITLE>Error 404--Not Found</TITLE>
</HEAD>
<BODY bgcolor="white">
<FONT FACE=Helvetica><BR CLEAR=all>
<TABLE border=0 cellspacing... (1164 bytes)]. Further attempts are logged on DEBUG level> 

<19-Feb-2020 11:16:16,850 o'clock CET> <Error> <HTTP> <BEA-101165> <Could not load user defined filter in web.xml: de.codecentric.boot.admin.server.ui.web.servlet.HomepageForwardingFilter.
java.lang.AbstractMethodError
	at weblogic.servlet.internal.FilterManager$FilterInitAction.run(FilterManager.java:400)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	Truncated. see log file for complete stacktrace
> 

[2020-02-19 11:16:17,099] Artifact spring-boot-admin-java:war exploded: Artifact is deployed successfully
[2020-02-19 11:16:17,099] Artifact spring-boot-admin-java:war exploded: Deploy took 14,821 milliseconds

If anyone has a solution for this it would be greatly appreciated or if any extra information is needed from my side please let me know.

Best regards,

Juan Manuel Puyo Negret

**Comment by joshiste** [comment]
If the log is from you SBA server and it should register at itself the `spring.boot.admin.url` looks wrong. I guess it should be http://localhost:7001/spring-boot-admin-java instead of http://localhost:7001/
