### ISSUE TITLE
Exception on Startup when using PreferIP

### ISSUE THREAD

**Issue by DesFieldCorbett** [codecentric/spring-boot-admin#1407]
I see the following exception on clients, however once they startup the connect to the SBA fine. However the exception is annoying our monitoring:
```
ERROR [registrationTask1] - [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler] [] - Unexpected error occurred in scheduled task
java.lang.IllegalStateException: couldn't determine local port. Please set spring.boot.admin.client.instance.service-base-url.
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getLocalServerPort(DefaultApplicationFactory.java:192)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceBaseUrl(DefaultApplicationFactory.java:104)
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getServiceUrl(ServletApplicationFactory.java:63)
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementBaseUrl(ServletApplicationFactory.java:76)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:154)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:80)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:58)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
 
I am using:
Admin server: 2.2.2
Admin client: 2.2.2
On Openshift 3.x

Config on Admin:
`spring.boot.admin.discovery.enabled=true`

Config on client:
```
spring.boot.admin.client.url= XXX
spring.boot.admin.client.instance.prefer-ip=true
```

**Comment by joshiste** [comment]
Are you deploying as a war into a servlet container?

**Comment by DesFieldCorbett** [comment]
we use embedeed tomcat

**Comment by joshiste** [comment]
Ok for the embedded tomcat this exception should not be thrown.
Do you have a project to reproduce the issue?

HINT: When using Openshift you could remove the sba-client from all your applications and use the spring-cloud-kubernetes-discovery for the sba-server...

**Comment by DesFieldCorbett** [comment]
Unfortunately the project is internal. Let me see what I can do.

We use Discovery in our Dev env but it needs additional permissions we dont want to give in the others.

**Comment by joshiste** [comment]
Do you have a project for me to reproduce the issue?

**Comment by joshiste** [comment]
Did you check if the exception occurs also when prefer-ip is false?
Imho this option has no part in the exception.

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by hbelhassine** [comment]
Some more feedback about this issue : 
We have the same exception on application startup using spring-boot-admin-client.
After debugging, the exception occurs when the registrator scheduler start before the spring context loading is complete.
In fact, we use spring-cloud-stream so the application startup may be a little slow due to the binding creations.
The workaround that I founded is to redefine  ApplicationFactory bean in order to pickup the port directly from the configuration, like that 

```
    @Bean
    @Lazy(false)
    public ApplicationFactory applicationFactory(InstanceProperties instance, ManagementServerProperties management,
                                                 ServerProperties server, ServletContext servletContext, PathMappedEndpoints pathMappedEndpoints,
                                                 WebEndpointProperties webEndpoint, ObjectProvider<List<MetadataContributor>> metadataContributors,
                                                 DispatcherServletPath dispatcherServletPath) {
        return new ServletApplicationFactory(instance, management, server, servletContext, pathMappedEndpoints,
                webEndpoint,
                new CompositeMetadataContributor(metadataContributors.getIfAvailable(Collections::emptyList)),
                dispatcherServletPath) {
            @Override
            protected Integer getLocalServerPort() {
                return server.getPort();
            }

            protected Integer getLocalManagementPort() {
                Integer managementPort = management.getPort();
                if (managementPort == null) {
                    managementPort = getLocalServerPort();
                }
                return managementPort;
            }
        };
    }
```
Of course this workaround can work only for servlet container and I'm not sure that it suits everyone. But it works for me.

We use spring-boot 2.3.4 and spring-boot-admin-client 2.3.0.
