### ISSUE TITLE
Admin server make server load to high

### ISSUE THREAD

**Issue by csloter** [codecentric/spring-boot-admin#1427]
We have one admin server on ip 192.168.6.31, and some client 
admin server use spring boot, 2.1.0.RELEASE, jdk1.8.0_111, deploy on aws ec2
admin server pom.xml
```
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>2.1.6</version>
        </dependency>
```
SpringApplication 
```
@Configuration
@EnableAutoConfiguration
@EnableAdminServer
public class AdminApplication {
    public static void main(String[] args) {
        SpringApplication.run(AdminApplication.class, args);
    }
}
```
applicaiton.properties config just one line 
```
server.port=10000
```
client  use same sprint boot and jdk
application.properties
```
...
#actuator config
management.server.port=30155
management.server.address=${host}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/my-client-name
#admin config
spring.boot.admin.client.url=http://192.168.6.31:10000
spring.boot.admin.client.instance.name=my-client-name
spring.boot.admin.client.instance.prefer-ip=true
...
```
about 10 client use same config 
around 4:30 every day  the admin server (8 core cpu) 's  load suddenly increased,  1 m load
may to 75 or more.

and the server log
```
2020-05-13 04:35:43.199 [reactor-http-client-epoll-17] ERROR r.n.r.PooledConnectionProvider - [id: 0x7c5960de, L:/192.168.6.31:53629 ! R:192.168.6.64/192.168.6.64:27035] Pooled connection observed an error
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
2020-05-13 04:37:41.559 [reactor-http-client-epoll-15] ERROR r.n.r.PooledConnectionProvider - [id: 0x002c3301, L:/192.168.6.31:60809 ! R:192.168.6.64/192.168.6.64:21055] Pooled connection observed an error
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
2020-05-13 04:37:41.559 [reactor-http-client-epoll-19] ERROR r.n.r.PooledConnectionProvider - [id: 0xc3458ca5, L:/192.168.6.31:65492 ! R:192.168.6.66/192.168.6.66:21055] Pooled connection observed an error
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
2020-05-13 04:37:41.607 [reactor-http-client-epoll-19] ERROR r.n.r.PooledConnectionProvider - [id: 0xc253cdf7, L:/192.168.6.31:47874 ! R:192.168.6.65/192.168.6.65:21055] Pooled connection observed an error
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
2020-05-13 04:37:41.609 [parallel-1] WARN  d.c.b.a.s.services.IntervalCheck - Unexpected error in status-check
reactor.core.Exceptions$OverflowException: Could not emit tick 8624 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:215)
        at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:130)
        at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
        at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2020-05-13 04:38:41.611 [reactor-http-client-epoll-14] ERROR r.n.r.PooledConnectionProvider - [id: 0xbb6a154a, L:/192.168.6.31:47963 ! R:1192.168.6.65/192.168.6.65:21055] Pooled connection observed an error
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
2020-05-13 04:38:41.663 [reactor-http-client-epoll-17] ERROR r.n.r.PooledConnectionProvider - [id: 0xed6b7e83, L:/192.168.6.31:60916 ! R:192.168.6.64/192.168.6.64:21055] Pooled connection observed an error
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
2020-05-13 05:04:59.973 [parallel-4] WARN  d.c.b.a.s.services.IntervalCheck - Unexpected error in info-check
reactor.core.Exceptions$OverflowException: Could not emit tick 7208 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:215)
        at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:130)
        at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
        at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
``` 

client log

```
2020-05-13 04:32:30.565 [registrationTask1] WARN  d.c.b.a.c.r.ApplicationRegistrator - Failed to register application as Application(name=my-client-name, managementUrl=http://192.168.6.64:30155/my-client-name, healthUrl=http://192.168.6.64:30155/my-client-name/health, serviceUrl=http://192.168.6.64:30150/) at spring-boot-admin ([http://192.168.6.31:10000/instances]): I/O error on POST request for "http://192.168.6.31:10000/instances": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out. Further attempts are logged on DEBUG level
```

And it's normal run for half a year,  bug  recently  about two week ago we found this problem. we check our net ,memory, disk .. it's ok, and we did not change any server's config. 
Can you help find out the reason for the problem and show us how to solve it

**Comment by joshiste** [comment]
Hmm.. could you update to the latest Spring Boot 2.1.x (or even 2.2.x and SBA 2.2.x) ? Just to be sure to have the most recent libraries...

**Comment by csloter** [comment]
Thank your for your replay. Okay, let's try to upgrade Spring Boot version

**Comment by joshiste** [comment]
@csloter any new observations?

**Comment by joshiste** [comment]
closed du to missing feedback. If you have some news on this we can reopen the ticket.
