### ISSUE TITLE
Metadata key "user.name" and "user.password" are not be supported by consul

### ISSUE THREAD

**Issue by Macrame** [codecentric/spring-boot-admin#1456]
The `BasicAuthHttpHeaderProvider` then uses this metadata to add the Authorization header to access your application’s actuator endpoints. And the code looks like this:
```
String username = instance.getRegistration().getMetadata().get("user.name");
String password = instance.getRegistration().getMetadata().get("user.password");
```
As Spring Cloud [reference](https://cloud.spring.io/spring-cloud-consul/reference/html/#metadata), Consul supports metadata on services. My application.yaml file contains below:
```
spring:
    cloud:
        consul:
            discovery:
                metadata:
                    user.name: spring_boot
                    userassword: MY_PASSWORD
```
Unfortunately, consul client library(consul-api-1.4.5.jar) reported an error coming from the consul server.
```
Caused by: com.ecwid.consul.v1.OperationException: OperationException(statusCode=400, statusMessage='Bad Request', statusContent='Invalid Service Meta: Couldn't load metadata pair ('user.name', 'spring_boot'): Key contains invalid characters')
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:278) ~[consul-api-1.4.5.jar:na]
	at com.ecwid.consul.v1.ConsulClient.agentServiceRegister(ConsulClient.java:310) ~[consul-api-1.4.5.jar:na]
	at org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistry.register(ConsulServiceRegistry.java:68) ~[spring-cloud-consul-discovery-2.2.3.RELEASE.jar:2.2.3.RELEASE]
Caused by: com.ecwid.consul.v1.OperationException: OperationException(statusCode=400, statusMessage='Bad Request', statusContent='Invalid Service Meta: Couldn't load metadata pair ('user.name', 'spring_boot'): Key contains invalid characters')

	at org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistry.register(ConsulServiceRegistry.java:43) ~[spring-cloud-consul-discovery-2.2.3.RELEASE.jar:2.2.3.RELEASE]
...
```
As the exception mentioned, the metadata can not contain `user.name`. Would you like to change the name of key(user.name) or help me to find another better approach than providing my own HttpHeadersProvider? Thank you.

**Comment by joshiste** [comment]
Either we could make the keys configurable or search additionally for keys (e.g. "user_name") satisfying the consul constraints (`^[a-zA-Z0-9_-]+$`). Would you like to work on a PR for it?

**Comment by Macrame** [comment]
I commented an issue to `hashicorp/consul` project and hope consul can support "user.name" for `Service.Meta`. I'll update this issue after his response.

**Comment by laffuste** [comment]
For the record, the issue opened in consul by @Macrame: https://github.com/hashicorp/consul/issues/8127

**Comment by laffuste** [comment]
@joshiste I pushed a PR, feel free to ask for modification.
