### ISSUE TITLE
springboot2.3.1.RELEASE spring-boot-admin2.2.3 No file descriptors available

### ISSUE THREAD

**Issue by star4j** [codecentric/spring-boot-admin#1459]
springboot2.3.1.RELEASE 
springboot admin2.2.3

The browser visits the log page and an exception occurs after some time
`ls -l /proc/<PID>/fd | wc -l`The Numbers keep going up

> io.netty.channel.ChannelException: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: No file descriptors available
	at io.netty.channel.unix.Socket.newSocketStream0(Socket.java:421) ~[netty-transport-native-unix-common-4.1.50.Final.jar!/:4.1.50.Final]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET health [DefaultWebClient]
Stack trace:
		at io.netty.channel.unix.Socket.newSocketStream0(Socket.java:421) ~[netty-transport-native-unix-common-4.1.50.Final.jar!/:4.1.50.Final]
		at io.netty.channel.epoll.LinuxSocket.newSocketStream(LinuxSocket.java:319) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar!/:4.1.50.Final]
		at io.netty.channel.epoll.LinuxSocket.newSocketStream(LinuxSocket.java:323) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar!/:4.1.50.Final]
		at io.netty.channel.epoll.EpollSocketChannel.<init>(EpollSocketChannel.java:45) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar!/:4.1.50.Final]
		at reactor.netty.resources.DefaultLoopEpoll.getChannel(DefaultLoopEpoll.java:45) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.resources.LoopResources.onChannel(LoopResources.java:187) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.resources.LoopResources.onChannel(LoopResources.java:169) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpResources.onChannel(TcpResources.java:215) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClientRunOn.configure(TcpClientRunOn.java:54) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClientRunOn.configure(TcpClientRunOn.java:43) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClientBootstrap.configure(TcpClientBootstrap.java:39) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.tcp.TcpClient.connect(TcpClient.java:196) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.http.client.HttpClientFinalizer.connect(HttpClientFinalizer.java:77) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:94) ~[reactor-netty-0.9.8.RELEASE.jar!/:0.9.8.RELEASE]
		at org.springframework.http.client.reactive.ReactorClientHttpConnector.connect(ReactorClientHttpConnector.java:111) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:104) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at de.codecentric.boot.admin.server.web.client.InstanceExchangeFilterFunctions.lambda$timeout$10(InstanceExchangeFilterFunctions.java:176) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$null$4(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_212]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$toExchangeFilterFunction$5(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at de.codecentric.boot.admin.server.web.client.InstanceExchangeFilterFunctions.lambda$retry$9(InstanceExchangeFilterFunctions.java:167) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$null$4(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_212]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$toExchangeFilterFunction$5(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at de.codecentric.boot.admin.server.web.client.InstanceExchangeFilterFunctions.lambda$logfileAcceptWorkaround$12(InstanceExchangeFilterFunctions.java:190) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$null$4(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_212]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$toExchangeFilterFunction$5(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at de.codecentric.boot.admin.server.web.client.InstanceExchangeFilterFunctions.lambda$convertLegacyEndpoints$4(InstanceExchangeFilterFunctions.java:113) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$null$4(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_212]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$toExchangeFilterFunction$5(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at de.codecentric.boot.admin.server.web.client.InstanceExchangeFilterFunctions.lambda$setDefaultAcceptHeader$8(InstanceExchangeFilterFunctions.java:156) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$null$4(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_212]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$toExchangeFilterFunction$5(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at de.codecentric.boot.admin.server.web.client.InstanceExchangeFilterFunctions.lambda$rewriteEndpointUrl$2(InstanceExchangeFilterFunctions.java:100) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$null$4(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_212]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$toExchangeFilterFunction$5(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at de.codecentric.boot.admin.server.web.client.InstanceExchangeFilterFunctions.lambda$addHeaders$1(InstanceExchangeFilterFunctions.java:68) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$null$4(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_212]
		at de.codecentric.boot.admin.server.web.client.InstanceWebClient.lambda$toExchangeFilterFunction$5(InstanceWebClient.java:66) ~[spring-boot-admin-server-2.2.3.jar!/:2.2.3]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at org.springframework.boot.actuate.metrics.web.reactive.client.MetricsWebClientFilterFunction.filter(MetricsWebClientFilterFunction.java:76) ~[spring-boot-actuator-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
		at org.springframework.web.reactive.function.client.ExchangeFilterFunction.lambda$null$0(ExchangeFilterFunction.java:57) ~[spring-webflux-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) [reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2152) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2026) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) [reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103) [reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4204) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.tryOnNext(FluxFilterFuseable.java:142) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.slowPath(FluxIterable.java:543) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:501) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:184) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:81) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:157) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4219) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:441) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:243) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:144) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:123) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.3.6.RELEASE.jar!/:3.3.6.RELEASE]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_212]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_212]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
		at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]

**Comment by joshiste** [comment]
it may be due to #1455 .
Could you try to add the `spring-boot-starter-web` so tomcat is chosen as underlying runtime and see if the error still occurs?

**Comment by star4j** [comment]
This is my pom
spring-boot-starter-web always in
![image](https://user-images.githubusercontent.com/25194485/84886126-93542580-b0c6-11ea-825f-92e9a5138875.png)

**Comment by joshiste** [comment]
did you observe this behaviour with Spring Boot 2.2.x?

**Comment by legart** [comment]
It sounds like this issue?

https://github.com/spring-projects/spring-boot/issues/21923

**Comment by joshiste** [comment]
> It sounds like this issue?
> 
> [spring-projects/spring-boot#21923](https://github.com/spring-projects/spring-boot/issues/21923)

yep it does

**Comment by star4j** [comment]
> did you observe this behaviour with Spring Boot 2.2.x?

Spring Boot 2.2.6 I haven't found anything wrong yet

**Comment by lcsvcn** [comment]
Hello, I am having this issue.

There is a workaround or solution for this bug?

**Comment by jeehunseo** [comment]
20201016 01:09:55.372 ERROR [payment-service,3b9b41a15864af68,e0eccbddc316c0b0,true] 1 [tp-epoll-3]: [703e1221-16621]  500 Server Error for HTTP POST "/v2/pay/saveOrderInfo" @a.w.r.e.AbstractErrorWebExceptionHandler
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:46)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to POST http://account-service/v1/account/checkUserAuth [DefaultWebClient]
        |_ checkpoint ⇢ Handler com.okimoki.micro.paymentservice.controller.PaymentController#saveOrderInfo(SaveOrderInfoReq) [DispatcherHandler]
        |_ checkpoint ⇢ org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP POST "/v2/pay/saveOrderInfo" [ExceptionHandlingWebHandler]
Stack trace:
                at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:46)
                at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)
                at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155)
                at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
                at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator.lambda$connectChannel$0(PooledConnectionProvider.java:243)
                at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
                at reactor.core.publisher.Mono.subscribeWith(Mono.java:4324)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4184)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4120)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4092)
                at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:260)
                at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drain(SimpleDequePool.java:204)
                at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:199)
                at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:378)
                at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onSubscribe(PooledConnectionProvider.java:532)
                at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:509)
                at reactor.netty.resources.PooledConnectionProvider.disposableAcquire(PooledConnectionProvider.java:218)
                at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$3(PooledConnectionProvider.java:182)
                at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:327)
                at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
                at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
                at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:330)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace.subscribe(TraceWebClientBeanPostProcessor.java:193)

**Comment by joshiste** [comment]
shoud be fixed with newer version of reactor-netty

**Comment by star4j** [comment]
Reactor Netty 0.9.9.RELEASE has solved this issue
Springboot 2.3.2 Depends on Reactor Netty 0.9.10.RELEASE
Springboot 2.3.2 above has resolved this issue
