### ISSUE TITLE
Memory usage can not be displayed. TypeError: Expected a finite number, got string

### ISSUE THREAD

**Issue by IcyLemon** [codecentric/spring-boot-admin#1498]
Hi,

My environment: Java 8 + Spring-Boot-Admin 2.3.0 + Spring Boot 2.3.1.RELEASE 

Everything is fine, but the memory usage can not be displayed on the Insights -> Details. 

In the web console of the browsers(Firefox and Edge), I found many error messages, as follows:

TypeError: Expected a finite number, got string: 501776088
    at o.t.exports (index.js:46)
    at o.St (details-memory.vue?b34d:1)
    at o.t._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554)
    at Xn (vue.runtime.esm.js:4310)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ce (vue.runtime.esm.js:1906)
    ......

Thanks.

**Comment by IcyLemon** [comment]
More details of error messages:

Error in event handler: SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at jQuery.fn.init.get (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/jquery.js:94:58)
    at Updater.check (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:131:38)
    at init (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:264:66)
    at Object.onInitializedGM (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:28:28)
    at Object.callbackResponse (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:13:29)
    at chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:139:29
vue.runtime.esm.js:1888 TypeError: t.processCpuLoad.toFixed is not a function
    at o.Jt (details-process.vue?c33d:1)
    at o.t._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554)
    at Xn (vue.runtime.esm.js:4310)
    ......
vue.runtime.esm.js:1888 TypeError: Expected a finite number, got string: 493001064
    at o.t.exports (index.js:46)
    at o.St (details-memory.vue?b34d:1)
    at o.t._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554)
    ......

**Comment by joshiste** [comment]
can you show me the reponse for the request to the `/instances/{instanceId}/actuator/health` endpoint?

**Comment by IcyLemon** [comment]
The response is below:

Error in event handler: SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at jQuery.fn.init.get (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/jquery.js:94:58)
    at Updater.check (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:131:38)
    at init (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:264:66)
    at Object.onInitializedGM (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:28:28)
    at Object.callbackResponse (chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:13:29)
    at chrome-extension://lfkofmgofencgoaehgcapmejhmedepib/bundle/contents.js:139:29

**Comment by IcyLemon** [comment]
The response using Postman is josn, looks like normal:

[{"name":"demo","buildVersion":"1.0.0-SNAPSHOT","status":"UP","statusTimestamp":"2020-08-20T06:08:54.041Z","instances":[{"id":"41dde6d7fdc0","version":3,"registration":{"name":"demo","managementUrl":"http://xxx:8080/demo/tiger","healthUrl":"http://xxx:8080/demo/tiger/health","serviceUrl":"http://xxx:8080/demo","source":"http-api","metadata":{"tags.profiles":"dev,settings-dev","startup":"2020-08-20T14:08:41.037+08:00"}},"registered":true,"statusInfo":{"status":"UP","details":{"db":{"description":"","status":"UP","details":{"database":"Oracle","validationQuery":"isValid()"}},"diskSpace":{"description":"","status":"UP","details":{"total":"322121494528","free":"294797922304","threshold":"10485760","exists":true}},"ping":{"description":"","status":"UP"},"redis":{"description":"","status":"UP","details":{"version":"5.0.8"}}}},"statusTimestamp":"2020-08-20T06:08:54.041Z","info":{"build":{"version":"1.0.0-SNAPSHOT","profiles":"dev,settings-dev","artifact":"demo","name":"demo","timestamp":"2020-08-20 14:08:02 GMT+08:00","group":"com.tiger","packaging":"war","time":1597903677.649000000}},"endpoints":[{"id":"caches","url":"http://xxx:8080/demo/tiger/caches"},{"id":"loggers","url":"http://xxx:8080/demo/tiger/loggers"},{"id":"health","url":"http://xxx:8080/demo/tiger/health"},{"id":"env","url":"http://xxx:8080/demo/tiger/env"},{"id":"heapdump","url":"http://xxx:8080/demo/tiger/heapdump"},{"id":"mappings","url":"http://xxx:8080/demo/tiger/mappings"},{"id":"scheduledtasks","url":"http://xxx:8080/demo/tiger/scheduledtasks"},{"id":"datasource","url":"http://xxx:8080/demo/tiger/datasource"},{"id":"configprops","url":"http://xxx:8080/demo/tiger/configprops"},{"id":"beans","url":"http://xxx:8080/demo/tiger/beans"},{"id":"threaddump","url":"http://xxx:8080/demo/tiger/threaddump"},{"id":"metrics","url":"http://xxx:8080/demo/tiger/metrics"},{"id":"conditions","url":"http://xxx:8080/demo/tiger/conditions"},{"id":"jolokia","url":"http://xxx:8080/demo/tiger/jolokia"},{"id":"info","url":"http://xxx:8080/demo/tiger/info"}],"buildVersion":"1.0.0-SNAPSHOT","tags":{"profiles":"dev,settings-dev"}}]}]

**Comment by joshiste** [comment]
doesn't looks like a actuator response, more like a error from the browser console. Did you have a look at the request in the dev-tools network tab?

**Comment by joshiste** [comment]
this looks like the reponse from the wrong endpoint.
What is the response from `/instances/41dde6d7fdc0/actuator/health` ?

**Comment by IcyLemon** [comment]
What I just sent is the response of /instances/41dde6d7fdc0/actuator/health. 
Whats is correct response? did I configure something wrong?

**Comment by joshiste** [comment]
the response should more looks like this one: 

```
{"status":"UP","details":{"diskSpace":{"status":"UP","details":{"total":21462233088,"free":19110391808,"threshold":10485760}},"ping":{"status":"UP"}}}
```

Just have a look at the browser's network tab.... the request/response should be easy to find

**Comment by IcyLemon** [comment]
OK, I got it, thank you for your quick and kind response
