### ISSUE TITLE
Spring Boot Admin not work with spring-boot-2.3.3.RELEASE and spring cloud Hoxton.SR8

### ISSUE THREAD

**Issue by zhangbin1010** [codecentric/spring-boot-admin#1513]
Environment: 
Spring Boot 2.3.3.RELEASE
Spring Cloud Hoxton.SR8
Spring Cloud Alibaba 2.2.2.RELEASE
Nacos 1.3.2

Spring Boot Admin 2.3.0

services cannot be discovered automatically.
here are the only error logs for sba startup:
`
2020-09-15 13:45:35.470  INFO 6120 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9099 (http) with context path ''
2020-09-15 13:45:35.793  INFO 6120 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, dev admin-server 127.0.0.1:9099 register finished
2020-09-15 13:45:40.008  INFO 6120 --- [ctor-http-nio-1] d.c.b.a.server.services.StatusUpdater    : Couldn't retrieve status for Instance(id=8c309d250e74, version=0, registration=Registration(name=admin-server, managementUrl=http://127.0.0.1:9098/actuator, healthUrl=http://127.0.0.1:9098/actuator/health, serviceUrl=http://127.0.0.1:9099, source=discovery), registered=true, statusInfo=StatusInfo(status=UNKNOWN, details={}), statusTimestamp=2020-09-15T05:45:35.880865800Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://127.0.0.1:9098/actuator/health)}), buildVersion=null, tags=Tags(values={}))

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:9098
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET health [DefaultWebClient]
Stack trace:
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-09-15 13:45:43.276  INFO 6120 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9098 (http)
2020-09-15 13:45:43.277  INFO 6120 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-09-15 13:45:43.278  INFO 6120 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.37]
2020-09-15 13:45:43.307  INFO 6120 --- [           main] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring embedded WebApplicationContext
2020-09-15 13:45:43.307  INFO 6120 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 198 ms
2020-09-15 13:45:43.322  INFO 6120 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 20 endpoint(s) beneath base path '/actuator'
2020-09-15 13:45:43.355  INFO 6120 --- [           main] c.a.c.s.SentinelWebAutoConfiguration     : [Sentinel Starter] register SentinelWebInterceptor with urlPatterns: [/**].
2020-09-15 13:45:43.395  INFO 6120 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9098 (http) with context path ''
2020-09-15 13:45:47.187  INFO 6120 --- [           main] p.a.a.a.AdminServerApplicationKt         : Started AdminServerApplicationKt in 30.739 seconds (JVM running for 32.654)
2020-09-15 13:45:47.644  INFO 6120 --- [)-10.100.106.69] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-09-15 13:45:47.645  INFO 6120 --- [)-10.100.106.69] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-09-15 13:45:47.660  INFO 6120 --- [)-10.100.106.69] o.s.web.servlet.DispatcherServlet        : Completed initialization in 15 ms
2020-09-15 13:45:51.282  INFO 6120 --- [nio-9098-exec-2] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-09-15 13:45:51.283  INFO 6120 --- [nio-9098-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-09-15 13:45:51.286  INFO 6120 --- [nio-9098-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
`

**Comment by joshiste** [comment]
the error says `Connection refused` I guess the address is not correct or there is no service listening on the port.

**Comment by QwertGold** [comment]
I had a similar issue (Spring 5.2.7, Boot 2.3.1, Hoxton.SR8), and after som debugging I discovered the following class `SimpleStorageProtocolResolver` This gets registered as an orderedPostProcessor which causes it to be instantiated 'early' (PostProcessorRegistrationDelegate:L172). This bean has a constructor dependency on AmazonS3, and this may cause other beans/configuration to be instantiated early. In our case it mean that for these beans all `@Value` injected configuration was `null`, because the configurations has not yet been processed yet.

**Comment by ffroliva** [comment]
I am also facing this issue. Any workaround? Updates?

My stack:

Spring Boot Admin 2.3.1

Spring-boot 2.3.10.RELEASE
Hoxton.SR10
