### ISSUE TITLE
Problems in springboot admin server project!

### ISSUE THREAD

**Issue by yangsuai** [codecentric/spring-boot-admin#1566]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET health [DefaultWebClient]
Stack trace:
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_131]
		at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_131]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_131]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_131]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
		at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

//=================================================================================
An error was reported in the springboot admin server project. A certain display time-out, the specific location is not located!
//=================================================================================

**Comment by joshiste** [comment]
looks like the health endpoint of the monitored application didn't response in time.

>java.util.concurrent.TimeoutException
>|_ checkpoint ⇢ Request to GET health [DefaultWebClient]

**Comment by seaskysmile** [comment]
@yangsuai did you fix it?

**Comment by javaHelper** [comment]
I am getting the same error. Is there any fix for this?

**Comment by asker124143222** [comment]
Try adjusting the following  parameters in your application.yml:

      monitor:
        default-timeout: 60000
        status-interval: 15000
        status-lifetime: 15000
