### ISSUE TITLE
Spring Security and Zuul

### ISSUE THREAD

**Issue by dmwb** [codecentric/spring-boot-admin#161]
#Spring Boot Admin 1.3.2
Solaris 11
jdk1.8.0_74

application.properties :
```
security.basic.enabled=true
security.basic.path=/**
security.user.name=foo
security.user.password=bar
```
Spring Boot Admin won't start. 

Logs:
```
2016-02-24 13:51:09.100 ERROR 4690 --- [main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration$ApplicationWebSecurityConfigurerAdapter': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.setAuthenticationConfiguration(org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.setGlobalAuthenticationConfigurers(java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootAuthenticationConfigurerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at 
....
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	... 50 common frames omitted
Caused by: java.lang.StackOverflowError: null
	at java.util.zip.Inflater.<init>(Inflater.java:102) ~[na:1.8.0_74]
	at org.springframework.boot.loader.jar.ZipInflaterInputStream.<init>(ZipInflaterInputStream.java:38) 
....
2016-02-24 13:51:09.137  WARN 4690 --- [main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.cloud.netflix.zuul.filters.ZuulProperties org.springframework.cloud.netflix.zuul.ZuulConfiguration.zuulProperties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zuul.CONFIGURATION_PROPERTIES': Initialization of bean failed; nested exception is java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@577cafda has not been refreshed yet)
2016-02-24 13:56:59.147  INFO 5069 --- [main] o.s.boot.SpringApplication               : ?
```

**Comment by dmwb** [comment]
#Spring Boot Admin Server Properties
spring.boot.admin.monitor.period=30000
spring.boot.admin.monitor.status-lifetime=30000
spring.boot.admin.hazelcast.enabled=false
spring.boot.admin.discovery.enabled=false
spring.boot.admin.notify.mail.enabled=true

**Comment by dmwb** [comment]
To be more clear. It's starts but inconsistently.Some times after fifth try...

**Comment by joshiste** [comment]
Doesn't look like an spring boot admin problem to me....

what does the file command tell about your jar file? Do you use war-packaging or the executable jar created by the spring-boot-maven-plugin?
And does the error occur if you use `mvn spring-boot:run`

**Comment by dmwb** [comment]
Thanks for fast response! I'm using executable jar. No issues on windows. Very strange behavior to me. First time it starts fine. If I bounce it after some time I get that exceptions and after fifth or six tries it starts eventually. No customizations, just a regular boot app:

@SpringBootApplication
@EnableAdminServer
public class SpringAppMonitor {
	
	public static void main(String[] args) {
		SpringApplication.run(SpringAppMonitor.class, args);
	}
}

**Comment by dmwb** [comment]
I have found that https://github.com/spring-cloud/spring-cloud-netflix/issues/162 
But I'm using basic not oauth2...

**Comment by joshiste** [comment]
Ok so did you experience problems with other boot-apps using spring-security on this system (without boot admin)?

**Comment by joshiste** [comment]
> I have found that spring-cloud/spring-cloud-netflix#162 

and why do you think this relates to your StackOverflowError???

**Comment by dmwb** [comment]
Yes. we have another boot app which we want to monitor. It has same basic security. No issues. They both ran on the same system.

**Comment by joshiste** [comment]
Did you check your value for `-Xss` jvm-parameter? Have you tried to increase?

**Comment by dmwb** [comment]
I guess 256K is enough for such a tiny app :)

JAVA_OPTS="$JAVA_OPTS 
-server
-Xms4g
-Xmx4g
-Xss256k
-XX:MaxMetaspaceSize=256m
-XX:+DisableExplicitGC
-XX:+UseG1GC
-XX:+UseStringDeduplication
-XX:+UseNUMA
-XX:+UseCompressedOops
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=$HEAPDUMP_FILE
-Dspring.profiles.active=$PROFILE
-Dserver.address=$SERVER_IP
-Dserver.port=$PORT"

**Comment by dmwb** [comment]
Full stacktrace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration$ApplicationWebSecurityConfigurerAdapter': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.setAuthenticationConfiguration(org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.setGlobalAuthenticationConfigurers(java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootAuthenticationConfigurerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at com.pacificorp.cs.tools.SpringAppMonitor.main(SpringAppMonitor.java:25) [spring-app-monitor.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [spring-app-monitor.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.setAuthenticationConfiguration(org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.setGlobalAuthenticationConfigurers(java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootAuthenticationConfigurerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:661) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	... 23 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.setGlobalAuthenticationConfigurers(java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootAuthenticationConfigurerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:618) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	... 25 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.setGlobalAuthenticationConfigurers(java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootAuthenticationConfigurerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:661) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	... 36 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootAuthenticationConfigurerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1068) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:618) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	... 38 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$SpringBootAuthenticationConfigurerAdapter]: Factory method 'springBootAuthenticationConfigurerAdapter' threw exception; nested exception is java.lang.StackOverflowError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	... 50 common frames omitted
Caused by: java.lang.StackOverflowError: null
	at java.util.zip.Inflater.<init>(Inflater.java:102) ~[na:1.8.0_74]
	at org.springframework.boot.loader.jar.ZipInflaterInputStream.<init>(ZipInflaterInputStream.java:38) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.jar.JarEntryData.getInputStream(JarEntryData.java:94) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:179) ~[spring-app-monitor.jar!/:na]
	at sun.misc.URLClassPath$Loader.getResource(URLClassPath.java:702) ~[na:1.8.0_74]
	at sun.misc.URLClassPath.getResource(URLClassPath.java:212) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_74]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_74]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[spring-app-monitor.jar!/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_74]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_74]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_74]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_74]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_74]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[spring-app-monitor.jar!/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_74]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_74]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_74]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_74]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_74]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[spring-app-monitor.jar!/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_74]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_74]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_74]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_74]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_74]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[spring-app-monitor.jar!/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_74]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_74]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_74]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_74]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_74]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[spring-app-monitor.jar!/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_74]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_74]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_74]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_74]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_74]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_74]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_74]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_74]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170) ~[spring-app-monitor.jar!/:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[spring-app-monitor.jar!/:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
	at org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration.springBootAuthenticationConfigurerAdapter(AuthenticationManagerConfiguration.java:86) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	... 51 common frames omitted

2016-02-24 13:51:09.137  WARN 4690 --- [main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.cloud.netflix.zuul.filters.ZuulProperties org.springframework.cloud.netflix.zuul.ZuulConfiguration.zuulProperties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zuul.CONFIGURATION_PROPERTIES': Initialization of bean failed; nested exception is java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@577cafda has not been refreshed yet)
```

**Comment by joshiste** [comment]
> I guess 256K is enough for such a tiny app :)

On my system the default is 1024k so please try to increase.
And if you look at all the dependencies... your app ain't that tiny anymore...

And I really think this isn't related to spring boot admin, so i'm closing this right now.

**Comment by dmwb** [comment]
Thanks. I think that was the issue. I test multiple times and boot admin app come up without that exception. Thanks and appreciate you help! Keep doing good things guys :+1:
