### ISSUE TITLE
Problem when using logfile viewer when rolling over

### ISSUE THREAD

**Issue by djeanprost** [codecentric/spring-boot-admin#1632]
Hello,

I setup my spring boot application to use a size file rolling file appender.
When using logfile viewer, everything is ok as long as rolling event does not occur. After it does, the **range values** sent to /logfile seem to be **outside** the actual log file size. 
I then get an error 500 in SBA, and the same error on the application side.

As I can't even imagine people using a file appender without any rolling policy (whatever the type), I really wonders if I'm the only one to meet this problem ?

Thank you for helping.
Dom

    GET /bootadmin/instances/5027eb28f1a9/actuator/logfile HTTP/1.1
    Host: localhost:8085
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
    Accept: text/plain
    Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    Accept-Encoding: gzip, deflate
    X-Requested-With: XMLHttpRequest
    range: bytes=3220-
    DNT: 1
    Authorization: Basic blabla
   Connection: keep-alive

And on server side :
    
    java.lang.IllegalArgumentException: 'position' exceeds the resource length 839
	at org.springframework.util.Assert.isTrue(Assert.java:121)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
    Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ReadOperationHandler#handle(ServerWebExchange) [DispatcherHandler]
    Stack trace:
		at org.springframework.util.Assert.isTrue(Assert.java:121)
		at org.springframework.http.HttpRange.toResourceRegion(HttpRange.java:68)
		at org.springframework.http.HttpRange.toResourceRegions(HttpRange.java:183)
		at org.springframework.http.codec.ResourceHttpMessageWriter.lambda$write$2(ResourceHttpMessageWriter.java:210)
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:151)
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
		at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:249)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by joshiste** [comment]
Does this happen only if the log viewer is opened while the rollover happens? Or does this occur anytime the page is opened after a rollover?

**Comment by djeanprost** [comment]
Hello @joshiste 

The problem occurs when the rollover happens. If I close the window and then reopen it, lines appear correctly until the next rollover. When the rollover happens, the file size goes down to a value which is less than the range that is requested when the following GET /logfile is fired.

**Comment by shmyer** [comment]
I have seen this issue in our application aswell and I have already thought about providing a PR, but unfortunately I don't have too much spare time. I did however look into the code and in my opinion (correct me if I'm wrong) this can easily be solved by handling the response code 416 in the if/else if/else block in [logtail.js](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/utils/logtail.js)

**Comment by pulasthi-Narada** [comment]
In the Spring Boot 3.x version, I use the `logging.logback.rollingpolicy.max-file-size` property to give a log file size but After I removed this property, this **error was gone**.
