### ISSUE TITLE
Not able to monitor Spring Boot 1.x components after upgrading to 2.4.0

### ISSUE THREAD

**Issue by zeljko-mirovic** [codecentric/spring-boot-admin#1638]
After upgrading to Spring Boot Admin 2.4.0 and Spring Boot 2.4.2, I am getting the following error when Spring Boot Admin is updating the status of a monitored component:

```
2021-02-19 12:11:11.426 DEBUG [     parallel-1] [IntervalCheck.java:93] check status for all instances
2021-02-19 12:11:11.426 DEBUG [     parallel-1] [StatusUpdater.java:74] Update status for Instance(id=46e6e344c534, version=1, registration=Registration(name=test, managementUrl=http://localhost:10100/manage, healthUrl=http://localhost:10100/manage/health, serviceUrl=http://localhost:10100/, source=discovery), registered=true, statusInfo=StatusInfo(status=OFFLINE, details={exception=java.lang.IllegalStateException, message=Only one connection receive subscriber allowed.}), statusTimestamp=2021-02-19T11:10:14.476Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://localhost:10100/manage/health)}), buildVersion=null, tags=Tags(values={}))
2021-02-19 12:11:11.429 TRACE [     parallel-1] [Loggers.java:229] | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
2021-02-19 12:11:11.429 TRACE [     parallel-1] [Loggers.java:229] | request(unbounded)
2021-02-19 12:11:11.433 DEBUG [ctor-http-nio-2] [Loggers.java:249] [id: 0x48784ef2, L:/127.0.0.1:10000 - R:localhost/127.0.0.1:10100] FluxReceive{pending=0, cancelled=false, inboundDone=false, inboundError=null}: subscribing inbound receiver
2021-02-19 12:11:11.434 TRACE [ctor-http-nio-2] [Loggers.java:229] | onError(java.lang.IllegalStateException: Only one connection receive subscriber allowed.)
2021-02-19 12:11:11.434 TRACE [ctor-http-nio-2] [Loggers.java:234] 

java.lang.IllegalStateException: Only one connection receive subscriber allowed.
	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:180)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint - Body from GET http://localhost:10100/manage/health [DefaultClientResponse]
	|_ checkpoint - Body from GET http://localhost:10100/manage/health [DefaultClientResponse]
Stack trace:
		at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:180)
		at reactor.netty.channel.FluxReceive.subscribe(FluxReceive.java:144)
		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
		at reactor.netty.ByteBufFlux.subscribe(ByteBufFlux.java:340)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173)
		at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$TraceWebClientSubscriber.onNext(TraceWebClientBeanPostProcessor.java:220)
		at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$TraceWebClientSubscriber.onNext(TraceWebClientBeanPostProcessor.java:183)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
		at reactor.core.publisher.FluxRetry$RetrySubscriber.onNext(FluxRetry.java:86)
		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:179)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:245)
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
		at reactor.core.publisher.Flux.subscribe(Flux.java:8156)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
		at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:385)
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:638)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:195)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:466)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:628)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)

2021-02-19 12:11:11.435 DEBUG [ctor-http-nio-2] [StatusUpdater.java:124] Couldn't retrieve status for Instance(id=46e6e344c534, version=1, registration=Registration(name=test, managementUrl=http://localhost:10100/manage, healthUrl=http://localhost:10100/manage/health, serviceUrl=http://localhost:10100/, source=discovery), registered=true, statusInfo=StatusInfo(status=OFFLINE, details={exception=java.lang.IllegalStateException, message=Only one connection receive subscriber allowed.}), statusTimestamp=2021-02-19T11:10:14.476Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://localhost:10100/manage/health)}), buildVersion=null, tags=Tags(values={}))

java.lang.IllegalStateException: Only one connection receive subscriber allowed.
	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:180)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint - Body from GET http://localhost:10100/manage/health [DefaultClientResponse]
	|_ checkpoint - Body from GET http://localhost:10100/manage/health [DefaultClientResponse]
Stack trace:
		at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:180)
		at reactor.netty.channel.FluxReceive.subscribe(FluxReceive.java:144)
		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
		at reactor.netty.ByteBufFlux.subscribe(ByteBufFlux.java:340)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173)
		at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$TraceWebClientSubscriber.onNext(TraceWebClientBeanPostProcessor.java:220)
		at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$TraceWebClientSubscriber.onNext(TraceWebClientBeanPostProcessor.java:183)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
		at reactor.core.publisher.FluxRetry$RetrySubscriber.onNext(FluxRetry.java:86)
		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:179)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:245)
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
		at reactor.core.publisher.Flux.subscribe(Flux.java:8156)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
		at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:385)
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:638)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:195)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:466)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:628)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)
```
The monitored component is responding correctly on health and info actuator endpoints.

Everything was working with Spring Boot Admin 2.3.1 and Spring Boot 2.3.6.RELEASE.

**Comment by erikpetzold** [comment]
we had the same message in  #1631

**Comment by zeljko-mirovic** [comment]
> we had the same message in #1631

Thank you for the hint.

Spring Boot Admin is using `Accept: application/vnd.spring-boot.actuator.v2+json, application/vnd.spring-boot.actuator.v1+json, application/json` in the request, but if the returned response has `Content-Type: application/vnd.spring-boot.actuator.v1+json` or `Content-Type: application/json`, the error mentioned above will arise.
There are no problems with `Content-Type: application/vnd.spring-boot.actuator.v2+json` or `Content-Type: application/vnd.spring-boot.actuator.v3+json`.

**Comment by ccoltx** [comment]
Thanks for providing the additional info. Can you provide a sample app which reproduces this issue.

FYI - spring-boot 2.2 deprecated v1 and introduced v3. spring-boot 2.4.0 removed support for v1. SBA does not yet support v3

https://github.com/spring-projects/spring-boot/commit/deb9d67cef7fe55bd08ab292659b611419031403#diff-c6064413bdac002275dc063ba502bccbf6a848eb3b075b86764f397883793c9f

https://github.com/spring-projects/spring-boot/commit/8f102aee6862b92a8e4c5db7a30527db05a2b183#diff-c6064413bdac002275dc063ba502bccbf6a848eb3b075b86764f397883793c9f

**Comment by zeljko-mirovic** [comment]
[applications.zip](https://github.com/codecentric/spring-boot-admin/files/6021672/applications.zip) contatins six applications.

Four applications are simple Spring Boot applications without security, exposing `health` and `info` actuator endpoints. The `health` endpoint shows details always, and the `info` endpoint shows build info.
Spring versions used:
- Spring Boot v1.4.7 - using `application/json` for a response.
- Spring Boot v1.5.22 - using `application/vnd.spring-boot.actuator.v1+json` for a response.
- Spring Boot v2.1.18 - using `application/vnd.spring-boot.actuator.v2+json` for a response.
- Spring Boot v2.4.3 - using `application/vnd.spring-boot.actuator.v2+json` or `application/vnd.spring-boot.actuator.v3+json` for a response.

Besides them, there are two versions of Spring Boot Admin:
- Spring Boot Admin v2.3.1 using Spring Boot 2.3.9.RELEASE.
- Spring Boot Admin v2.4.0 using Spring Boot 2.4.3.

Both of them are configured to monitor all four Spring Boot applications, using a static configuration with `SimpleDiscoveryClient`.

Additionally, I wrote the test to check is Spring Boot Admin registers mocked versions of applications (`health` and `info` responses are mocked). The test has five scenarios:
- Spring Boot v1.4.x responses using `application/json`.
- Spring Boot v1.5.x responses using `application/vnd.spring-boot.actuator.v1+json`.
- Spring Boot v2.1.x  responses using `application/vnd.spring-boot.actuator.v2+json`.
- Spring Boot v2.4.x responses using `application/vnd.spring-boot.actuator.v2+json`.
- Spring Boot v2.4.x responses using `application/vnd.spring-boot.actuator.v3+json`.

The last scenario is not a real-life scenario because Spring Boot admin uses the `Accept` header without the `v3` media type. It is added to cover all possible responses.
Test scenarios that are failing are disabled.

**Comment by joshiste** [comment]
may be the IllegalStateException is due to https://github.com/reactor/reactor-netty/issues/1513 ?

**Comment by zeljko-mirovic** [comment]
> may be the IllegalStateException is due to [reactor/reactor-netty#1513](https://github.com/reactor/reactor-netty/issues/1513) ?

That one is pointing to [spring-cloud/spring-cloud-sleuth/issues#1854](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1854), but there is no Spring Cloud Sleuth in the provided example.

**Comment by zeljko-mirovic** [comment]
The issue is also reproducible with Spring Boot v2.4.4.
