### ISSUE TITLE
Update to Spring Cloud Brixton

### ISSUE THREAD

**Issue by Koizumi85** [codecentric/spring-boot-admin#167]
Hello,

found, that the next version of spring-cloud-netflix (Brixton Release Train) will break spring-boot-admin.
Constructor of SimpleHostRoutingFilter changed from "public SimpleHostRoutingFilter(ProxyRequestHelper helper)" to "public SimpleHostRoutingFilter(ProxyRequestHelper helper, ZuulProperties properties)"

Stacktrace:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter]: Factory method 'simpleHostRoutingFilter' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.<init>(Lorg/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper;)V
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 47 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.<init>(Lorg/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper;)V
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration.simpleHostRoutingFilter(RevereseZuulProxyConfiguration.java:71) ~[spring-boot-admin-server-1.3.3-SNAPSHOT.jar:1.3.3-SNAPSHOT]
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration$$EnhancerBySpringCGLIB$$231adb08.CGLIB$simpleHostRoutingFilter$3(<generated>) ~[spring-boot-admin-server-1.3.3-SNAPSHOT.jar:1.3.3-SNAPSHOT]
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration$$EnhancerBySpringCGLIB$$231adb08$$FastClassBySpringCGLIB$$e4bebeba.invoke(<generated>) ~[spring-boot-admin-server-1.3.3-SNAPSHOT.jar:1.3.3-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration$$EnhancerBySpringCGLIB$$231adb08.simpleHostRoutingFilter(<generated>) ~[spring-boot-admin-server-1.3.3-SNAPSHOT.jar:1.3.3-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72-internal]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
```

**Comment by joshiste** [comment]
I know. There are several changes needed for the Brixton update. I have a [branch in my private repo for the Brixton update](https://github.com/joshiste/spring-boot-admin/tree/pull-159).
After the Brixton Release at the end of this quarter, I'll update the dependencies in boot admin.

**Comment by royremi** [comment]
Hi Johannes, do you plan to release for brixton RC1? Waiting on that. Will be really useful!

Thanks

**Comment by joshiste** [comment]
No waiting for the release.

**Comment by joshlong** [comment]
would u be willing to publish a milestone or snapshot version so that we could link to it in updated code, in the meantime?

**Comment by joshiste** [comment]
I've committed the changes to master. When the travis build has  passed, snapshots are available in the sonatype snapshot repo:

```xml
<repositories>
        <repository>
             <id>sonatype-nexus-snapshots</id>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
</repositories>
```

**Comment by joshiste** [comment]
@joshlong the snapshot build is now available. I appreciate some feedback :smile:

**Comment by tjuchniewicz** [comment]
Snapshot works fine for me.

When can we expect release of 1.3.3? Brixton.RELEASE is available now.

**Comment by joshiste** [comment]
> Brixton.RELEASE is available now.

not yet pushed to [repo1.maven.org](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/). We have to wait for that. After the release on maven central I'll update the master branch and provide a snapshot build for testing. One week after I'll do the release.

**Comment by joshiste** [comment]
snapshots are built. happy testing! :smile:
