### ISSUE TITLE
Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by Tobisaninfo** [codecentric/spring-boot-admin#1711]
Hi,

I'm using SBA 2.4.1 in combination with spring boot 2.4.5 in a Docker/Tomcat environment. SBA runs in a plain openjdk container and my actual spring boot applications (2) run inside a tomcat docker container.

As I run both of them, I got in an irregular time interval status change mails (link this example below) caused by this exception below. There as I'm the opinion, that the actual applications works fin all the time. The appended exception is from the SBA container.

**Mail Example:**
```
app-api (ff3c712f6338) is OFFLINE

Instance ff3c712f6338 changed status from UP to OFFLINE

Status Details

exception
org.springframework.web.reactive.function.client.WebClientRequestException
message
Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
Registration

Service Url	http://app:8080/api
Health Url	http://app:8080/api/actuator/health
Management Url	http://app:8080/api/actuator
```

My configuration looks like this:

**SBA:** 
```properties
spring.security.user.name=admin
spring.security.user.password=<password>
server.port=8000
```

**Spring Boot Application:**
```properties
spring.boot.admin.client.url=http://admin-server:8000
spring.boot.admin.client.instance.service-base-url=http://app:8080
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin
spring.boot.admin.client.instance.metadata.user.name=client
spring.boot.admin.client.instance.metadata.user.password=<password>
```

Do I have anything misconfigured or is this a bug?

**The actual Exception inside SBA:**
```
2021-04-24 11:23:44.946  WARN 1 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect    : [id:f901f883-15, L:/172.28.0.2:40130 ! R:app/172.28.0.3:8080] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2021-04-24 11:23:44.973  INFO 1 --- [or-http-epoll-2] d.c.b.a.server.services.StatusUpdater    : Couldn't retrieve status for Instance(id=ff3c712f6338, version=7, registration=Registration(name=app-api, managementUrl=http://app:8080/api/actuator, healthUrl=http://app:8080/api/actuator/health, serviceUrl=http://app:8080/api, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={mongo={status=UP, details={version=4.4.5}}, db={status=UP, details={database=MySQL, validationQuery=isValid()}}, diskSpace={status=UP, details={total=420696522752, free=318616391680, threshold=10485760, exists=true}}, ping={status=UP}, redis={status=UP, details={version=5.0.12}}}), statusTimestamp=2021-04-24T09:20:31.726866Z, info=Info(values={git={branch=origin/master, commit={id=725df9c, time=2021-04-24T09:08:38Z}}}), endpoints=Endpoints(endpoints={mappings=Endpoint(id=mappings, url=http://app:8080/api/actuator/mappings), httptrace=Endpoint(id=httptrace, url=http://app:8080/api/actuator/httptrace), caches=Endpoint(id=caches, url=http://app:8080/api/actuator/caches), loggers=Endpoint(id=loggers, url=http://app:8080/api/actuator/loggers), logfile=Endpoint(id=logfile, url=http://app:8080/api/actuator/logfile), configprops=Endpoint(id=configprops, url=http://app:8080/api/actuator/configprops), scheduling=Endpoint(id=scheduling, url=http://app:8080/api/actuator/scheduling), health=Endpoint(id=health, url=http://app:8080/api/actuator/health), env=Endpoint(id=env, url=http://app:8080/api/actuator/env), info=Endpoint(id=info, url=http://app:8080/api/actuator/info)}), buildVersion=null, tags=Tags(values={}))

org.springframework.web.reactive.function.client.WebClientRequestException: Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.6.jar!/:5.3.6]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET health [DefaultWebClient]
Stack trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.6.jar!/:5.3.6]
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:70) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4150) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:221) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:221) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:221) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:224) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:273) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:413) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:250) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:97) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:189) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:189) ~[reactor-core-3.4.5.jar!/:3.4.5]
		at reactor.netty.http.client.HttpClientConnect$HttpObserver.onUncaughtException(HttpClientConnect.java:358) ~[reactor-netty-http-1.0.6.jar!/:1.0.6]
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onUncaughtException(ReactorNetty.java:647) ~[reactor-netty-core-1.0.6.jar!/:1.0.6]
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onUncaughtException(DefaultPooledConnectionProvider.java:214) ~[reactor-netty-core-1.0.6.jar!/:1.0.6]
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onUncaughtException(DefaultPooledConnectionProvider.java:462) ~[reactor-netty-core-1.0.6.jar!/:1.0.6]
		at reactor.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:290) ~[reactor-netty-http-1.0.6.jar!/:1.0.6]
		at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:74) ~[reactor-netty-core-1.0.6.jar!/:1.0.6]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:235) ~[netty-codec-http-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:311) ~[netty-codec-http-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar!/:4.1.51.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
```

**Comment by woshiyingmu** [comment]
I ran into the same problem,My SBA version is 2.2.4 and my client version also is 2.2.4, one of my application intermittently appears online and offline，but my application works well.

**Comment by yanye666** [comment]
I also encountered the same problem. After a few minutes, I received an email with the status of up. The following is the content of the email:
Instance 5fbe0fe99c17changed status from UPto OFFLINE

Status Details
exception
reactor.netty.http.client.PrematureCloseException
message
Connection prematurely closed BEFORE response

**Comment by yanye666** [comment]
@joshiste

**Comment by SteKoe** [comment]
Hi, can you please provide a repo that reproduces this issue? I am not able to find a combination of SBA and Spring Boot applications that lead to the mentioned problem when running either out of my IDE or in a Docker container.

**Comment by patpatpat123** [comment]
Also seeing this very frequently on my end.

SBA 2.4.1 with Spring Boot 2.5.0-RC1

My clients are Spring Webflux projects

**Comment by thanks-git** [comment]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
 Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET health [DefaultWebClient]
 Stack trace:

**Comment by thanks-git** [comment]
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
 Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET health [DefaultWebClient]
 Stack trace:

**Comment by coderDem** [comment]
I have the same error going on after I updated to version 2.5.1:

```Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response```

**Comment by SakuraAxy** [comment]
hi~ Is there any progress on this issue recently ?

**Comment by erikpetzold** [comment]
Like @SteKoe wrote earlier, it would be great if someone could provide a demo project where this happens. Simply share a link to a git repo here, so we can reproduce and further analyse the issue.

**Comment by coderDem** [comment]
Hello @ulischulte I understand that this is an fault of netty, but, what could we do that the error are not called?
I have updated spring boot admin and sprint boot parent to the newest version. This seems not to work.

**Comment by erikpetzold** [comment]
Hi @coderDem if you think this is a netty error, can you please open a bug at [netty](https://github.com/reactor/reactor-netty) project? We don't want to do that in your name, as we cannot provide any more details or examples.
You can also reference this issue here. Thank you

**Comment by bootstrap2025** [comment]
![微信图片_20211122170111](https://user-images.githubusercontent.com/9637974/143030748-f65222ff-c73c-4c22-9edf-8a296c1379cf.png)

It can be seen from the figure that the service will go online and offline frequently, the server will report errors as follows:：
```
org.springframework.web.reactive.function.client.WebClientRequestException: Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.9.jar!/:5.3.9]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET info [DefaultWebClient]
Stack trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.9.jar!/:5.3.9]
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4338) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:414) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:189) ~[reactor-core-3.4.8.jar!/:3.4.8]
		at reactor.netty.http.client.HttpClientConnect$HttpObserver.onUncaughtException(HttpClientConnect.java:384) ~[reactor-netty-http-1.0.9.jar!/:1.0.9]
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onUncaughtException(ReactorNetty.java:647) ~[reactor-netty-core-1.0.9.jar!/:1.0.9]
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onUncaughtException(DefaultPooledConnectionProvider.java:219) ~[reactor-netty-core-1.0.9.jar!/:1.0.9]
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onUncaughtException(DefaultPooledConnectionProvider.java:467) ~[reactor-netty-core-1.0.9.jar!/:1.0.9]
		at reactor.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:289) ~[reactor-netty-http-1.0.9.jar!/:1.0.9]
		at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:73) ~[reactor-netty-core-1.0.9.jar!/:1.0.9]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:235) ~[netty-codec-http-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[netty-codec-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[netty-codec-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:313) ~[netty-codec-http-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831) ~[netty-transport-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.66.Final-linux-x86_64.jar!/:4.1.66.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.66.Final.jar!/:4.1.66.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.66.Final.jar!/:4.1.66.Final]
		at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
Caused by: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

```

**Comment by MrZhengliang** [comment]
Current project:
Spring Boot version: 2.4.2
Reactor netty version: 1.0.3
spring-boot-admin version: 2.4.3
When we check health, the following exception logs often appear in spring boot admin:
`reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response`

**Comment by MrZhengliang** [comment]
Current project:
Spring Boot version: 2.4.2
Reactor netty version: 1.0.3
spring-boot-admin version: 2.4.3
When we check health, the following exception logs often appear in spring boot admin:
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

**Comment by HugoVeillette** [comment]
Reporting same issue with 2.2.2, running in a Kubernetes env.
I wonder if this is a interoperability issue with Netty following an update of the Kubernetes environment.
Btw the issue becomes worst as the app registration count increase.
With around 20 apps, issue occurs but rarely. Once per day, not every app.
With around 50 apps, issue occurs every ~5 minutes, every app registration is affected at least once in a day.
The wallboard looks like holiday tree.

This looks like a http/1.1 connection pooling issue.

**Comment by erikpetzold** [comment]
Hi everyone, 

could you please try if enabling retry solves the problem? See https://codecentric.github.io/spring-boot-admin/current/#_configuration_options

There are the options `spring.boot.admin.monitor.default-retries` and `spring.boot.admin.monitor.retries.*` to configure the number of retries (default is 0, here we need retry for health endpoint). 

So please add
`spring.boot.admin.monitor.default-retries=5`
or
`spring.boot.admin.monitor.retries.health=5`
to your config.

Does not remove the connection issue, but hopefully fixes the status changes.

**Comment by HugoVeillette** [comment]
@erikpetzold good idea. 

Also there these system properties:
`-Dreactor.netty.pool.maxIdleTime=`
`-Dreactor.netty.pool.maxLifeTime=`
which may help mitigate the issue, assuming connection pooling on client side is not getting the `RST` packets.
See
https://projectreactor.io/docs/netty/release/reference/index.html#faq.connection-closed
https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java

**Comment by hzmcoder** [comment]
@erikpetzold 
Hello, how to restrict some services on Nacos from registering with SBA

**Comment by erikpetzold** [comment]
@hzmcoder 

this has nothing to do with this ticket, please don't spam other topics with unrelated questions.

In general, for questions please use the chat on gitter or ask on stackoverflow, see https://github.com/codecentric/spring-boot-admin#getting-help

I personally don't know nacos. There are mechanisms based on metadata that can be provided by your discovery client, see https://codecentric.github.io/spring-boot-admin/current/#_converting_serviceinstances

```
spring.boot.admin.discovery.ignored-instances-metadata

Instances of services will be ignored if they contain at least one metadata item that matches this list. (e.g. "discoverable=false")

spring.boot.admin.discovery.instances-metadata

Instances of services will be included if they contain at least one metadata item that matches this list. (e.g. "discoverable=true")
```

If you want to ignore a fixed set of services you could also use

```
spring.boot.admin.discovery.ignored-services 
This  services will be ignored when using discovery and not registered as  application. Supports simple patterns (e.g. "foo*", "*bar", "foo*bar*").
```

**Comment by SteKoe** [comment]
Closing this issue due to inactivity. If the problem pops up again, feel free to reopen the issue.
