### ISSUE TITLE
After a period of time, e-mails are sent twice in a minute, but they are not offline or up

### ISSUE THREAD

**Issue by lswlsw** [codecentric/spring-boot-admin#1716]
[2021-04-30 08:51:51.234] [nothing.attdns.com] [parallel-5] INFO d.c.b.a.s.services.StatusUpdater@logError:127 - Couldn't retrieve status for Instance(id=d152d04972d7, version=10, registration=Registration(name=spring-boot-application, managementUrl=http://localhost:8080/mdm-server/actuator, healthUrl=http://localhost:8080/mdm-server/actuator/health, serviceUrl=http://localhost:8080/mdm-server, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={mail={status=UP, details={location=smtp.tinno.com:-1}}, db={status=UP, details={dynamicDataSource={status=UNKNOWN, details={routing=true}}, masterDataSource={status=UP, details={database=MySQL, validationQuery=isValid()}}}}, diskSpace={status=UP, details={total=2414735265792, free=2403225538560, threshold=10485760, exists=true}}, ping={status=UP}, redis={status=UP, details={version=3.0.503}}}), statusTimestamp=2021-04-29T12:54:01.502074Z, info=Info(values={}), endpoints=Endpoints(endpoints={caches=Endpoint(id=caches, url=http://localhost:8080/mdm-server/actuator/caches), loggers=Endpoint(id=loggers, url=http://localhost:8080/mdm-server/actuator/loggers), logfile=Endpoint(id=logfile, url=http://localhost:8080/mdm-server/actuator/logfile), health=Endpoint(id=health, url=http://localhost:8080/mdm-server/actuator/health), env=Endpoint(id=env, url=http://localhost:8080/mdm-server/actuator/env), heapdump=Endpoint(id=heapdump, url=http://localhost:8080/mdm-server/actuator/heapdump), scheduledtasks=Endpoint(id=scheduledtasks, url=http://localhost:8080/mdm-server/actuator/scheduledtasks), mappings=Endpoint(id=mappings, url=http://localhost:8080/mdm-server/actuator/mappings), beans=Endpoint(id=beans, url=http://localhost:8080/mdm-server/actuator/beans), configprops=Endpoint(id=configprops, url=http://localhost:8080/mdm-server/actuator/configprops), threaddump=Endpoint(id=threaddump, url=http://localhost:8080/mdm-server/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://localhost:8080/mdm-server/actuator/metrics), conditions=Endpoint(id=conditions, url=http://localhost:8080/mdm-server/actuator/conditions), info=Endpoint(id=info, url=http://localhost:8080/mdm-server/actuator/info)}), buildVersion=null, tags=Tags(values={}))
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET health [DefaultWebClient]
Stack trace:
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
		at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
		at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)
[2021-04-30 08:55:51.234] [nothing.attdns.com] [parallel-7] INFO d.c.b.a.s.services.StatusUpdater@logError:127 - Couldn't retrieve status for Instance(id=d152d04972d7, version=12, registration=Registration(name=spring-boot-application, managementUrl=http://localhost:8080/mdm-server/actuator, healthUrl=http://localhost:8080/mdm-server/actuator/health, serviceUrl=http://localhost:8080/mdm-server, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={mail={status=UP, details={location=smtp.tinno.com:-1}}, db={status=UP, details={dynamicDataSource={status=UNKNOWN, details={routing=true}}, masterDataSource={status=UP, details={database=MySQL, validationQuery=isValid()}}}}, diskSpace={status=UP, details={total=2414735265792, free=2403057782784, threshold=10485760, exists=true}}, ping={status=UP}, redis={status=UP, details={version=3.0.503}}}), statusTimestamp=2021-04-30T00:52:21.465653Z, info=Info(values={}), endpoints=Endpoints(endpoints={caches=Endpoint(id=caches, url=http://localhost:8080/mdm-server/actuator/caches), loggers=Endpoint(id=loggers, url=http://localhost:8080/mdm-server/actuator/loggers), logfile=Endpoint(id=logfile, url=http://localhost:8080/mdm-server/actuator/logfile), health=Endpoint(id=health, url=http://localhost:8080/mdm-server/actuator/health), env=Endpoint(id=env, url=http://localhost:8080/mdm-server/actuator/env), heapdump=Endpoint(id=heapdump, url=http://localhost:8080/mdm-server/actuator/heapdump), scheduledtasks=Endpoint(id=scheduledtasks, url=http://localhost:8080/mdm-server/actuator/scheduledtasks), mappings=Endpoint(id=mappings, url=http://localhost:8080/mdm-server/actuator/mappings), beans=Endpoint(id=beans, url=http://localhost:8080/mdm-server/actuator/beans), configprops=Endpoint(id=configprops, url=http://localhost:8080/mdm-server/actuator/configprops), threaddump=Endpoint(id=threaddump, url=http://localhost:8080/mdm-server/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://localhost:8080/mdm-server/actuator/metrics), conditions=Endpoint(id=conditions, url=http://localhost:8080/mdm-server/actuator/conditions), info=Endpoint(id=info, url=http://localhost:8080/mdm-server/actuator/info)}), buildVersion=null, tags=Tags(values={}))
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET health [DefaultWebClient]
Stack trace:
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288)
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
		at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395)
		at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)

![微信截图_20210430181546](https://user-images.githubusercontent.com/8841511/116681877-1f6df380-a9e0-11eb-8394-c31cd2ab001f.png)

Email repeatedly

**Comment by maozhenzhen** [comment]
hi,Have you solved the problem  @lswlsw

**Comment by thanks-git** [comment]
Hi, Have you solved the problem? @maozhenzhen
