### ISSUE TITLE
Spring native compatibility

### ISSUE THREAD

**Issue by Sunny2720** [codecentric/spring-boot-admin#1743]
- Spring boot: 2.5.1
- Spring boot admin: 2.4.1
- Spring native version: 0.10.0

I have been trying around building a spring native image for the spring boot admin server.

`[ERROR] Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.10.0:test-generate (test-generate) on project eureka: Build failed during Spring AOT test code generation: ERROR: in 'de.codecentric.boot.admi
n.server.config.AdminServerNotifierAutoConfiguration$MailNotifierConfiguration' these methods are directly invoking methods marked @Bean: [mailNotifier] - due to the enforced proxyBeanMethods=false for components in a native-image,
please consider refactoring to use instance injection. If you are confident this is not going to affect your application, you may turn this check off using -Dspring.native.verify=false. -> [Help 1]`

This is the error I get.

**Comment by ozkanpakdil** [comment]
This looks like more of spring-native issue then SBA, out of curiosity, did you try to run it with "-Dspring.native.verify=false"

**Comment by srempfer** [comment]
![image](https://user-images.githubusercontent.com/3134465/124560624-511a9500-de3d-11eb-9fb0-eeab1c207811.png)

**Comment by Sunny2720** [comment]
@ozkanpakdil I had tried with "-Dspring.native.verify=false" without success. The error still remains the same.

**Comment by srempfer** [comment]
@Sunny2720: Could you try it we the code change I made in #1763? Are there other Spring AOT test code generation errors?

**Comment by Sunny2720** [comment]
![image](https://user-images.githubusercontent.com/15946983/124596920-71b80e80-de80-11eb-9c3f-7c57fb1ab1a6.png)
I am facing some issues while building Spring Boot Admin Server UI. 
@srempfer Any idea why it might be failing? I am running on windows.

**Comment by srempfer** [comment]
@Sunny2720: Unfortunately I've no experiences with npm and the frontend stuff of the project...

**Comment by ozkanpakdil** [comment]
that looks like a gyp issue. according to https://github.com/atom/atom/issues/2077#issuecomment-42716876 and https://stackoverflow.com/a/66398860/175554 I would suggest clean it up re-try from scratch.

**Comment by Sunny2720** [comment]
Sorry for being inactive for a while. Thanks @ozkanpakdil , that resolved the issue. And @srempfer I moved past that error to get stuck in another issue.
`
WARNING: Could not register reflection metadata for org.springframework.cloud.netflix.eureka.config.EurekaConfigServerBootstrapper. Reason: java.lang.NoClassDefFoundError: org/springframework/cloud/config/client/ConfigServerInstanceProvider$Function.
WARNING: Could not register reflection metadata for org.springframework.boot.autoconfigure.security.SecurityDataConfiguration. Reason: java.lang.NoClassDefFoundError: org/springframework/security/data/repository/query/SecurityEvaluationContextExtension.
[eureka:5205]     analysis: 219,508.60 ms,  5.12 GB
Fatal error:java.lang.NoClassDefFoundError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.NoClassDefFoundError: javax/mail/MessagingException
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getConstructor0(Class.java:3342)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
        at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:316)
        at com.oracle.svm.hosted.ServiceLoaderFeature.duringAnalysis(ServiceLoaderFeature.java:178)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$14(NativeImageGenerator.java:765)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: javax.mail.MessagingException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 17 more
Error: Image build request failed with exit status 1
`
The optional dependencies like mail is the culprit here.

**Comment by srempfer** [comment]
@Sunny272: I referenced a Spring Boot Admin Sample for Spring Native with some required native hints.

**Comment by Sunny2720** [comment]
Thanks @srempfer. I will try it out.

**Comment by ulischulte** [comment]
The problem seems to be solved. If there are any further issues, feel free to reopen the issue.
