### ISSUE TITLE
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout

### ISSUE THREAD

**Issue by thanks-git** [codecentric/spring-boot-admin#1774]
** Question **
The background sub service client is normal, but the admin server reports the following error; And keep sending mail？

** Enhancement **

 java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
 Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET health [DefaultWebClient]
 Stack trace:
                at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
                at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:279)
                at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:418)
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
                at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:270)
                at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:285)
                at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
                at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

**Comment by SteKoe** [comment]
Hi, could you please try to check if the solution provided on Stackoverflow solves your problem? https://stackoverflow.com/a/67381494

**Comment by romilptl** [comment]
@SteKoe I am also facing the same issue, SBA keeps sending the email when even the client application is up. Unfortunately, the client application does use the Eureka dependency, is there any other way to increase the timeout value?

**Comment by romilptl** [comment]
There is configurable property in [AdminServerProperties](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerProperties.java) defaultTimeout which can 
 be overridden using **`spring.boot.admin.monitor.timeout.`** . 

I have increased the timeout value to 60000 and it has prevented the unwanted email alerts due to timeout even when the application is UP. 

```
spring.boot.admin.monitor.timeout.defaultTimeout=60000
spring.boot.admin.monitor.timeout.default-timeout=60000 
```

**Comment by thanks-git** [comment]
@ulischulte  No, no, my registry uses Nacos

**Comment by thanks-git** [comment]
@romilptl  @ulischulte  Maybe so. It seems better to know the deep-seated reasons. Thanks

**Comment by thanks-git** [comment]
@AkaneMurakawa  Well, thank you for your ideas, but I'm not a problem with this version .

**Comment by ulischulte** [comment]
@thanks-git 
If you're not facing any more problems, is it OK with you to close the issue?

**Comment by thanks-git** [comment]
@ulischulte  Closed, thank you
