### ISSUE TITLE
DuplicateKeyException: INSERT INTO SPRING_SESSION_ATTRIBUTES

### ISSUE THREAD

**Issue by melloware** [codecentric/spring-boot-admin#1852]
**Spring Boot:** 2.5.6
**Spring Admin:** 2.5.3
**Servlet Engine:** Undertow or Tomcat

When registering client apps using standard SBA Client I am seeing a lot of these stack traces in the log...

It looks like its trying to write the same session to H2 and getting a deadlock.

```
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO SPRING_SESSION_ATTRIBUTES (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES) VALUES (?, ?, ?)]; integrity constraint violation: unique constraint or index violation; SPRING_SESSION_ATTRIBUTES_PK table: SPRING_SESSION_ATTRIBUTES; nested exception is java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SPRING_SESSION_ATTRIBUTES_PK table: SPRING_SESSION_ATTRIBUTES
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247) ~[spring-jdbc-5.3.12.jar:5.3.12]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.12.jar:5.3.12]
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.12.jar:5.3.12]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.12.jar:5.3.12]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.12.jar:5.3.12]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015) ~[spring-jdbc-5.3.12.jar:5.3.12]
        at org.springframework.session.jdbc.JdbcIndexedSessionRepository.insertSessionAttributes(JdbcIndexedSessionRepository.java:507) ~[spring-session-jdbc-2.5.3.jar:2.5.3]
        at org.springframework.session.jdbc.JdbcIndexedSessionRepository.access$1200(JdbcIndexedSessionRepository.java:133) ~[spring-session-jdbc-2.5.3.jar:2.5.3]
        at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.lambda$save$10(JdbcIndexedSessionRepository.java:854) ~[spring-session-jdbc-2.5.3.jar:2.5.3]
        at org.springframework.transaction.support.TransactionOperations.lambda$executeWithoutResult$0(TransactionOperations.java:68) ~[spring-tx-5.3.12.jar:5.3.12]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.12.jar:5.3.12]
        at org.springframework.transaction.support.TransactionOperations.executeWithoutResult(TransactionOperations.java:67) ~[spring-tx-5.3.12.jar:5.3.12]
        at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.save(JdbcIndexedSessionRepository.java:836) ~[spring-session-jdbc-2.5.3.jar:2.5.3]
        at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.access$200(JdbcIndexedSessionRepository.java:665) ~[spring-session-jdbc-2.5.3.jar:2.5.3]
        at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:422) ~[spring-session-jdbc-2.5.3.jar:2.5.3]
        at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:133) ~[spring-session-jdbc-2.5.3.jar:2.5.3]
        at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:226) ~[spring-session-core-2.5.3.jar:2.5.3]
        at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:193) ~[spring-session-core-2.5.3.jar:2.5.3]
        at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:145) ~[spring-session-core-2.5.3.jar:2.5.3]
        at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) ~[spring-session-core-2.5.3.jar:2.5.3]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.5.6.jar:2.5.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.12.jar:5.3.12]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.12.jar:5.3.12]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.12.jar:5.3.12]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
```

**Comment by erikpetzold** [comment]
Hi @melloware 
as far as we can see, SBA is not involved here. You configured your client application to store session data to H2 and this is where the error happens.
From the stacktrace you can see that this happens when invoking the metrics actuator, which is probably done by SBA. So this is why SBA is triggering the issue. But you have to fix this in your client.

**Comment by ulischulte** [comment]
Could be related to https://github.com/spring-projects/spring-session/issues/1802

**Comment by melloware** [comment]
Yes it's that issue and it's when I use SBA out of the box with H2.  It's happening inside SBA.  You recommend turning off H2?

**Comment by melloware** [comment]
I can't find anything in your docs about how to disable storing sessions in H2.  Can someone point me in the right direction?

**Comment by erikpetzold** [comment]
As I wrote, this has nothing to do with Spring Boot Admin.
You have enabled this feature in your client application, either explicitly
or implicit due to some dependency and Spring Boot autoconfiguration

Melloware ***@***.***> schrieb am Sa., 13. Nov. 2021, 01:29:

**Comment by melloware** [comment]
@erikpetzold Maybe we are confusing the terms Server and Client?  This error is not happening in my Client Application it is happening the the SBA Server.   AS far as I can tell this has nothing to do with my client I am using your Server out of the box from your Samples page here: https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-war

**Comment by erikpetzold** [comment]
Hi, ok to make some things more clear:

- with "server" we refer to the Spring-Boot-Admin server
- with "client" we refer to the monitored application (which includes the spring-boot-admin-client dependency) 
- when checking the dependencies of the sample you mentioned there is no spring-session and no h2 (can you please execute `mvn dependency:tree` to see where it is coming from?)
- what I wrote about metric actuator above was probably wrong, there is only rthe WebMvcMetricsFilter in the stack trace which is recording metrics on any request

So for now my understanding is that your Spring Boot Admin server is reqceiving some http request, creates a session and tries to store the session onto h2 database.
1) It seems there is a bug in spring-session.
2) As you said you don't want to store your sessions to h2, you have to find out why it tries to do so (is no default feature of SBA). Try starting with the dependency to spring-session as I wrote above.

**Comment by melloware** [comment]
OK got to the bottom of it. Its definitely your sample WAR file.  I had to add this dependency:
```xml
        <dependency>
            <groupId>org.hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
        </dependency>
```

Because if I try and start without it I get this error:

```
:: Spring Boot ::                (v2.5.6)

2021-11-15 07:13:31.088  INFO 11080 --- [           main] .c.b.a.SpringBootAdminServletApplication : Starting SpringBootAdminServletApplication using Java 11.0.10 on UPTWL21H13105 with PID 11080 
2021-11-15 07:13:31.088  INFO 11080 --- [           main] .c.b.a.SpringBootAdminServletApplication : The following profiles are active: secure
2021-11-15 07:13:31.142  WARN 11080 --- [           main] o.s.b.c.config.ConfigDataEnvironment     : Property 'spring.profiles' imported from location 'class path resource [application.yml]' is invalid and should be replaced with 'spring.config.activate.on-profile' [origin: class path resource [application.yml] - 63:13]
2021-11-15 07:13:31.142  WARN 11080 --- [           main] o.s.b.c.config.ConfigDataEnvironment     : Property 'spring.profiles' imported from location 'class path resource [application.yml]' is invalid and should be replaced with 'spring.config.activate.on-profile' [origin: class path resource [application.yml] - 57:13]
2021-11-15 07:13:32.474  WARN 11080 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2021-11-15 07:13:32.490  INFO 11080 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2021-11-15 07:13:32.490  INFO 11080 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1332 ms
2021-11-15 07:13:32.514  WARN 11080 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.session.JdbcSessionConfiguration$SpringBootJdbcHttpSessionConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in de.codecentric.boot.admin.SpringBootAdminServletApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.jdbc.datasource.embedded.EmbeddedDatabase]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Driver for test database type [HSQL] is not available
2021-11-15 07:13:32.529  INFO 11080 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-15 07:13:32.545 ERROR 11080 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.session.JdbcSessionConfiguration$SpringBootJdbcHttpSessionConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in de.codecentric.boot.admin.SpringBootAdminServletApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.jdbc.datasource.embedded.EmbeddedDatabase]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Driver for test database type [HSQL] is not available
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.5.6.jar:2.5.6]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.12.jar:5.3.12]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.6.jar:2.5.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.6.jar:2.5.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.6.jar:2.5.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.6.jar:2.5.6]
        at de.codecentric.boot.admin.SpringBootAdminServletApplication.main(SpringBootAdminServletApplication.java:55) ~[classes/:na]
Caused by: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.session.JdbcSessionConfiguration$SpringBootJdbcHttpSessionConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in de.codecentric.boot.admin.SpringBootAdminServletApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.jdbc.datasource.embedded.EmbeddedDatabase]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Driver for test database type [HSQL] is not available
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:257) ~[undertow-servlet-2.2.12.Final.jar:2.2.12.Final]
        at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createManager(UndertowServletWebServerFactory.java:347) ~[spring-boot-2.5.6.jar:2.5.6]
        at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:316) ~[spring-boot-2.5.6.jar:2.5.6]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182) ~[spring-boot-2.5.6.jar:2.5.6]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160) ~[spring-boot-2.5.6.jar:2.5.6]
        ... 6 common frames omitted
```

**Comment by melloware** [comment]
Ahh nevermind I was following an old example which had the Embedded Database Configuration.  I have removed it and this error is gone.

Thanks for your help.
