### ISSUE TITLE
Client getting "Temporary failure in name resolution" error on AWS EC2

### ISSUE THREAD

**Issue by mh-ckantzer** [codecentric/spring-boot-admin#1872]
I'm trying to deploy SpringbootAdmin server and client to the same EC2 instance, but I'm getting the following exception when the client starts (X'd out IPs which is the internal IP of the ec2 instance):

```
2021-12-02 15:01:44,616 [registrationTask1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: ip-xx-xxx-xx-xxx: ip-xx-xx-xx-xxx: Temporary failure in name resolution
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getLocalHost(DefaultApplicationFactory.java:121)
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceHost(DefaultApplicationFactory.java:104)
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceUrl(DefaultApplicationFactory.java:65)
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getManagementUrl(DefaultApplicationFactory.java:77)
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:92)
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:46)
        at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:126)
        at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:65)
        at de.codecentric.boot.admin.client.registration.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:80)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: ip-xx-xxx-xx-xxx:  ip-xx-xxx-xx-xxx: Temporary failure in name resolution
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getLocalHost(DefaultApplicationFactory.java:119)
        ... 16 common frames omitted
Caused by: java.net.UnknownHostException:  ip-xx-xxx-xx-xxx: Temporary failure in name resolution
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 17 common frames omitted
```

I also see the following warning when the admin server starts:

```
2021-12-01 16:55:31,858 [main - ] WARN  o.s.c.c.d.n.NoopDiscoveryClientAutoConfiguration - Cannot get host info: ( ip-xx-xxx-xx-xxx:  ip-xx-xxx-xx-xxx: Temporary failure in name resolution)
2021-12-01 16:55:31,911 [main - ] WARN  c.n.c.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2021-12-01 16:55:31,914 [main - ] INFO  c.n.c.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath. 
```

I'm running an older version (1.5.0) for some legacy software that we are trying to migrate from on-prem to AWS.  

Here is my client config:

spring.boot.admin.client.url=https://127.0.0.1:9000/springbootadmin/

I've tried localhost and the actual ip of the ec2 instance for the client url and I get the same error.  It's very possible it's a firewall issue or permissions issue, but I don't know where to start looking since I'm not sure why the client/admin servers are getting this error.

I can hitting both the client and admin urls using curl in the EC2 command line using localhost, ip, etc, so I know the instances are running correctly. 

Any suggestions would be appreciated.

**Comment by mh-ckantzer** [comment]
Turns out I was using the wrong property names for 1.5.  Using the correct property name and adding the prefer-ip flag and service/management urls solved the problem.
