### ISSUE TITLE
karma error: The header content contains invalid characters

### ISSUE THREAD

**Issue by jakabgergely** [codecentric/spring-boot-admin#194]
hi, thank you for the fast answer for my previous issue, now I have got stuck with karma error on WIN 8.1 HUN

**Comment by joshiste** [comment]
sorry not enough information.

**Comment by jakabgergely** [comment]
True, 
locale is Hungarian on Win 8
and sending error message:

[17:57:17] Starting 'karma'...
[17:57:17] Starting Karma server...
(node:5144) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:5144) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
[32mINFO [karma]: [39mKarma v0.12.37 server started at http://localhost:9876/
[32mINFO [launcher]: [39mStarting browser Chrome
[32mINFO [launcher]: [39mStarting browser Firefox
[31mERROR [launcher]: [39mCannot start Firefox
	Can not find the binary C:\Program Files\Mozilla Firefox\firefox.exe
	Please set env variable FIREFOX_BIN
[32mINFO [Chrome 50.0.2661 (Windows 8.1 0.0.0)]: [39mConnected on socket jBO_AQuLnPMV7saCr72B with id 38769240
[31mERROR [karma]: [39mTypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ServerResponse.res.setHeader (C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\node_modules\connect\lib\patch.js:134:22)
    at Object.setNoCacheHeaders (C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\lib\middleware\common.js:76:12)
    at C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\lib\middleware\karma.js:109:18
    at C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\lib\middleware\common.js:63:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ServerResponse.res.setHeader (C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\node_modules\connect\lib\patch.js:134:22)
    at Object.setNoCacheHeaders (C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\lib\middleware\common.js:76:12)
    at C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\lib\middleware\karma.js:109:18
    at C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\karma\lib\middleware\common.js:63:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\gulpfile.js:149
            throw err;
            ^
Error: karma exited with code 1
    at done (C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\gulp-karma\index.js:56:30)
    at ChildProcess.<anonymous> (C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui\node_modules\gulp-karma\index.js:82:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by joshiste** [comment]
Try updating the karma version >= `0.13.20` in the `package.version`. There is a bug in older karma with non-english locales (see https://github.com/karma-runner/karma/issues/1994).

I'm currently working on a rewrite of the ui build using webpack, this will have a newer karma version so I won't do a short term fix.
