### ISSUE TITLE
Wrong port used during server start

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#196]
I have configured non default port 8602 for spring-boot-admin. Just after start (not always) server logs message:

```
New Application Application [id=18a92494, name=ADMINSERVER, managementUrl=http://localhost:8080/management, healthUrl=http://localhost:8080/management/health, serviceUrl=http://localhost:8080/] registered
```
Port 8080? I have no application running on port 8080. This is a spring-boot-admin default port. After some time proper application is registered:

```
New Application Application [id=4108e779, name=ADMINSERVER, managementUrl=http://localhost:8602/management, healthUrl=http://localhost:8602/management/health, serviceUrl=http://localhost:8602/] registered
```

See full stacktrace:

```
08:58:31.743  INFO [adminserver,,,] --- [        Timer-0] c.d.d.a.d.DynamicEurekaInstanceDiscovery : No apps configured, returning an empty instance list
08:58:33.052  INFO [adminserver,,,] --- [           main] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=18a92494, name=ADMINSERVER, managementUrl=http://localhost:8080/management, healthUrl=http://localhost:8080/management/health, serviceUrl=http://localhost:8080/] registered
08:58:34.059  WARN [adminserver,,,] --- [           main] d.c.boot.admin.registry.StatusUpdater    : Couldn't retrieve status for Application [id=18a92494, name=ADMINSERVER, managementUrl=http://localhost:8080/management, healthUrl=http://localhost:8080/management/health, serviceUrl=http://localhost:8080/]

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8080/management/health": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:289)
        at de.codecentric.boot.admin.registry.StatusUpdater.queryStatus(StatusUpdater.java:78)
        at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:62)
        at de.codecentric.boot.admin.config.AdminServerWebConfiguration.onClientApplicationRegistered(AdminServerWebConfiguration.java:173)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:348)
        at de.codecentric.boot.admin.registry.ApplicationRegistry.register(ApplicationRegistry.java:82)
        at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:71)
        at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onInstanceRegistered(ApplicationDiscoveryListener.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
        at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:111)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:852)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at com.daimler.daivb.core.DaivbSpringApplication.run(DaivbSpringApplication.java:56)
        at com.daimler.daivb.core.DaivbSpringApplication.run(DaivbSpringApplication.java:29)
        at com.daimler.daivb.adm.AdminServerApplication.main(AdminServerApplication.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:80)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
        ... 52 common frames omitted

08:58:34.160  INFO [adminserver,,,] --- [           main] c.d.daivb.adm.AdminServerApplication     : Started AdminServerApplication in 15.229 seconds (JVM running for 26.653)
08:58:37.076  INFO [adminserver,861510b40e07f70f,861510b40e07f70f,false] --- [  XNIO-3 task-1] io.undertow.servlet                      : Initializing Spring FrameworkServlet 'dispatcherServlet'
08:58:37.077  INFO [adminserver,861510b40e07f70f,861510b40e07f70f,false] --- [  XNIO-3 task-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
08:58:37.103  INFO [adminserver,861510b40e07f70f,861510b40e07f70f,false] --- [  XNIO-3 task-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 26 ms
08:59:01.573  INFO [adminserver,,,] --- [freshExecutor-0] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=4108e779, name=ADMINSERVER, managementUrl=http://localhost:8602/management, healthUrl=http://localhost:8602/management/health, serviceUrl=http://localhost:8602/] registered

```

It not always happens... Sometime good port is used but spring-boot-admin is trying to use it before fully started:

```
09:06:56.787  INFO [adminserver,,,] --- [        Timer-0] c.d.d.a.d.DynamicEurekaInstanceDiscovery : No apps configured, returning an empty instance list
09:06:57.187  INFO [adminserver,,,] --- [           main] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=4108e779, name=ADMINSERVER, managementUrl=http://localhost:8602/management, healthUrl=http://localhost:8602/management/health, serviceUrl=http://localhost:8602/] registered
09:06:58.191  WARN [adminserver,,,] --- [           main] d.c.boot.admin.registry.StatusUpdater    : Couldn't retrieve status for Application [id=4108e779, name=ADMINSERVER, managementUrl=http://localhost:8602/management, healthUrl=http://localhost:8602/management/health, serviceUrl=http://localhost:8602/]

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8602/management/health": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:289)
        at de.codecentric.boot.admin.registry.StatusUpdater.queryStatus(StatusUpdater.java:78)
        at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:62)
        at de.codecentric.boot.admin.config.AdminServerWebConfiguration.onClientApplicationRegistered(AdminServerWebConfiguration.java:173)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:348)
        at de.codecentric.boot.admin.registry.ApplicationRegistry.register(ApplicationRegistry.java:82)
        at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:71)
        at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onInstanceRegistered(ApplicationDiscoveryListener.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
        at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:111)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:852)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at com.daimler.daivb.core.DaivbSpringApplication.run(DaivbSpringApplication.java:56)
        at com.daimler.daivb.core.DaivbSpringApplication.run(DaivbSpringApplication.java:29)
        at com.daimler.daivb.adm.AdminServerApplication.main(AdminServerApplication.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:80)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
        ... 52 common frames omitted

09:06:58.322  INFO [adminserver,,,] --- [           main] c.d.daivb.adm.AdminServerApplication     : Started AdminServerApplication in 12.877 seconds (JVM running for 19.676)
```

**Comment by joshiste** [comment]
Which version of Spring Boot Admin you are using. Can you please provide a small sample project to reproduce the issue?

**Comment by tjuchniewicz** [comment]
I'm using 1.3.3-SNAPSHOT. 

I will try to make sample but it will take some time...

**Comment by joshiste** [comment]
Are you using the discovery support or the spring-boot-admin-starter-client?

**Comment by tjuchniewicz** [comment]
I'm using discovery support.

**Comment by joshiste** [comment]
> I'm using discovery support. 

Can you debug into the converter? Maybe it's a fault in eureka and not spring boot admin...

**Comment by tjuchniewicz** [comment]
My debug result:

```java
public class EurekaServiceInstanceConverter implements ServiceInstanceConverter {

   private Application EurekaServiceInstanceConverter.convert(InstanceInfo instanceInfo) {
      String mgmtUrl = instanceInfo.getHomePageUrl(); // mgmtUrl = http://localhost:8080/management
...
```

`instanceInfo` is read from Eureka?

**Comment by joshiste** [comment]
>instanceInfo is read from Eureka?

Yes it is. So I don't think it's an spring boot admin issue...

**Comment by tjuchniewicz** [comment]
I confirm that this is Eureka problem. I sniffed communication between Boot Admin and Eureka and Eureka returns wrong information. 

This happens after restart of Boot Admin. It looks like Eureka returns corrupted, old values for instance which was shut down earlier.

**Comment by tjuchniewicz** [comment]
But what about second problem.

It not always happens... Sometime good port is used but spring-boot-admin is trying to use it before fully started? This is maybe because of following scenario: 

1. Eureka starts
2. Spring Boot Admin Server registers itself in Eureka. 
3. Admin stops
4. Admin starts again
5. Admin gets application list from Eureka and Eureka returns information about old Admin instance.
6. Admin try to connect to this old instance but it fails and logs error message about problem with connection. Maybe because Admin is not fully started yet.

**Comment by joshiste** [comment]
Does the port change between restarts?

**Comment by tjuchniewicz** [comment]
No.
