### ISSUE TITLE
Admin starts checking itself before it binds on tcp port

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#201]
It not always happens... some race-condition happens.

Scenario:

1. Eureka starts
2. Spring Boot Admin Server registers itself in Eureka.
3. Admin gets application list from Eureka and Eureka returns information about just registered Admin instance.
4. Admin try to connect to this instance but it fails and logs error message about problem with connection. Admin is not fully started yet. Trying to deal with app (itself) but not listening on tcp port yet.

Log messages:
```
12:31:39.036  INFO [adminserver,,,] --- [           main] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
12:31:39.175  INFO [adminserver,,,] --- [           main] c.n.e.EurekaDiscoveryClientConfiguration : Registering application adminserver with eureka with status UP
12:31:39.182  INFO [adminserver,,,] --- [           main] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=c8d1059e, name=CONFIGSERVER, managementUrl=http://localhost:8601/management, healthUrl=http://localhost:8601/management/health, serviceUrl=http://localhost:8601/] registered
12:31:39.397  INFO [adminserver,,,] --- [           main] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=4108e779, name=ADMINSERVER, managementUrl=http://localhost:8602/management, healthUrl=http://localhost:8602/management/health, serviceUrl=http://localhost:8602/] registered
12:31:40.403  WARN [adminserver,,,] --- [           main] d.c.boot.admin.registry.StatusUpdater    : Couldn't retrieve status for Application [id=4108e779, name=ADMINSERVER, managementUrl=http://localhost:8602/management, healthUrl=http://localhost:8602/management/health, serviceUrl=http://localhost:8602/]

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8602/management/health": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:289)
        at de.codecentric.boot.admin.registry.StatusUpdater.queryStatus(StatusUpdater.java:78)
        at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:62)
        at de.codecentric.boot.admin.config.AdminServerWebConfiguration.onClientApplicationRegistered(AdminServerWebConfiguration.java:173)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:348)
        at de.codecentric.boot.admin.registry.ApplicationRegistry.register(ApplicationRegistry.java:82)
        at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:71)
        at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onInstanceRegistered(ApplicationDiscoveryListener.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:227)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
        at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:111)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:852)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at com.adm.AdminServerApplication.main(AdminServerApplication.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:80)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
        ... 52 common frames omitted

12:31:40.544  INFO [adminserver,,,] --- [           main] b.c.e.u.UndertowEmbeddedServletContainer : Undertow started on port(s) 8602 (http)
12:31:40.545  INFO [adminserver,,,] --- [           main] c.n.e.EurekaDiscoveryClientConfiguration : Updating port to 8602
12:31:40.550  INFO [adminserver,,,] --- [           main] c.n.e.EurekaDiscoveryClientConfiguration : Updating port to 8602
12:31:40.555  INFO [adminserver,,,] --- [           main] c.d.adm.AdminServerApplication     : Started AdminServerApplication in 17.402 seconds (JVM running for 18.063)
```

**Comment by joshiste** [comment]
To fix this the `updateTaskRegistrar`  must not be started before the `ApplicationStartedEvent` is fired.

**Comment by tjuchniewicz** [comment]
Any easy way to reconfigure Spring Boot Admin 1.3.3?

**Comment by joshiste** [comment]
Hmm... you could replace the `StatusUpdater`-bean with one, that does nothing until it sees the `ApplicationStartedEvent`... But this is more a workaround....

**Comment by tjuchniewicz** [comment]
This fix does not work for me.

I use this workaround:

```java

@EnableAdminServer
@EnableTurbine
@Slf4j
public class AdminServerApplication implements ApplicationListener<ContextRefreshedEvent> {

     ...

    @Autowired
    ApplicationContext applicationContext;
    
    @Autowired
    AdminServerProperties adminServerProperties;
    
    @Autowired
    private ApplicationStore applicationStore;

    @Primary
    @Bean
    @ConditionalOnMissingBean
    public StatusUpdater statusUpdater() {
        
        log.info("Registering patched version of de.codecentric.boot.admin.registry.StatusUpdates");
        
        RestTemplate template = new RestTemplate();
        template.getMessageConverters().add(new MappingJackson2HttpMessageConverter());
        template.setErrorHandler(new DefaultResponseErrorHandler() {
            @Override
            protected boolean hasError(HttpStatus statusCode) {
                return false;
            }
        });
        StatusUpdater statusUpdater = new PatchedStatusUpdater(template, applicationStore);
        statusUpdater.setStatusLifetime(adminServerProperties.getMonitor().getStatusLifetime());
        
        return statusUpdater;
    }

    @Override
    public void onApplicationEvent(ContextRefreshedEvent  event) {
        
        PatchedStatusUpdater statusUpdater = (PatchedStatusUpdater) applicationContext.getBean("statusUpdater");
        statusUpdater.setActive(true);
    }
}

@Slf4j
public class PatchedStatusUpdater extends StatusUpdater {

    private boolean active = false;
    
    public PatchedStatusUpdater(RestTemplate restTemplate, ApplicationStore store) {
        super(restTemplate, store);
    }

    @Override
    public void updateStatus(Application application) {

        if (active) {
            super.updateStatus(application);
        } else {
            log.info("Application not started yet. Application update process not executed");
        }
    }

    public void setActive(boolean b) {
        log.debug("Setting active property to: {}", b);
        active = b;
    }

    public boolean isActive() {
        return active;
    }
}
```
