### ISSUE TITLE
Spring Boot Admin results in error 500

### ISSUE THREAD

**Issue by VineetJT** [codecentric/spring-boot-admin#204]
Hi

I am trying to register a client with admin server using client starter. Following is the version of jar being used:
spring-boot-admin-server-1.3.1.jar
spring-boot-admin-server-ui-1.3.1.jar
spring-boot-admin-starter-client-1.3.1.jar
spring-boot-1.3.5.RELEASE.jar
Spring 4.2.4

Server is up and I am able to view the UI. 

Following error is receiver when trying to register a client:
```
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: statusInfo must not be null!] with root cause
java.lang.IllegalArgumentException: statusInfo must not be null!
	at org.springframework.util.Assert.notNull(Assert.java:115)
	at de.codecentric.boot.admin.model.Application.<init>(Application.java:42)
	at de.codecentric.boot.admin.model.Application$Builder.build(Application.java:133)
```

```
Following is the application.properties for the client

endpoints.health.enabled=true
endpoints.health.sensitive=false
management.health.status.order=UP,DOWN,UNKNOWN
server.port = 9000
management.port: 9000
management.address: 127.0.0.1
management.contextPath=/admin
spring.boot.admin.url=http://localhost:8080
info.version=@project.version@
```

It is a very simple code for test:

Server:
```java
@SpringBootApplication
@EnableAdminServer
public class SpringAdmin {
	
	    	public static void main(String[] args) {
	    		SpringApplication.run(SpringAdmin.class, args);
	    	}

	    }
```
Client:

```java
package test;

import org.springframework.beans.factory.annotation.Autowired;
@Controller
@EnableAutoConfiguration
@ComponentScan(basePackages = "test")
public class SpringBoot {
	
	@Autowired
	CountService service;
	
	    @RequestMapping(value = "/hello",method = RequestMethod.GET)
	    @ResponseBody
	    String home() {
	    	service.exampleMethod();
	    	return "hello.jsp";
	    }

	   public static void main(String[] args) throws Exception {
	    	//System.setProperty("spring.jmx.enabled", "false");
	    	//System.setProperty("server.port", "8081");
	        SpringApplication.run(SpringBoot.class);
	       
	    }
	   
	   
	   @Bean
	    public static Endpoint exampleEndpoint() {
	        return new Endpoint<String>() {
	            @Override
	            public String getId() {
	                return "hello";
	            }

	            @Override
	            public boolean isEnabled() {
	                return true;
	            }

	            @Override
	            public boolean isSensitive() {
	                return false;
	            }

	            @Override
	            public String invoke() {
	                return "hello";
	            }
	        };
	    }

}
```

**Comment by joshiste** [comment]
please update to spring boot admin 1.3.3

**Comment by VineetJT** [comment]
Seems the issue happens only when using port 8080 on server. I changed to other port and seems to resolve the issue.

On a side note, is there any way to use JAVA 6 with admin and client? Right now we are using JRE6 and it seems to be compatible class error.

**Comment by joshiste** [comment]
> Seems the issue happens only when using port 8080 on server. I changed to other port and seems to resolve the issue.

Can you provide me the complete project for your admin server to track down the issue?

> On a side note, is there any way to use JAVA 6 with admin and client? Right now we are using JRE6 and it seems to be compatible class error.

Our build is for Java 7. You have to build it yourself if you want to use it with Java 1.6, maybe some minor  changes are required.

**Comment by joshiste** [comment]
closing due to missing response

**Comment by Taominghua** [comment]
I also encountered the same problem.I upgraded the package version to the same version and solved the problem.
