### ISSUE TITLE
Question: Graalvm Native support - Spring boot 3.0

### ISSUE THREAD

**Issue by Dam14n** [codecentric/spring-boot-admin#2163]
Hi team,

First, thanks for this amazing project that you are working on!

I have been testing Spring boot 3.0 (SNAPSHOT) with Graalvm Native support and Spring Boot Admin. Running locally is working as expected but I'm having some issues when building the Docker image in native mode.

Quick question, are you planning to support graalvm configuration? like autoconfiguration for native-hints (I mean this https://docs.spring.io/spring-boot/docs/3.0.0-SNAPSHOT/reference/htmlsingle/#native-image.advanced.custom-hints) in Spring boot 3.0 or adding some reachability-metadata (if needed) in the graalvm repo.

- https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata.

Or is it something that we should config on our end?? thanks a lot

**Comment by erikpetzold** [comment]
Hi @Dam14n 

I think we don't have any native hints yet.

We have a branch for spring boot 3 support (https://github.com/codecentric/spring-boot-admin/tree/experimental/spring-boot-3-playground) and you can use our snapshot release by adding the snapshot repo: https://github.com/codecentric/spring-boot-admin#snapshot-builds

If you find something that should be added to SBA directly we would be happy if you file a Pull Request with the native hints against this branch.

Regards, Erik

**Comment by Dam14n** [comment]
Hi @erikpetzold,

Thanks for the fast reply!

I will give it a look and I will try to submit a PR this week.

Thanks!

**Comment by trcoelho** [comment]
Hi @Dam14n , am having same trouble!

What is being displayed is:

`No HttpMessageConverter for de.codecentric.boot.admin.client.registration.Application and content type "application/json"`

That is pretty weird since it only happened when we build a native image.

Do you have any additional configuration, as well as native hints that might help?

It should be considered if SBA is part of Spring Boot 3.0.0.

Any updates @erikpetzold ?

Thank you.

**Comment by bjorntj** [comment]
Hi.

I am having the same problem ("d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application(name=rem-authentication-service, managementUrl=http://localhost:2100/actuator, healthUrl=http://localhost:2100/actuator/health, serviceUrl=http://localhost:2100/) at spring-boot-admin ([http://localhost:2100/admin/instances]): No HttpMessageConverter for de.codecentric.boot.admin.client.registration.Application and content type "application/json"")

Using the agent is not a solution, when I do this the build of my native image fails.

So just wondering which hint(s) are needed to make SBA work when running native?

**Comment by 929541303** [comment]
Hi.
     I im having another problem:
`
org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers
        at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869)
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077)
        at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372)
        at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1414)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1158)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1097)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:691)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:441)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:367)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:295)
        at de.codecentric.boot.admin.server.ui.web.servlet.HomepageForwardingFilter.doFilter(HomepageForwardingFilter.java:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)

`
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/73211930/217218141-a4cbdff2-35a4-41ac-9166-8e6c772e943a.png">

**Comment by ulischulte** [comment]
@Dam14n,

the current snapshot (3.0.4-SNAPSHOT) now includes autoconfigurations with RuntimeHints for SBA client and server running as Spring Boot 3 native applications. You can find a running GraalVM SBA server sample (+ self registration as a client) right here: https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet-graalvm
This should solve your problem. If you encounter any other issues regarding GraalVM native support, feel free to open a new issue.

Regards,
Uli

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！
