### ISSUE TITLE
No new Notifications in Teams from Admin server

### ISSUE THREAD

**Issue by Sainir1** [codecentric/spring-boot-admin#2374]
## Spring Boot Admin Server information

- **Version**: 2.7.10(spring-boot-admin.version)
  

- **Spring Boot version**: 2.7.7(spring-boot-starter-parent)
  

- **Configured Security**: basic auth
  

- **Webflux or Servlet application**:  servlet application
  

## Client information

- **Spring Boot versions**:  2.7.4, 2.7.7
  

- **Used discovery mechanism**:  Self Registration
  

- **Webflux or Servlet application**: servlet
  

## Description
We are using below code in application.properties of Admin server so that Admin can trigger notifications in Teams tool.
   spring.boot.admin.notify.ms-teams.webhook-url=https://edisonintl.webhook.office.com/webhookb2/***
It worked initially and Admin instance successfully sent notification to Teams, but later we tried following actions, but we are not seeing any notifications in teams from Admin:
   1. shutting down monitored instance
   2. restarting monitored instance
   3. restarting admin server application
   4. restarting tomcat which hosts admin server application. 
  
Along with this we needed help if there is a way that notification can have environment information of monitored instance.

**Comment by erikpetzold** [comment]
Hi @Sainir1 ,

can you please first check if the events are showing up in Spring Boot Admin itself? Are they visible in the journal?

If not, then this is a problem with the Spring Boot Admin setup/configuration. Maybe the shutdown and restart are not even recognized. How long is your polling interval?

If they are visible in Spring Boot Admin, then your MS teams integration is not working. Maybe the webhook was removed in teams? Some permissions changed by your organization? Can you create a new webhok and test with that one?

To your last question: you cannot include information of your monitored instance as the notification is created by the Spring Boot Admin Server. The SBA server cannot access the environment information of the monitored instance. Especially if the monitored instance has been shut down.

**Comment by erikpetzold** [comment]
may be related to #2390 (?)

**Comment by Sainir1** [comment]
Hi Erik, Thanks for your inputs and Sorry for delayed response. we are trying to resolve the exception we are getting, Following is log:

2023-05-15 01:48:25.396 [reactor-http-nio-2] INFO  d.c.b.a.s.services.StatusUpdater - Couldn't retrieve status for Instance(id=num, version=4, registration=Registration(name=ApplicationName, managementUrl=https://ApplicationURL, healthUrl=https://ApplicationURL/health, serviceUrl=https://server/ApplicationName, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={clientConfigServer={status=UP, details={propertySources=[bootstrapProperties-configClient, bootstrapProperties-dbProperties, bootstrapProperties-https://github.com/ApplicationRepo.git/application-development.properties, bootstrapProperties-https://github.com/ApplicationRepo.git/application-development.properties]}}, diskSpace={status=UP, details={total=2872868864, free=878010368, threshold=10485760, exists=true}}, ping={status=UP}, discoveryComposite={description=Discovery Client not initialized, status=UNKNOWN, components={discoveryClient={description=Discovery Client not initialized, status=UNKNOWN}}}, refreshScope={status=UP}, db={status=UP, details={database=Oracle, validationQuery=isValid()}}}), statusTimestamp=2023-05-04T14:27:20.811Z, info=Info(values={tags={environment=Dev}, git={build={host=HOST, number=22, version=1.2.49-SNAPSHOT, time=2023-04-28T07:52:12Z, user={name=SampleName, email=email@sample.com}}, branch=gitBranch, commit={message={short=context path changed to ConfigServer, full=context path changed to ConfigServer}, id={describe=891d16a, abbrev=891d16a, describe-short=891d16a, full=num}, committer={time=2023-04-17T08:03:04-0700}, time=2023-04-17T15:03:04Z, user={email=num+SampleName@users.noreply.github.com, name=SampleName}, author={time=2023-04-17T08:03:04-0700}}, closest={tag={name=, commit={count=}}}, local={branch={ahead=NO_REMOTE, behind=NO_REMOTE}}, dirty=true, remote={origin={url=https://github.com/ApplicationRepo.git}}, tags=, total={commit={count=657}}}, build={version=1.2.49-SNAPSHOT, artifact=ApplicationName, name=ApplicationName, group=com.sample, time=2023-04-28T07:51:38.700Z}}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=https://ApplicationURL/health), metrics=Endpoint(id=metrics, url=https://ApplicationURL/metrics), info=Endpoint(id=info, url=https://ApplicationURL/info)}), buildVersion=1.2.49-SNAPSHOT, tags=Tags(values={environment=Dev}))
org.springframework.web.reactive.function.client.WebClientRequestException: Connection refused: no further information: ApplicationServer; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: ApplicationServer
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Request to GET health [DefaultWebClient]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537)
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343)
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:307)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:160)
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475)
		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431)
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:558)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
		at reactor.core.publisher.Operators.error(Operators.java:198)
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:580)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:534)
		at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:265)
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
		at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
		at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: ApplicationServer
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

**Comment by erikpetzold** [comment]
Hi @Sainir1 ,
so the problem is that the admin server cannot connect to the monitored application.
You need to find out if the address+port is correct, if network connection exists, firewall is not blocking etc.
