### ISSUE TITLE
Admin tries to connect to itself /management/hystrix.stream even if Hystrix is not enabled

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#239]
No all of my applications have Hystrix endpoint enabled. Especially Admin. It looks like Admin tries to monitor itself.
```
 INFO [admin-server,,,] --- [        Timer-0] c.n.t.monitor.instance.InstanceMonitor   : Url for host: http://localhost:8080/management/hystrix.stream default
ERROR [admin-server,,,] --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Could not initiate connection to host, giving up: [{,   "timestamp" : 1469611350374,,   "status" : 404,,   "error" : "Not Found",,   "message" : "Not Found",,   "path" : "/management/hystrix.stream", }]
 WARN [admin-server,,,] --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Stopping InstanceMonitor for: localhost default

com.netflix.turbine.monitor.instance.InstanceMonitor$MisconfiguredHostException: [{,   "timestamp" : 1469611350374,,   "status" : 404,,   "error" : "Not Found",,   "message" : "Not Found",,   "path" : "/management/hystrix.stream", }]
        at com.netflix.turbine.monitor.instance.InstanceMonitor.init(InstanceMonitor.java:318)
        at com.netflix.turbine.monitor.instance.InstanceMonitor.access$100(InstanceMonitor.java:103)
        at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:235)
        at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:229)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Spring Boot Admin 1.3.5. I don't remember such errors in previous versions.

**Comment by joshiste** [comment]
Why do you think it's an SBA issue? we don't have anything related to Hystrix (yet).

**Comment by tjuchniewicz** [comment]
You are right. This is probably because `@EnableHystrixDashboard` or `@EnableTurbine` we use in our SBA. 

Sorry for the inconvenience! Closing.
