### ISSUE TITLE
maven install  error:"Singleton bean creation not allowed while singletons of this factory are in destruction"

### ISSUE THREAD

**Issue by chazhiguo** [codecentric/spring-boot-admin#2403]
1.version
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.5</version>
		<relativePath/> 
	</parent>
	<spring-cloud.version>2022.0.2</spring-cloud.version>		
	<admin.starter.server.version>3.0.2</admin.starter.server.version> 
        java-18
2. maven  install , error
[2023-04-20 15:16:16.316] [ERROR] [DiscoveryClient-CacheRefreshExecutor-0] [c.n.discovery.DiscoveryClient] [DiscoveryClient.java:1497] ==== Cannot fetch registry from server ====
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'instanceDiscoveryListener': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1132)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:370)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:335)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:228)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
	at org.springframework.cloud.netflix.eureka.CloudEurekaClient.onCacheRefreshed(CloudEurekaClient.java:121)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:975)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1475)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1442)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
3.   BUILD SUCCESS, run success

**Comment by chazhiguo** [comment]
user  eureka
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>

**Comment by erikpetzold** [comment]
Hi @chazhiguo 

we're not 100% sure what you did and when you get this error.

Seems the error occurs during maven build of your application. But the message says that a spring context is starting, so this is probably a SpringBoot**Test** trying to run the context and during test there is no eureka reachable.

What do you mean by "3. BUILD SUCCESS, run success"? The maven build is successfull anyways? So do you have a real problem or is it "just" the error message in the build log?
