### ISSUE TITLE
Error when startup by giving message "serviceUrl must be set when deployed to servlet-container"

### ISSUE THREAD

**Issue by jiangyuhe123** [codecentric/spring-boot-admin#260]
Include dependency in pom.
```
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-starter-client</artifactId>
    <version>1.4.1</version>
</dependency>
```
Include hystrix stream or amqp in pom to use rabbitMQ stream.
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-netflix-hystrix-amqp</artifactId>
</dependency>
```
or
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-netflix-hystrix-stream</artifactId>
</dependency>
```

Start up spring boot application, in start up trace we can see below message, but the application can be success register to spring boot admin. I just want to know how to solve this error trace.
```
2016-09-04 15:56:17.990 ERROR 13260 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.IllegalStateException: serviceUrl must be set when deployed to servlet-container
	at de.codecentric.boot.admin.config.AdminClientProperties.getServiceUrl(AdminClientProperties.java:132)
	at de.codecentric.boot.admin.config.AdminClientProperties.getManagementUrl(AdminClientProperties.java:87)
	at de.codecentric.boot.admin.config.AdminClientProperties.getHealthUrl(AdminClientProperties.java:119)
	at de.codecentric.boot.admin.services.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:124)
	at de.codecentric.boot.admin.services.ApplicationRegistrator.register(ApplicationRegistrator.java:73)
	at de.codecentric.boot.admin.services.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:89)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-09-04 15:56:18.458  INFO 13260 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: SimpleConnection@7ef7faa9 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 50213]
2016-09-04 15:56:18.521  INFO 13260 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {message-handler:outbound.springCloudHystrixStream} as a subscriber to the 'hystrixStreamOutput' channel
2016-09-04 15:56:18.536  INFO 13260 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'zuul-service:8765.hystrixStreamOutput' has 1 subscriber(s).
2016-09-04 15:56:18.536  INFO 13260 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started outbound.springCloudHystrixStream
2016-09-04 15:56:18.536  INFO 13260 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147482648
2016-09-04 15:56:18.536  INFO 13260 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2016-09-04 15:56:18.536  INFO 13260 --- [           main] c.n.e.EurekaDiscoveryClientConfiguration : Registering application zuul-service with eureka with status UP
2016-09-04 15:56:18.614  INFO 13260 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2016-09-04 15:56:18.614  INFO 13260 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'zuul-service:8765.errorChannel' has 1 subscriber(s).
2016-09-04 15:56:18.630  INFO 13260 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2016-09-04 15:56:18.630  INFO 13260 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482647
2016-09-04 15:56:18.630  INFO 13260 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2016-09-04 15:56:18.630  INFO 13260 --- [           main] ration$HystrixMetricsPollerConfiguration : Starting poller
2016-09-04 15:56:18.630  INFO 13260 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2016-09-04 15:56:18.630  INFO 13260 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482647
2016-09-04 15:56:18.630  INFO 13260 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2016-09-04 15:56:18.739  INFO 13260 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8765 (http)
2016-09-04 15:56:18.739  INFO 13260 --- [           main] c.n.e.EurekaDiscoveryClientConfiguration : Updating port to 8765
2016-09-04 15:56:18.755  INFO 13260 --- [           main] c.s.c.z.service.ZuulServerApplication    : Started ZuulServerApplication in 16.64 seconds (JVM running for 18.104)
```

**Comment by joshiste** [comment]
Looks like it tries to register before the `local.server.port` has been set...
