### ISSUE TITLE
Offline instances don't show as offline in SBA 3.x

### ISSUE THREAD

**Issue by Peksa** [codecentric/spring-boot-admin#2667]
## Spring Boot Admin Server information

- **Version**:
3.1.3

- **Spring Boot version**:
3.1.2

- **Configured Security**:
none

- **Webflux or Servlet application**:
servlet (Tomcat)

## Client information

- **Spring Boot versions**:
3.1.2

- **Used discovery mechanism**:
self-registration

- **Webflux or Servlet application**:
servlet (Tomcat)

## Description
When upgrading from SBA 2.7.10 to 3.1.3 I noticed that instances no longer report as "offline" when they disappear/stop, but seem to be forever "UP". While viewing an instance, SBA shows HTTP 504 in widgets:

![image](https://github.com/codecentric/spring-boot-admin/assets/138212246/6aac8aad-93c8-436c-9460-1c77da4db476)

There is also a warning in the logs:

```
2023-08-07T15:27:31.179+02:00  WARN 28030 --- [     parallel-1] d.c.b.a.server.services.IntervalCheck    : Unexpected error in status-check

reactor.core.Exceptions$OverflowException: Could not emit tick 7 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:249) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:132) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.5.8.jar:3.5.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

Trying to debug the issue, I think the issue is that an error in [IntervalCheck.java](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/IntervalCheck.java#L85)
cancels the pending status check in [StatusUpdater.java](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/StatusUpdater.java#L80)

Enabling trace logging shows this output, after stopped the previously registered app:

```
2023-08-07T15:50:35.985+02:00 TRACE 29373 --- [    parallel-12] d.c.b.a.server.services.IntervalCheck    : onNext(0)
2023-08-07T15:50:35.986+02:00 DEBUG 29373 --- [    parallel-12] d.c.b.a.server.services.IntervalCheck    : check status for all instances
2023-08-07T15:50:35.986+02:00 DEBUG 29373 --- [    parallel-12] d.c.b.a.server.services.StatusUpdater    : Update status for Instance(id=3b1e9adb3094, version=2, registration=Registration(name=should-be-down, managementUrl=http://192.168.0.9:8081/actuator, healthUrl=http://192.168.0.9:8081/actuator/health, serviceUrl=http://192.168.0.9:8081/, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={}), statusTimestamp=2023-08-07T13:49:36.774245Z, info=Info(values={}), endpoints=Endpoints(endpoints={caches=Endpoint(id=caches, url=http://192.168.0.9:8081/actuator/caches), loggers=Endpoint(id=loggers, url=http://192.168.0.9:8081/actuator/loggers), health=Endpoint(id=health, url=http://192.168.0.9:8081/actuator/health), env=Endpoint(id=env, url=http://192.168.0.9:8081/actuator/env), heapdump=Endpoint(id=heapdump, url=http://192.168.0.9:8081/actuator/heapdump), scheduledtasks=Endpoint(id=scheduledtasks, url=http://192.168.0.9:8081/actuator/scheduledtasks), mappings=Endpoint(id=mappings, url=http://192.168.0.9:8081/actuator/mappings), beans=Endpoint(id=beans, url=http://192.168.0.9:8081/actuator/beans), configprops=Endpoint(id=configprops, url=http://192.168.0.9:8081/actuator/configprops), threaddump=Endpoint(id=threaddump, url=http://192.168.0.9:8081/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://192.168.0.9:8081/actuator/metrics), conditions=Endpoint(id=conditions, url=http://192.168.0.9:8081/actuator/conditions), shutdown=Endpoint(id=shutdown, url=http://192.168.0.9:8081/actuator/shutdown), info=Endpoint(id=info, url=http://192.168.0.9:8081/actuator/info)}), buildVersion=null, tags=Tags(values={}))
2023-08-07T15:50:35.989+02:00 TRACE 29373 --- [    parallel-12] d.c.b.a.server.services.StatusUpdater    : | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
2023-08-07T15:50:35.989+02:00 TRACE 29373 --- [    parallel-12] d.c.b.a.server.services.StatusUpdater    : | request(unbounded)
2023-08-07T15:50:35.990+02:00 TRACE 29373 --- [    parallel-12] .a.s.w.c.InstanceExchangeFilterFunctions : URL 'health' for Endpoint health of instance 3b1e9adb3094 rewritten to http://192.168.0.9:8081/actuator/health
2023-08-07T15:50:35.990+02:00 TRACE 29373 --- [    parallel-12] .a.s.w.c.InstanceExchangeFilterFunctions : No cookies found for request [url=http://192.168.0.9:8081/actuator/health]
2023-08-07T15:50:45.987+02:00 TRACE 29373 --- [    parallel-12] d.c.b.a.server.services.IntervalCheck    : onError(reactor.core.Exceptions$OverflowException: Could not emit tick 1 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks))
2023-08-07T15:50:45.987+02:00 TRACE 29373 --- [    parallel-12] d.c.b.a.server.services.IntervalCheck    : 

reactor.core.Exceptions$OverflowException: Could not emit tick 1 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:249) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:132) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.5.8.jar:3.5.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-08-07T15:50:45.988+02:00 TRACE 29373 --- [    parallel-12] d.c.b.a.server.services.StatusUpdater    : | cancel()
2023-08-07T15:50:45.988+02:00  WARN 29373 --- [    parallel-12] d.c.b.a.server.services.IntervalCheck    : Unexpected error in status-check

reactor.core.Exceptions$OverflowException: Could not emit tick 1 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:249) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:132) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.5.8.jar:3.5.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-08-07T15:50:48.325+02:00 DEBUG 29373 --- [ status-check-3] d.c.b.a.server.services.IntervalCheck    : Scheduled status-check every PT10S
2023-08-07T15:50:48.326+02:00 TRACE 29373 --- [ status-check-3] d.c.b.a.server.services.IntervalCheck    : onSubscribe(FluxPeek.PeekSubscriber)
2023-08-07T15:50:48.326+02:00 TRACE 29373 --- [ status-check-3] d.c.b.a.server.services.IntervalCheck    : request(1)
2023-08-07T15:50:58.331+02:00 TRACE 29373 --- [     parallel-3] d.c.b.a.server.services.IntervalCheck    : onNext(0)
2023-08-07T15:50:58.332+02:00 DEBUG 29373 --- [     parallel-3] d.c.b.a.server.services.IntervalCheck    : check status for all instances
2023-08-07T15:50:58.332+02:00 DEBUG 29373 --- [     parallel-3] d.c.b.a.server.services.StatusUpdater    : Update status for Instance(id=3b1e9adb3094, version=2, registration=Registration(name=should-be-down, managementUrl=http://192.168.0.9:8081/actuator, healthUrl=http://192.168.0.9:8081/actuator/health, serviceUrl=http://192.168.0.9:8081/, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={}), statusTimestamp=2023-08-07T13:49:36.774245Z, info=Info(values={}), endpoints=Endpoints(endpoints={caches=Endpoint(id=caches, url=http://192.168.0.9:8081/actuator/caches), loggers=Endpoint(id=loggers, url=http://192.168.0.9:8081/actuator/loggers), health=Endpoint(id=health, url=http://192.168.0.9:8081/actuator/health), env=Endpoint(id=env, url=http://192.168.0.9:8081/actuator/env), heapdump=Endpoint(id=heapdump, url=http://192.168.0.9:8081/actuator/heapdump), scheduledtasks=Endpoint(id=scheduledtasks, url=http://192.168.0.9:8081/actuator/scheduledtasks), mappings=Endpoint(id=mappings, url=http://192.168.0.9:8081/actuator/mappings), beans=Endpoint(id=beans, url=http://192.168.0.9:8081/actuator/beans), configprops=Endpoint(id=configprops, url=http://192.168.0.9:8081/actuator/configprops), threaddump=Endpoint(id=threaddump, url=http://192.168.0.9:8081/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://192.168.0.9:8081/actuator/metrics), conditions=Endpoint(id=conditions, url=http://192.168.0.9:8081/actuator/conditions), shutdown=Endpoint(id=shutdown, url=http://192.168.0.9:8081/actuator/shutdown), info=Endpoint(id=info, url=http://192.168.0.9:8081/actuator/info)}), buildVersion=null, tags=Tags(values={}))
2023-08-07T15:50:58.335+02:00 TRACE 29373 --- [     parallel-3] d.c.b.a.server.services.StatusUpdater    : | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
2023-08-07T15:50:58.335+02:00 TRACE 29373 --- [     parallel-3] d.c.b.a.server.services.StatusUpdater    : | request(unbounded)
2023-08-07T15:50:58.335+02:00 TRACE 29373 --- [     parallel-3] .a.s.w.c.InstanceExchangeFilterFunctions : URL 'health' for Endpoint health of instance 3b1e9adb3094 rewritten to http://192.168.0.9:8081/actuator/health
2023-08-07T15:50:58.336+02:00 TRACE 29373 --- [     parallel-3] .a.s.w.c.InstanceExchangeFilterFunctions : No cookies found for request [url=http://192.168.0.9:8081/actuator/health]
2023-08-07T15:51:08.328+02:00 TRACE 29373 --- [     parallel-3] d.c.b.a.server.services.IntervalCheck    : onError(reactor.core.Exceptions$OverflowException: Could not emit tick 1 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks))
2023-08-07T15:51:08.330+02:00 TRACE 29373 --- [     parallel-3] d.c.b.a.server.services.IntervalCheck    : 

reactor.core.Exceptions$OverflowException: Could not emit tick 1 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:249) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:132) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.5.8.jar:3.5.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-08-07T15:51:08.331+02:00 TRACE 29373 --- [     parallel-3] d.c.b.a.server.services.StatusUpdater    : | cancel()
2023-08-07T15:51:08.332+02:00  WARN 29373 --- [     parallel-3] d.c.b.a.server.services.IntervalCheck    : Unexpected error in status-check

reactor.core.Exceptions$OverflowException: Could not emit tick 1 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:249) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:132) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.5.8.jar:3.5.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-08-07T15:51:12.248+02:00 DEBUG 29373 --- [ status-check-3] d.c.b.a.server.services.IntervalCheck    : Scheduled status-check every PT10S
2023-08-07T15:51:12.249+02:00 TRACE 29373 --- [ status-check-3] d.c.b.a.server.services.IntervalCheck    : onSubscribe(FluxPeek.PeekSubscriber)
2023-08-07T15:51:12.249+02:00 TRACE 29373 --- [ status-check-3] d.c.b.a.server.services.IntervalCheck    : request(1)
```

..and so on.

The very similar info-updater seems to show a proper timeout, but the status-updater is somehow being cancelled.

Here's trace logging when the info-updater runs:

```
2023-08-07T15:51:14.705+02:00 TRACE 29373 --- [     parallel-2] d.c.b.a.server.services.IntervalCheck    : onNext(1)
2023-08-07T15:51:14.706+02:00 DEBUG 29373 --- [     parallel-2] d.c.b.a.server.services.IntervalCheck    : check info for all instances
2023-08-07T15:51:14.706+02:00 DEBUG 29373 --- [     parallel-2] d.c.b.admin.server.services.InfoUpdater  : Update info for Instance(id=3b1e9adb3094, version=2, registration=Registration(name=should-be-down, managementUrl=http://192.168.0.9:8081/actuator, healthUrl=http://192.168.0.9:8081/actuator/health, serviceUrl=http://192.168.0.9:8081/, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={}), statusTimestamp=2023-08-07T13:49:36.774245Z, info=Info(values={}), endpoints=Endpoints(endpoints={caches=Endpoint(id=caches, url=http://192.168.0.9:8081/actuator/caches), loggers=Endpoint(id=loggers, url=http://192.168.0.9:8081/actuator/loggers), health=Endpoint(id=health, url=http://192.168.0.9:8081/actuator/health), env=Endpoint(id=env, url=http://192.168.0.9:8081/actuator/env), heapdump=Endpoint(id=heapdump, url=http://192.168.0.9:8081/actuator/heapdump), scheduledtasks=Endpoint(id=scheduledtasks, url=http://192.168.0.9:8081/actuator/scheduledtasks), mappings=Endpoint(id=mappings, url=http://192.168.0.9:8081/actuator/mappings), beans=Endpoint(id=beans, url=http://192.168.0.9:8081/actuator/beans), configprops=Endpoint(id=configprops, url=http://192.168.0.9:8081/actuator/configprops), threaddump=Endpoint(id=threaddump, url=http://192.168.0.9:8081/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://192.168.0.9:8081/actuator/metrics), conditions=Endpoint(id=conditions, url=http://192.168.0.9:8081/actuator/conditions), shutdown=Endpoint(id=shutdown, url=http://192.168.0.9:8081/actuator/shutdown), info=Endpoint(id=info, url=http://192.168.0.9:8081/actuator/info)}), buildVersion=null, tags=Tags(values={}))
2023-08-07T15:51:14.707+02:00 TRACE 29373 --- [     parallel-2] d.c.b.admin.server.services.InfoUpdater  : | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
2023-08-07T15:51:14.707+02:00 TRACE 29373 --- [     parallel-2] d.c.b.admin.server.services.InfoUpdater  : | request(unbounded)
2023-08-07T15:51:14.707+02:00 TRACE 29373 --- [     parallel-2] .a.s.w.c.InstanceExchangeFilterFunctions : URL 'info' for Endpoint info of instance 3b1e9adb3094 rewritten to http://192.168.0.9:8081/actuator/info
2023-08-07T15:51:14.707+02:00 TRACE 29373 --- [     parallel-2] .a.s.w.c.InstanceExchangeFilterFunctions : No cookies found for request [url=http://192.168.0.9:8081/actuator/info]
2023-08-07T15:51:22.254+02:00 TRACE 29373 --- [     parallel-6] d.c.b.a.server.services.IntervalCheck    : onNext(0)
2023-08-07T15:51:22.254+02:00 DEBUG 29373 --- [     parallel-6] d.c.b.a.server.services.IntervalCheck    : check status for all instances
2023-08-07T15:51:22.255+02:00 DEBUG 29373 --- [     parallel-6] d.c.b.a.server.services.StatusUpdater    : Update status for Instance(id=3b1e9adb3094, version=2, registration=Registration(name=should-be-down, managementUrl=http://192.168.0.9:8081/actuator, healthUrl=http://192.168.0.9:8081/actuator/health, serviceUrl=http://192.168.0.9:8081/, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={}), statusTimestamp=2023-08-07T13:49:36.774245Z, info=Info(values={}), endpoints=Endpoints(endpoints={caches=Endpoint(id=caches, url=http://192.168.0.9:8081/actuator/caches), loggers=Endpoint(id=loggers, url=http://192.168.0.9:8081/actuator/loggers), health=Endpoint(id=health, url=http://192.168.0.9:8081/actuator/health), env=Endpoint(id=env, url=http://192.168.0.9:8081/actuator/env), heapdump=Endpoint(id=heapdump, url=http://192.168.0.9:8081/actuator/heapdump), scheduledtasks=Endpoint(id=scheduledtasks, url=http://192.168.0.9:8081/actuator/scheduledtasks), mappings=Endpoint(id=mappings, url=http://192.168.0.9:8081/actuator/mappings), beans=Endpoint(id=beans, url=http://192.168.0.9:8081/actuator/beans), configprops=Endpoint(id=configprops, url=http://192.168.0.9:8081/actuator/configprops), threaddump=Endpoint(id=threaddump, url=http://192.168.0.9:8081/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://192.168.0.9:8081/actuator/metrics), conditions=Endpoint(id=conditions, url=http://192.168.0.9:8081/actuator/conditions), shutdown=Endpoint(id=shutdown, url=http://192.168.0.9:8081/actuator/shutdown), info=Endpoint(id=info, url=http://192.168.0.9:8081/actuator/info)}), buildVersion=null, tags=Tags(values={}))
2023-08-07T15:51:22.256+02:00 TRACE 29373 --- [     parallel-6] d.c.b.a.server.services.StatusUpdater    : | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
2023-08-07T15:51:22.256+02:00 TRACE 29373 --- [     parallel-6] d.c.b.a.server.services.StatusUpdater    : | request(unbounded)
2023-08-07T15:51:22.257+02:00 TRACE 29373 --- [     parallel-6] .a.s.w.c.InstanceExchangeFilterFunctions : URL 'health' for Endpoint health of instance 3b1e9adb3094 rewritten to http://192.168.0.9:8081/actuator/health
2023-08-07T15:51:22.257+02:00 TRACE 29373 --- [     parallel-6] .a.s.w.c.InstanceExchangeFilterFunctions : No cookies found for request [url=http://192.168.0.9:8081/actuator/health]
2023-08-07T15:51:24.713+02:00 TRACE 29373 --- [     parallel-7] d.c.b.admin.server.services.InfoUpdater  : | onError(java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'peek' (and no fallback has been configured))
2023-08-07T15:51:24.713+02:00 TRACE 29373 --- [     parallel-7] d.c.b.admin.server.services.InfoUpdater  : 

java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'peek' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.5.8.jar:3.5.8]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to GET info [DefaultWebClient]
Original Stack Trace:
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.8.jar:3.5.8]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-08-07T15:51:24.714+02:00  WARN 29373 --- [     parallel-7] d.c.b.admin.server.services.InfoUpdater  : Couldn't retrieve info for Instance(id=3b1e9adb3094, version=2, registration=Registration(name=should-be-down, managementUrl=http://192.168.0.9:8081/actuator, healthUrl=http://192.168.0.9:8081/actuator/health, serviceUrl=http://192.168.0.9:8081/, source=http-api), registered=true, statusInfo=StatusInfo(status=UP, details={}), statusTimestamp=2023-08-07T13:49:36.774245Z, info=Info(values={}), endpoints=Endpoints(endpoints={caches=Endpoint(id=caches, url=http://192.168.0.9:8081/actuator/caches), loggers=Endpoint(id=loggers, url=http://192.168.0.9:8081/actuator/loggers), health=Endpoint(id=health, url=http://192.168.0.9:8081/actuator/health), env=Endpoint(id=env, url=http://192.168.0.9:8081/actuator/env), heapdump=Endpoint(id=heapdump, url=http://192.168.0.9:8081/actuator/heapdump), scheduledtasks=Endpoint(id=scheduledtasks, url=http://192.168.0.9:8081/actuator/scheduledtasks), mappings=Endpoint(id=mappings, url=http://192.168.0.9:8081/actuator/mappings), beans=Endpoint(id=beans, url=http://192.168.0.9:8081/actuator/beans), configprops=Endpoint(id=configprops, url=http://192.168.0.9:8081/actuator/configprops), threaddump=Endpoint(id=threaddump, url=http://192.168.0.9:8081/actuator/threaddump), metrics=Endpoint(id=metrics, url=http://192.168.0.9:8081/actuator/metrics), conditions=Endpoint(id=conditions, url=http://192.168.0.9:8081/actuator/conditions), shutdown=Endpoint(id=shutdown, url=http://192.168.0.9:8081/actuator/shutdown), info=Endpoint(id=info, url=http://192.168.0.9:8081/actuator/info)}), buildVersion=null, tags=Tags(values={}))

java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'peek' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.5.8.jar:3.5.8]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to GET info [DefaultWebClient]
Original Stack Trace:
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.8.jar:3.5.8]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

I have a small repro here:

https://github.com/Peksa/broken-sba

To repro:
1. Start with the default spring profile (Spring Boot Admin will listen on http://localhost:8080) - instance 1
2. Start another instance, but now with the spring profile `second`. This starts another Spring Boot Admin on http://localhost:8081, but registers to the first SBA instance.
3. Wait until the instance shows up in instance 1
4. Stop the instance 2
5. Observe that instance 2 never shows as offline, and eventually you see the above errors in standard out.

**Comment by ulischulte** [comment]
Hi @Peksa 
There might be something wrong with the way you configured your services since some configuration options significantly changed with Spring Boot 3 (please consider having a look at the migration guide). 
It seems like your services won't deregister since your configuration thinks your CloudPlatform will handle this. To test this, you could just test the following configuration within your service:

```
spring:
  application:
    name: should-be-down
  boot:
    admin:
      client:
        url: <someUrl>
        auto-deregistration: true
```

If this solves the issue, then your application is misconfigured in some way.

Regards,
Uli

**Comment by SteKoe** [comment]
Hi, we have made some changes in 3.1.6 regarding the mechanism of detecting status changes of instances. Could you please update your server to 3.1.6 and check if the issues still occur? TIA!
