### ISSUE TITLE
Can not build spring-boot-admin-server-ui project

### ISSUE THREAD

**Issue by khangnd2014** [codecentric/spring-boot-admin#272]
Hi,
I download source spring-boot-admin-server-ui project from git but cannot build it, I used nodejs v5.0.0. Please help me resolved this bug.

When run:
`npm run build`

`     @ ./~/css-loader?-minimize!./third-party/googlefonts/googlefonts.css 6:572-608
Child extract-text-webpack-plugin:
       [1] ./core/img/spring-logo.png 0 bytes [built] [failed]
       [3] ./core/img/platform-spring-boot.png 0 bytes [built] [failed]
        + 2 hidden modules

    ERROR in ./core/img/spring-logo.png
    Module parse failed: E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\core\img\spring-logo.png Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected character '�' (1:0)
        at Parser.pp$4.raise (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp$7.getTokenFromCode (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2756:10)
        at Parser.pp$7.readToken (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
        at Parser.pp$7.nextToken (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
        at Parser.parse (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:515:10)
        at Object.parse (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (E:\AngularExample\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)`

Thanks,

**Comment by joshiste** [comment]
So you found a solution to your problem? Do you want to tell me what the problem was?

**Comment by dipinpoovathel** [comment]
I am also facing the same problem.. I am using Node v6.9.2 and npm v4.0.5.
