### ISSUE TITLE
Error reading request, ignored

### ISSUE THREAD

**Issue by ahoehma** [codecentric/spring-boot-admin#2732]
## Spring Boot Admin Server information

- **Version**:
  3.1.5

- **Spring Boot version**:
  3.1.3

- **Configured Security**:
sba clients-with base auth
sba server with openid based login

- **Webflux or Servlet application**:
servlet

## Client information

- **Spring Boot versions**:
3.1.3

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
servlet

## Description

I see periodically this in my sba server log:

2023-09-01 08:59:09 http-nio-5000-exec-6 ERROR - [] - org.apache.coyote.http11.Http11NioProtocol:175 - Error reading request, ignored
java.lang.NullPointerException: Cannot invoke "org.apache.catalina.Context.decrementInProgressAsyncCount()" because "this.context" is null
        at org.apache.catalina.core.AsyncContextImpl.decrementInProgressAsyncCount(AsyncContextImpl.java:441)
        at org.apache.coyote.AsyncStateMachine.asyncPostProcess(AsyncStateMachine.java:295)
        at org.apache.coyote.AbstractProcessor.asyncPostProcess(AbstractProcessor.java:197)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:78)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SteKoe** [comment]
Hi @ahoehma,

we have found the exact same issue in Tomcat’s Bugzilla: https://bz.apache.org/bugzilla/show_bug.cgi?id=67235 It seems that they have introduced a bug in their newest versions, when using Server Send Events, which Spring Boot Admin utilizes. If you do not face any issues in regards to usability / stability of your SBA installation, we will keep track of the issue at tomcat and merge a fix asap.

Regards
SteKoe

**Comment by SteKoe** [comment]
Due to missing feedback, we are closing this issue. Feel free to reopen if this is still relevant.
