### ISSUE TITLE
Error : Could not evaluate condition on org.springframework.cloud.netflix.zuul.ZuulConfiguration#routeLocator due to com/netflix/zuul/ZuulFilter not found

### ISSUE THREAD

**Issue by sabarnath** [codecentric/spring-boot-admin#278]
```
2016-09-26 19:40:56.798  WARN 13960 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.ss.admin.SpringBootAdminUiApplication]; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/netflix/zuul/ZuulConfiguration
2016-09-26 19:40:56.806 ERROR 13960 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.ss.admin.SpringBootAdminUiApplication]; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/netflix/zuul/ZuulConfiguration
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:489) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:191) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:324) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:246) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at com.ss.admin.SpringBootAdminUiApplication.main(SpringBootAdminUiApplication.java:25) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [SpringBootAdminUI-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [SpringBootAdminUI-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [SpringBootAdminUI-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [SpringBootAdminUI-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/netflix/zuul/ZuulConfiguration
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_102]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_102]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_102]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_102]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_102]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_102]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_102]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_102]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89) ~[SpringBootAdminUI-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_102]
	at de.codecentric.boot.admin.config.AdminServerImportSelector.selectImports(AdminServerImportSelector.java:31) ~[spring-boot-admin-server-1.4.1.jar!/:1.4.1]
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:481) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	... 22 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.netflix.zuul.ZuulConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_102]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89) ~[SpringBootAdminUI-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_102]
	... 36 common frames omitted
```
I have been using following dependencies

spring boot parent version : 1.4.1.RELEASE
spring-boot-admin-server : 1.4.1
spring-boot-admin-server-ui : 1.4.1
spring-boot-admin-starter-client - 1.4.1

**Comment by joshiste** [comment]
Please show me your full pom.xml or the dependency tree.

**Comment by sabarnath** [comment]
Thank you for quick response , The Issue has been resolved due to jars
version  mismatch, after change into 1.3.0 of spring boot admin and client
working fine.

Thanks again!!!.

**Comment by sabarnath** [comment]
Thank you for quick response , The Issue has been resolved due to jars version  mismatch, after change into 1.3.0 of spring boot admin and client working fine.

Thanks again!!!.

**Comment by geduo83** [comment]
@sabarnath 你的提醒，解决了我的问题 thank you
