### ISSUE TITLE
Backoff retry delay in status check is increasing to hours rendering services offline

### ISSUE THREAD

**Issue by eugene-sadovsky** [codecentric/spring-boot-admin#2897]
## Spring Boot Admin Server information

- **Version**:
 3.1.4

- **Spring Boot version**:
  3.1.0

## Client information
- **Used discovery mechanism**:
  Consul

## Description
[Exponential back-off](https://github.com/codecentric/spring-boot-admin/blob/e634b20ffb734cba5ee831586478029b15910b0d/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/IntervalCheck.java#L87) delay  in `de.codecentric.boot.admin.server.services.IntervalCheck` is increasing to hours. I noticed that after I run SBA for 2+ weeks, previously registered services go offline for hours and then they become available again. Restarting SBA helps right away. This is always accompanied by the error message: ```Unexpected error in status-check: reactor.core.Exceptions$OverflowException: Could not emit tick NN due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)```
After some investigation it looks like this happens when [checkAllInstances](https://github.com/codecentric/spring-boot-admin/blob/e634b20ffb734cba5ee831586478029b15910b0d/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/IntervalCheck.java#L96) method times-out (takes longer to complete than the interval check) and it triggers a retry. The back-off interval keeps increasing with each failure during the life-time of the SBA and eventually grows to hours. I actually takes about 12+ retries, The situation improved by lowering `spring.boot.admin.timeout.health` to 3 seconds. By default health endpoint timeout is equal to `spring.boot.admin.status-interval` (10s).

Here's the [code snippet](https://gist.github.com/eugene-sadovsky/46e75836c017652cb03fb3f27cf06e9e) that reproduces this behavior. It will slow-down with each retry

**Comment by erikpetzold** [comment]
Hi @eugene-sadovsky ,

that the retry time increases is intendet behaviour. But you are right that the waitting time might get too high.
We introduced a new property for maxBackoff, so you can configure this on your own. The default maxBackoff for status check is now 60 seconds.

**Comment by eugene-sadovsky** [comment]
thank you for the quick response 🙇🏼

**Comment by eugene-sadovsky** [comment]
I think the main issue is that back-off time is never reset back to zero after successful retry. It will just saturate to `maxBackoff`  and stay like this for the lifetime of the process. This still solves my issue, thank you 👍🏼

**Comment by erikpetzold** [comment]
if this is really true that would be a bug in project reactor I think

**Comment by eugene-sadovsky** [comment]
yeah, this is the behavior I observed. You can reproduce it by running my gist, it closely resembles the code in `IntervalCheck`. It randomly simulates a timeout, then there may be few successful checks, then timeout again. With each retry delay becomes longer and never goes back to zero

**Comment by cdprete** [comment]
@erikpetzold was this solved somehow?

I observed exactly the same in version `3.5.5`:
```console
2025-10-20T23:17:44.197Z  WARN 1 --- [Zookeepers Monitoring] [     parallel-1] d.c.b.a.server.services.IntervalCheck    : Unexpected error in status-check
reactor.core.Exceptions$OverflowException: Could not emit tick 4391 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:251) ~[reactor-core-3.7.11.jar:3.7.11]
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:131) ~[reactor-core-3.7.11.jar:3.7.11]
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) ~[reactor-core-3.7.11.jar:3.7.11]
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) ~[reactor-core-3.7.11.jar:3.7.11]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by ulischulte** [comment]
We'll look into it.
