### ISSUE TITLE
Admin Health Endpoint throwing Invalid Char in Cookie value error

### ISSUE THREAD

**Issue by ankur-sharma-maersk** [codecentric/spring-boot-admin#3030]
## Spring Boot Admin Server information

- **Version**:
  2.6.7

- **Spring Boot version**:
2.6.7

- **Configured Security**:
  Basic Auth

- **Webflux or Servlet application**:
Servlet Application

## Client information

- **Spring Boot versions**:
 2.7.15

- **Used discovery mechanism**:
  self registration

- **Webflux or Servlet application**:
Servlet Application

## Description
From the last 7 days, one of the application in Prod environment started throwing error on health check in Spring Boot Admin Console as shown below. All other application are working fine and this application is working fine on lower environment(with same config). Because of which, Application remains in Offline mode in Spring Boot Admin console, but health check in Azure are working fine(showing application healthy). Spring boot Admin console checking the status every hour and sending notification to Microsoft teams.

Status changed to Up and then Offline with the below error(every hour):
`Cookie value contains an invalid char: \"; nested exception is java.lang.IllegalArgumentException: Cookie value contains an invalid char: \"`
![image](https://github.com/codecentric/spring-boot-admin/assets/54935467/ec93f610-dc14-41d8-af9d-34a34a7283b3)

Health Endpoint is working fine and return below response:
`{"status":"UP","components":{"db":{"status":"UP","details":{"database":"Microsoft SQL Server","validationQuery":"isValid()"}},"keyVault":{"status":"UP"},"ping":{"status":"UP"}}}`

**Comment by ankur-sharma-maersk** [comment]
![image](https://github.com/codecentric/spring-boot-admin/assets/54935467/9c040269-81cb-4740-adb5-b382a8b07880)

**Comment by ankur-sharma-maersk** [comment]
![image](https://github.com/codecentric/spring-boot-admin/assets/54935467/3ca62c02-075a-4e0e-8e9a-f12f6d7a15fc)

**Comment by ankur-sharma-maersk** [comment]
Error in Spring Boot Admin console - 

`2024-01-04T10:02:55.057354678Z: [INFO]  java.lang.IllegalArgumentException: Cookie value contains an invalid char: "
2024-01-04T10:02:55.057369378Z: [INFO]  	at io.netty.handler.codec.http.cookie.CookieEncoder.validateCookie(CookieEncoder.java:48) ~[netty-codec-http-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057373978Z: [INFO]  	at io.netty.handler.codec.http.cookie.ClientCookieEncoder.encode(ClientCookieEncoder.java:217) ~[netty-codec-http-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057377878Z: [INFO]  	at io.netty.handler.codec.http.cookie.ClientCookieEncoder.encode(ClientCookieEncoder.java:86) ~[netty-codec-http-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057382278Z: [INFO]  	at reactor.netty.http.client.HttpClientOperations.addCookie(HttpClientOperations.java:163) ~[reactor-netty-http-1.0.18.jar!/:1.0.18]
2024-01-04T10:02:55.057386578Z: [INFO]  	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:1.8.0_252]
2024-01-04T10:02:55.057390278Z: [INFO]  	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_252]
2024-01-04T10:02:55.057393878Z: [INFO]  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_252]
2024-01-04T10:02:55.057397779Z: [INFO]  	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[na:1.8.0_252]
2024-01-04T10:02:55.057401679Z: [INFO]  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272) ~[na:1.8.0_252]
2024-01-04T10:02:55.057405479Z: [INFO]  	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_252]
2024-01-04T10:02:55.057409479Z: [INFO]  	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_252]
2024-01-04T10:02:55.057413279Z: [INFO]  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_252]
2024-01-04T10:02:55.057417279Z: [INFO]  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_252]
2024-01-04T10:02:55.057421179Z: [INFO]  	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:1.8.0_252]
2024-01-04T10:02:55.057425079Z: [INFO]  	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:1.8.0_252]
2024-01-04T10:02:55.057429079Z: [INFO]  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_252]
2024-01-04T10:02:55.057436879Z: [INFO]  	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[na:1.8.0_252]
2024-01-04T10:02:55.057454179Z: [INFO]  	at org.springframework.http.client.reactive.ReactorClientHttpRequest.applyCookies(ReactorClientHttpRequest.java:134) ~[spring-web-5.3.19.jar!/:5.3.19]
2024-01-04T10:02:55.057458180Z: [INFO]  	at org.springframework.http.client.reactive.AbstractClientHttpRequest.lambda$null$0(AbstractClientHttpRequest.java:143) ~[spring-web-5.3.19.jar!/:5.3.19]
2024-01-04T10:02:55.057462680Z: [INFO]  	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49) ~[reactor-core-3.4.17.jar!/:3.4.17]
2024-01-04T10:02:55.057467280Z: [INFO]  	at reactor.core.publisher.Mono.subscribe(Mono.java:4400) [reactor-core-3.4.17.jar!/:3.4.17]
2024-01-04T10:02:55.057471180Z: [INFO]  	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:147) [reactor-core-3.4.17.jar!/:3.4.17]
2024-01-04T10:02:55.057475080Z: [INFO]  	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60) [reactor-core-3.4.17.jar!/:3.4.17]
2024-01-04T10:02:55.057479080Z: [INFO]  	at reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:81) [reactor-core-3.4.17.jar!/:3.4.17]
2024-01-04T10:02:55.057482980Z: [INFO]  	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.17.jar!/:3.4.17]
2024-01-04T10:02:55.057486680Z: [INFO]  	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:441) [reactor-netty-http-1.0.18.jar!/:1.0.18]
2024-01-04T10:02:55.057490380Z: [INFO]  	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677) [reactor-netty-core-1.0.18.jar!/:1.0.18]
2024-01-04T10:02:55.057493980Z: [INFO]  	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.run(DefaultPooledConnectionProvider.java:274) [reactor-netty-core-1.0.18.jar!/:1.0.18]
2024-01-04T10:02:55.057497780Z: [INFO]  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057501780Z: [INFO]  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057505780Z: [INFO]  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057510980Z: [INFO]  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057515180Z: [INFO]  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057520181Z: [INFO]  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.76.Final.jar!/:4.1.76.Final]
2024-01-04T10:02:55.057523881Z: [INFO]  	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]`

**Comment by erikpetzold** [comment]
Hi @ankur-sharma-maersk 
As the message is saying, your application sends a cookie with the http response. This cookie contains invalid characters in value.
In your first message you have shown the http response body, which is saying the application is up and everything is fine. There should also be cookies (sent in http header), please check these cookies/headers.
Spring Boot Admin Server also receives this invalid cookie and then has error.

**Comment by ankur-sharma-maersk** [comment]
We have checked and there was no cookie present in the header that's why it was confusing why we were getting this error. For now, we have added check to ignore the OFFLINE status in spring boot admin which is thrown in this case. So, we are only alerting or listening to UNKNOWN, UP, DOWN status.
