### ISSUE TITLE
Unable to build spring-boot-admin-server-ui

### ISSUE THREAD

**Issue by obeyler** [codecentric/spring-boot-admin#315]
Hello,
I'd like to add a column with link  provided by each client component

I use netbeans on a mac book, I try to build the ui to be able to customize it but I don't manage to build it. Is it an error or a bad config from my part ?
best regards and congratulation for your work.

```
--- exec-maven-plugin:1.4.0:exec (npm-test) @ spring-boot-admin-server-ui ---

> spring-boot-admin-server-ui@1.5.0 test /Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui
> karma start karma.conf.js

02 11 2016 23:07:28.880:ERROR [config]: Error in config file!
 TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1431:5)
    at phantomJSExePath (/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/node_modules/karma-phantomjs-launcher/index.js:19:12)
    at Object.<anonymous> (/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/node_modules/karma-phantomjs-launcher/index.js:104:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/karma.conf.js:30:13)
    at Object.parseConfig (/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/node_modules/karma/lib/config.js:377:5)
    at new Server (/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/node_modules/karma/lib/server.js:56:20)
    at Object.exports.run (/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/node_modules/karma/lib/cli.js:280:7)
    at Object.<anonymous> (/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/node_modules/karma/bin/karma:3:23)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! spring-boot-admin-server-ui@1.5.0 test: `karma start karma.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spring-boot-admin-server-ui@1.5.0 test script 'karma start karma.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spring-boot-admin-server-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start karma.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-boot-admin-server-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spring-boot-admin-server-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/npm-debug.log
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 38.285s
Finished at: Wed Nov 02 23:07:29 CET 2016
Final Memory: 16M/437M
------------------------------------------------------------------------
```

**Comment by joshiste** [comment]
can you attach the npm-debug.log?
Do you see any other messages such as
```
[launcher]: No binary for PhantomJS browser on your platform.
  Please, set "PHANTOMJS_BIN" env variable.
```
??

**Comment by obeyler** [comment]
Thanks for your help 
this is my npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle spring-boot-admin-server-ui@1.5.0~pretest: spring-boot-admin-server-ui@1.5.0
6 silly lifecycle spring-boot-admin-server-ui@1.5.0~pretest: no script for pretest, continuing
7 info lifecycle spring-boot-admin-server-ui@1.5.0~test: spring-boot-admin-server-ui@1.5.0
8 verbose lifecycle spring-boot-admin-server-ui@1.5.0~test: unsafe-perm in lifecycle true
9 verbose lifecycle spring-boot-admin-server-ui@1.5.0~test: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui/node_modules/.bin:/usr/local/bin/:/Applications/Utilities/phantomjs-2.1.1-macosx/bin/:/usr/local/lib/node_modules/npm/lib/install/:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle spring-boot-admin-server-ui@1.5.0~test: CWD: /Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui
11 silly lifecycle spring-boot-admin-server-ui@1.5.0~test: Args: [ '-c', 'karma start karma.conf.js' ]
12 silly lifecycle spring-boot-admin-server-ui@1.5.0~test: Returned: code: 1  signal: null
13 info lifecycle spring-boot-admin-server-ui@1.5.0~test: Failed to exec test script
14 verbose stack Error: spring-boot-admin-server-ui@1.5.0 test: `karma start karma.conf.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid spring-boot-admin-server-ui@1.5.0
16 verbose cwd /Users/olivier/Downloads/spring-boot-admin-master/spring-boot-admin-server-ui
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error spring-boot-admin-server-ui@1.5.0 test: `karma start karma.conf.js`
22 error Exit status 1
23 error Failed at the spring-boot-admin-server-ui@1.5.0 test script 'karma start karma.conf.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the spring-boot-admin-server-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     karma start karma.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs spring-boot-admin-server-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls spring-boot-admin-server-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by obeyler** [comment]
Note that node js and npm are already installed.
Could you mention in your comment PHANTOMJS_BIN env, could you give me the list of env variable need to well configure the project ?
Thanks

**Comment by obeyler** [comment]
I found the bug it is due to a bug on karma-phantomjs-launcher/index.js. It doesn't work well with mac sierra and try to evaluate the path like if it believes to be on a windows so it crashs on a null path

I find a workaround witch is not very clean as it works only for mac  users ... I removed the line for windows :-) `
at the end of this file you can find 

```
PhantomJSBrowser.prototype = {
  name: 'PhantomJS',

  DEFAULT_CMD: {
    linux: require('phantomjs-prebuilt').path,
    darwin: require('phantomjs-prebuilt').path,
    win32: phantomJSExePath()
  },
  ENV_CMD: 'PHANTOMJS_BIN'
}
```

replace it by 

```

PhantomJSBrowser.prototype = {
  name: 'PhantomJS',

  DEFAULT_CMD: {
    linux: require('phantomjs-prebuilt').path,
    darwin: require('phantomjs-prebuilt').path
  },
  ENV_CMD: 'PHANTOMJS_BIN'
}
```

**Comment by joshiste** [comment]
Since you found the problem outside of SBA I'm closing this issue. 
Did you raise an issue for karma-phantomjs-launcher?

**Comment by obeyler** [comment]
yes I've done
see https://github.com/karma-runner/karma-phantomjs-launcher/issues/138
thanks again you have done a very good application
