### ISSUE TITLE
Spring Boot Admin shows OFFLINE.

### ISSUE THREAD

**Issue by jacks808** [codecentric/spring-boot-admin#338]
Hi, I am a new bee of spring boot admin. I were add spring boot admin client to my api project follow the steps:
1. add maven dependency:
```    
        <!-- starter actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- spring boot admin client -->
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>1.4.1</version>
        </dependency>
```
2. set remote server address:
```
spring:
  boot:
    admin:
      url: http://10.94.66.193:9998
```

And, I start up api project, then I found a node in spring boot admin:
![image](https://cloud.githubusercontent.com/assets/1544433/20426890/1bbeb2bc-adbc-11e6-97b3-7b6a53ce0d0d.png)

BUT: the status of api project is `OFFLINE`.
Is there some wrong usage of my code?

**Comment by jacks808** [comment]
By the way, I were add spring boot admin itself to the application list by the same way like api project. And, it shows `UP` rather than `OFFLINE`

**Comment by jacks808** [comment]
And, I notice that `spring boot admin` server log output a connection refused. but the ip of my client is wrong, `spring boot admin` use 127.0.0.1 to connect client. 

more detail:

```

org.apache.http.conn.HttpHostConnectException: Connect to localhost:8088 [localhost/127.0.0.1] failed: 拒绝连接 (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158) ~[httpclient-4.5.2.jar!/:4.5.2]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.2.jar!/:4.5.2]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.2.jar!/:4.5.2]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.2.jar!/:4.5.2]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.2.jar!/:4.5.2]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.2.jar!/:4.5.2]

```

**Comment by jacks808** [comment]
I am not running `spring boot admin` and `api project` at same server.

**Comment by jacks808** [comment]
And finally, When i add client config to application.properties, the host of client is real ip.
