### ISSUE TITLE
spring-boot-admin-server-ui build is failing on Windows

### ISSUE THREAD

**Issue by dipinpoovathel** [codecentric/spring-boot-admin#363]
I am trying to build spring-boot-admin-server-ui and it is always failing. I am getting following error while building the UI using 'npm run build'. npm version is 4.0.5, node version is 6.9.2. I am using Windows 7 workstation.
```
Hash: f327a06cfa036df5a4d8
Version: webpack 1.13.3
Time: 29588ms
                                                        Asset       Size  Chunks             Chunk Names
                                      applications/module.css    3.29 kB       1  [emitted]  applications/module
                                              dependencies.js     324 kB       0  [emitted]  dependencies.js
                               applications-details/module.js    11.3 kB       2  [emitted]  applications-details/module
                                   applications-jmx/module.js    19.7 kB       3  [emitted]  applications-jmx/module
                                                      core.js     244 kB       4  [emitted]  core
                               applications-logfile/module.js    3.28 kB       5  [emitted]  applications-logfile/module
                               applications-threads/module.js    4.09 kB       6  [emitted]  applications-threads/module
                               applications-metrics/module.js    4.02 kB       7  [emitted]  applications-metrics/module
                                 applications-trace/module.js    2.18 kB       8  [emitted]  applications-trace/module
                               applications-logging/module.js    4.66 kB       9  [emitted]  applications-logging/module
                             applications-liquibase/module.js    4.24 kB      10  [emitted]  applications-liquibase/module
                           applications-environment/module.js    3.89 kB      11  [emitted]  applications-environment/module
                                applications-flyway/module.js    1.22 kB      12  [emitted]  applications-flyway/module
                                             events/module.js  564 bytes      13  [emitted]  events/module
                              applications-heapdump/module.js  574 bytes      14  [emitted]  applications-heapdump/module
                                              about/module.js  365 bytes      15  [emitted]  about/module
                              applications-details/module.css  375 bytes       2  [emitted]  applications-details/module
                              applications-logfile/module.css  306 bytes       5  [emitted]  applications-logfile/module
                                applications-trace/module.css    2.45 kB       8  [emitted]  applications-trace/module
                                       applications/module.js     177 kB       1  [emitted]  applications/module
                                                     core.css    22.1 kB       4  [emitted]  core
                                                   index.html    2.07 kB          [emitted]
                                             about\about.html       1 kB          [emitted]
   applications-details\views\templates\health-diskspace.html  422 bytes          [emitted]
                      applications-details\views\details.html    2.89 kB          [emitted]
applications-details\views\templates\health-configserver.html    1.02 kB          [emitted]
              applications-environment\views\environment.html    1.35 kB          [emitted]
      applications-details\views\templates\health-status.html    1.01 kB          [emitted]
                              applications-jmx\views\jmx.html     1.8 kB          [emitted]
                        applications-flyway\views\flyway.html    1.69 kB          [emitted]
                  applications-liquibase\views\liquibase.html  396 bytes          [emitted]
                      applications-logfile\views\logfile.html  567 bytes          [emitted]
                      applications-logging\views\logging.html    2.32 kB          [emitted]
                      applications-metrics\views\metrics.html    1.08 kB          [emitted]
                      applications-threads\views\threads.html  546 bytes          [emitted]
                      applications\views\application-nav.html    1.31 kB          [emitted]
                          applications-trace\views\trace.html  883 bytes          [emitted]
                    applications\views\applications-list.html    3.99 kB          [emitted]
                                           events\events.html    1.07 kB          [emitted]
   [0] multi dependencies.js 76 bytes {0} [built]
  **[14] ./core/img/spring-logo.png 0 bytes [built] [failed]**
  [22] ./third-party/bootstrap/js/bootstrap.js 61.9 kB {0} [built]
  [23] ./modules/applications-jmx/third-party/jolokia.js 33.2 kB {3} [built]
**[167] ./core/img/favicon.png 0 bytes [built] [failed]**
**[168] ./core/img/platform-spring-boot.png 0 bytes [built] [failed]**
**[169] ./modules/applications/img/error.png 0 bytes [built] [failed]**
**[170] ./modules/applications/img/ok.png 0 bytes [built] [failed]**
**[171] ./modules/applications/img/unknown.png 0 bytes [built] [failed]**
**[178] ./third-party/bootstrap/img/glyphicons-halflings-white.png 0 bytes [built] [failed]**
**[179] ./third-party/bootstrap/img/glyphicons-halflings.png 0 bytes [built] [failed]**
**[180] ./third-party/googlefonts/Montserrat-Bold.ttf 0 bytes [built] [failed]**
**[181] ./third-party/googlefonts/Montserrat-Regular.ttf 0 bytes [built] [failed]**
**[182] ./third-party/googlefonts/VarelaRound-Regular.ttf 0 bytes [built] [failed]**
    + 195 hidden modules

WARNING in dependencies.js from UglifyJs
Condition always true [./~/jquery/dist/jquery.js:10179,0]
Dropping unused variable arrayMode [./~/angular-ui-router/release/angular-ui-router.js:796,0]
Side effects in initialization of unused variable ignoreUpdate [./~/angular-ui-router/release/angular-ui-router.js:2040,0]
Side effects in initialization of unused variable inherited [./~/angular-ui-router/release/angular-ui-router.js:4002,0]
Dropping unused variable cfg [./~/angular-ui-router/release/angular-ui-router.js:922,15]
Dropping unused function indexBy [./~/angular-ui-router/release/angular-ui-router.js:166,0]
Dropping unused function pluck [./~/angular-ui-router/release/angular-ui-router.js:196,0]
Dropping unused variable $active [./third-party/bootstrap/js/bootstrap.js:703,0]
Dropping unused variable that [./third-party/bootstrap/js/bootstrap.js:887,0]
Dropping unused variable that [./third-party/bootstrap/js/bootstrap.js:958,0]
Dropping unused variable that [./third-party/bootstrap/js/bootstrap.js:1273,0]
Side effects in initialization of unused variable $element [./~/angular/angular.js:9552,0]
Dropping unreachable code [./~/angular/angular.js:20263,0]
Dropping unused variable expression [./~/angular/angular.js:15347,0]
Dropping unused function includes [./~/angular/angular.js:799,0]
Dropping unused function nodesetLinkingFn [./~/angular/angular.js:10162,0]
Dropping unused function directiveLinkingFn [./~/angular/angular.js:10169,0]

WARNING in applications/module.js from UglifyJs
Condition always true [./~/esprima/esprima.js:32,0]
Dropping unreachable code [./~/esprima/esprima.js:34,5]
Dropping side-effect-free statement [./~/js-yaml/lib/js-yaml/type/binary.js:1,0]
Dropping unused variable require [./~/js-yaml/lib/js-yaml/type/binary.js:1,0]
Dropping unused variable _require [./~/js-yaml/lib/js-yaml/type/binary.js:9,0]
Dropping side-effect-free statement [./~/js-yaml/lib/js-yaml/type/js/function.js:1,0]
Dropping unused variable require [./~/js-yaml/lib/js-yaml/type/js/function.js:1,0]
Dropping unused variable _require [./~/js-yaml/lib/js-yaml/type/js/function.js:14,0]
Side effects in initialization of unused variable TEXT_TOKENS [./~/linkifyjs/lib/linkify/core/parser.js:10,0]

WARNING in applications-jmx/module.js from UglifyJs
Condition always true [./modules/applications-jmx/third-party/jolokia.js:744,0]
Dropping unreachable code [./modules/applications-jmx/third-party/jolokia.js:749,0]

WARNING in core.js from UglifyJs
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always true [./~/es6-shim/es6-shim.js:15,0]
Dropping unreachable code [./~/es6-shim/es6-shim.js:18,3]
Condition always false [./~/es6-shim/es6-shim.js:95,0]
Condition always false [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./core/css/core.css:10,0]
Dropping unreachable code [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./core/css/core.css:12,0]
Side effects in initialization of unused variable update [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./core/css/core.css:7,0]
Condition always false [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./~/font-awesome/css/font-awesome.css:10,0]
Dropping unreachable code [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./~/font-awesome/css/font-awesome.css:12,0]
Side effects in initialization of unused variable update [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./~/font-awesome/css/font-awesome.css:7,0]
Condition always false [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./third-party/bootstrap/css/bootstrap.css:10,0]
Dropping unreachable code [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./third-party/bootstrap/css/bootstrap.css:12,0]
Side effects in initialization of unused variable update [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./third-party/bootstrap/css/bootstrap.css:7,0]
Condition always false [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./third-party/googlefonts/googlefonts.css:10,0]
Dropping unreachable code [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./third-party/googlefonts/googlefonts.css:12,0]
Side effects in initialization of unused variable update [./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader?-minimize!./third-party/googlefonts/googlefonts.css:7,0]

**ERROR in ./core/img/favicon.png
Module parse failed: C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\core\img\favicon.png Unexpected character'?' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '?' (1:0)
    at Parser.pp$4.raise (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./core/core.js 26:0-28**

ERROR in ./modules/applications/img/error.png
Module parse failed: C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\modules\applications\img\error.png Unexpected character '?' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '?' (1:0)
    at Parser.pp$4.raise (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\BootAdmin\spring-boot-admin-master\spring-boot-admin-server-ui\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./modules/applications/module.js 170:50-76
```

**Comment by joshiste** [comment]
There seems to be an error while copying the binary images and fonts. Unfortunately I don't own a Windows machine and I can't reproduce the error...,

**Comment by joshiste** [comment]
You're possbily hitting https://github.com/webpack/file-loader/issues/101

**Comment by joshiste** [comment]
Maybe I've spotted the error in using `/` as path separator. Could you try the build using the following webpack.config.js ? Please tell me if that works?
[webpack.config.js.gz](https://github.com/codecentric/spring-boot-admin/files/665801/webpack.config.js.gz)

**Comment by dipinpoovathel** [comment]
Tkanks @joshiste,  with that change the build is successful. I am not seeing the errors any more. But the images files are not copied in to dist directory. The .png files are showing as [2]  in the dist directory and in the third-part directory.  In think need to tune the query part of the loader

`        query: {
          name: 'third-party/[2]',
          regExp: '(third-party|node_modules)/(.+)'
        }
`
`        query: {
          name: '[2]',
          regExp: '(core|modules)/(.+)$'
        }
`

![image](https://cloud.githubusercontent.com/assets/24617792/21401358/b037473e-c779-11e6-883f-79ab9496f10a.png)

![image](https://cloud.githubusercontent.com/assets/24617792/21401371/c68b7a46-c779-11e6-8e69-3886872c456f.png)

**Comment by dipinpoovathel** [comment]
@joshiste with the following changes, I am able to build spring-boot-admin-server-ui.

`query: {
          name: 'third-party/[2]',
          regExp: '(third-party|node_modules)/(.+)'
        }`

is changed to 

`query: {
          name: 'third-party/[2]',
          regExp: '(third-party|node_modules)\(.+)'
        }`

and 

`query: {
          name: '[2]',
          regExp: '(core|modules)/(.+)$'
        }`

is changed to

`query: {
          name: '[2]',
          regExp: '(core|modules)\(.+)$'
        }`

Thanks a lot for all your support..

Just to summaries, to **build spring-boot-admin-server-ui in Windows**, update following loader configurations in **webpack.config.js**

`{`
        `test: /\.(jpg|png|gif|eot|svg|ttf|woff(2)?)(\?.*)?$/,`
        `include: /\/(third-party|node_modules)\//,`
        `loader: 'file',`
        `query: {
          name: 'third-party/[2]',
          regExp: '(third-party|node_modules)/(.+)'
        }`
`}`

to 

`{`
        `test: /\.(jpg|png|gif|eot|svg|ttf|woff(2)?)(\?.*)?$/,`
        `include: /(third-party|node_modules)/,`
        `loader: 'file',`
        `query: {
          name: 'third-party/[2]',
          regExp: '(third-party|node_modules)\(.+)'
        }`
      `}`

 **and**

`{`
        `test: /\.(jpg|png|gif)$/,`
        `include: /\/(core|modules)\//,`
        `loader: 'file',`
        `query: {
          name: '[2]',
          regExp: '(core|modules)/(.+)$'
        }`
      `}`

to 

`{`
        `test: /\.(jpg|png|gif)$/,`
        `include: /(core|modules)/,`
        `loader: 'file',`
        `query: {
          name: '[2]',
          regExp: '(core|modules)\(.+)$'
        }`
      `}`

**Comment by joshiste** [comment]
I reopened the issue and fixed the webpackconfig so that the ui should build on posix and windows systems.
