### ISSUE TITLE
Multiple registrations for the same service on the server

### ISSUE THREAD

**Issue by philsmart** [codecentric/spring-boot-admin#366]
I often see a single service being registered more than once on the admin server. They are then grouped together. If I remove both of them, only one returns, until at some point more than one is again added. Could this be fixed? or is this something I am doing wrong?
![admin-server-issue](https://cloud.githubusercontent.com/assets/16583275/21432124/fee556b2-c861-11e6-858d-0d57d22af637.png)

**Comment by joshiste** [comment]
Applications are identified by their health-url so for each unique url there will be an entry in the list.

In case you are using SBA Client:
 * If the same instance is registered twice please read throug your client application's log for the registration message appearing more than once and compare the used health-urls
 * The instances aren't removed on shutdown per default If you wish that the application deregisters autmatically set `spring.boot.admin.auto-deregistration=true`.

**Comment by philsmart** [comment]
OK, the hostname I blanked out is the same. The application was maybe restarted in this time (but the URL should have stayed the same). I will check the application log to see what it is registering as. Thanks for getting back to me.

**Comment by joshiste** [comment]
The service url is displayed in the list. Did you check that the health-url is the same too? Since the Id is a hash of the health url, and the ids differ in your screenshot the health-urls should too...

**Comment by philsmart** [comment]
Ah, now I see, one of them has the DNS name of the server, the other (as below, has it's IP address). Now I remember in the logs there are instances of exceptions relating to not being able to resolve the name of the server (will try to dig those out). So looks like a client issue, with the possibility of this being relating to the machines network settings or related to our network env. I will try to find the exception and paste it here for reference.


![image](https://cloud.githubusercontent.com/assets/16583275/21433263/16304282-c867-11e6-8119-1e3253475194.png)

**Comment by philsmart** [comment]
For completeness, this is the client error that leads to two registrations of the same service in the admin server, not sure specifically why it occurs only on some occasions:
`java.lang.IllegalArgumentException: <omitted>.ac.uk: <omitted>.ac.uk: unknown error
        at de.codecentric.boot.admin.config.AdminClientProperties.getHostAddress(AdminClientProperties.java:188)
        at de.codecentric.boot.admin.config.AdminClientProperties.getServiceUrl(AdminClientProperties.java:145)
        at de.codecentric.boot.admin.config.AdminClientProperties.getManagementUrl(AdminClientProperties.java:87)
        at de.codecentric.boot.admin.config.AdminClientProperties.getHealthUrl(AdminClientProperties.java:119)
        at de.codecentric.boot.admin.services.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:124)
        at de.codecentric.boot.admin.services.ApplicationRegistrator.register(ApplicationRegistrator.java:73)
        at de.codecentric.boot.admin.services.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:89)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: <omitted>.ac.uk: <omitted>.ac.uk: unknown error
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
        at de.codecentric.boot.admin.config.AdminClientProperties.getHostAddress(AdminClientProperties.java:186)
        ... 14 common frames omitted
Caused by: java.net.UnknownHostException:<omitted>.ac.uk: unknown error
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)`

**Comment by joshiste** [comment]
The InetAdress tries to resolve the address for your hostname... and fails.

You could set `server.address` to the address where your server is reachable so that the resolution for your hostname doesn't happen.

**Comment by philsmart** [comment]
Thanks for the update. I will try that.
