### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by hsoftxl** [codecentric/spring-boot-admin#384]
```
2017-01-12 15:04:04.997  INFO 1984 --- [           main] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=b3e0cf72, name=WELIAN-ADMIN-SERVER, managementUrl=http://USER-20160130KC:8000, healthUrl=http://USER-20160130KC:8000/health, serviceUrl=http://USER-20160130KC:8000] registered 
2017-01-12 15:04:09.019  WARN 1984 --- [           main] d.c.boot.admin.registry.StatusUpdater    : Couldn't retrieve status for Application [id=b3e0cf72, name=WELIAN-ADMIN-SERVER, managementUrl=http://USER-20160130KC:8000, healthUrl=http://USER-20160130KC:8000/health, serviceUrl=http://USER-20160130KC:8000]

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://USER-20160130KC:8000/health": Connect to USER-20160130KC:8000 [USER-20160130KC/192.168.1.167, USER-20160130KC/fe80:0:0:0:ad3a:9b29:ed99:b846%14, USER-20160130KC/fe80:0:0:0:ca4:3337:3f57:fe58%4, USER-20160130KC/2001:0:5ef5:79fb:ca4:3337:3f57:fe58] failed: Connection refused: connect; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to USER-20160130KC:8000 [USER-20160130KC/192.168.1.167, USER-20160130KC/fe80:0:0:0:ad3a:9b29:ed99:b846%14, USER-20160130KC/fe80:0:0:0:ca4:3337:3f57:fe58%4, USER-20160130KC/2001:0:5ef5:79fb:ca4:3337:3f57:fe58] failed: Connection refused: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:312)
	at de.codecentric.boot.admin.registry.StatusUpdater.queryStatus(StatusUpdater.java:78)
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:62)
	at de.codecentric.boot.admin.registry.StatusUpdateApplicationListener.onClientApplicationRegistered(StatusUpdateApplicationListener.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:350)
	at de.codecentric.boot.admin.registry.ApplicationRegistry.register(ApplicationRegistry.java:82)
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.register(ApplicationDiscoveryListener.java:113)
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:84)
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onInstanceRegistered(ApplicationDiscoveryListener.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:111)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at com.welian.cloud.admin.AdminServerApplication.main(AdminServerApplication.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to USER-20160130KC:8000 [USER-20160130KC/192.168.1.167, USER-20160130KC/fe80:0:0:0:ad3a:9b29:ed99:b846%14, USER-20160130KC/fe80:0:0:0:ca4:3337:3f57:fe58%4, USER-20160130KC/2001:0:5ef5:79fb:ca4:3337:3f57:fe58] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:89)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
	... 52 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 65 common frames omitted
```

**Comment by hsoftxl** [comment]
application.yml  

server:
  port: 8000

spring:
  application:
    name: welian-admin-server
  cloud:
    config:
      enabled: false
# tag::configuration-eureka[]
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: true       #为true时，可以启动，但报异常：Cannot execute request on any known server
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
# end::configuration-eureka[]

# tag::configuration-ui-hystrix[]
#spring.boot.admin.routes.endpoints: env,metrics,trace,dump,health,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream
# end::configuration-ui-hystrix[]

# tag::configuration-ui-turbine[]
#spring.boot.admin.turbine:
#  clusters: default
#  url: http://localhost:8989/turbine.stream
# end::configuration-ui-turbine[]

**Comment by joshiste** [comment]
It's a networking error. Make sure the admin server can reach your clients on the registered url.

**Comment by thanks-git** [comment]
@joshiste  Hi Can you help me look at the mistakes?
 java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
 Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET health [DefaultWebClient]
 Stack trace:

**Comment by thanks-git** [comment]
Hi Can you help me look at the mistakes? @joshiste  
 java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
 Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET health [DefaultWebClient]
 Stack trace:
