### ISSUE TITLE
Client registration fails if notification configuration is disabled, but configured as beans

### ISSUE THREAD

**Issue by rfelgent** [codecentric/spring-boot-admin#402]
Hello @joshiste ,

I think there is a misconfiguration between Java-Code and Config-Code considering notification settings.

I have a Java-Config with slack notification 

```
 @Autowired
    private Notifier delegate;

    @Bean
    public FilteringNotifier filteringNotifier () {
        return new FilteringNotifier(delegate);
    }

    @Bean
    @Primary
    public RemindingNotifier remindingNotifier () {
        RemindingNotifier remindingNotifier = new RemindingNotifier(filteringNotifier());
        remindingNotifier.setReminderPeriod(TimeUnit.MINUTES.toMillis(5));
        return remindingNotifier;
    }

    @Scheduled(fixedRate = 60_000L)
    public void remind () {
        remindingNotifier().sendReminders();
    }
```

My application-XXX.yml is configured for each stage: prod, uat, dev and so on.

For profile "prod" I set "spring.boot.admin.notify.slack.enabled=true". For the other profiles I want a deactivation of the notification mechanism at all. As slack is the only notification, I assumed to disable the whole notification mechanism by setting "spring.boot.admin.notify.slack.enabled=false".

The weired behaviour is that SBAP still wants to perform some "notification logic" what in turns breaks the whole client registration logic. SBAP fails to poll the actuator endpoints and my GUI looks broken. The registered client shows up with the "details" button, but has no "version" or "info" column. Furthermore, I get strange exception in the detail view of the corresponding registered client.

So in the end:

1) should we update the docu for this pitfall?
2) should SBA be smart enough to deactivate whole "notification mechanism", if there is no valid notifier implementation enabled
3) should my Java-Config be smarter? 
4) decouple client registration/client actuator endpoint polling from the notification mechanism (failing one should not influence the other!)

**Comment by rfelgent** [comment]
I am using version 1.4.2

**Comment by joshiste** [comment]
Do you have a stacktrace from the server?

**Comment by rfelgent** [comment]
here you go:

`2017-02-07 17:22:55.934 ERROR 24889 --- [http-nio-10000-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at de.codecentric.boot.admin.notify.filter.FilteringNotifier.notify(FilteringNotifier.java:52)
	at de.codecentric.boot.admin.notify.RemindingNotifier.notify(RemindingNotifier.java:44)
	at de.codecentric.boot.admin.notify.NotifierListener.onClientApplicationEvent(NotifierListener.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:349)
	at de.codecentric.boot.admin.registry.ApplicationRegistry.register(ApplicationRegistry.java:82)
	at de.codecentric.boot.admin.registry.web.RegistryController.register(RegistryController.java:57)
	at de.codecentric.boot.admin.registry.web.RegistryController$$FastClassBySpringCGLIB$$2753636d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinp`

**Comment by joshiste** [comment]
> decouple client registration/client actuator endpoint polling from the notification mechanism (failing one should not influence the other!)

correct.


If you set `spring.boot.admin.notify.slack.enabled=false` the bean for the slack notifier is not created and the delegate for the Filter notifier is null..

**Comment by rfelgent** [comment]
Can I assist you with an MR ?

**Comment by joshiste** [comment]
Hmm I'd rather tend to implement a assertion to the filteringNotifier that the delegate must not be null. And also let the FilteringNotifier extend AbstractEventNotifier

**Comment by rfelgent** [comment]
this in turn would force me to do a more complex java-config, right?

i like the "on/off" idea without much affecting the java-config for supporting @ActiveProfile.

my wish would be, that SBAP is more "graceful/silent" when i set "spring.boot.admin.notify.slack.enabled=false" although some notifier beans are registered via java config (just a user perspective!)

**Comment by joshiste** [comment]
We could also remove the `@ConditionalOnProperty(prefix = "spring.boot.admin.notify.slack", name = "enabled", matchIfMissing = true)` from the slackNotifier bean.

**Comment by joshiste** [comment]
> Can I assist you with an MR ?

sure. Help is always welcome.

**Comment by joshiste** [comment]
@rfelgent Are you working on a PR?

**Comment by rfelgent** [comment]
Hi @joshiste,

no, i am currently not working an a PR, als am on a vacation till next week.

I like your suggestion of changing/removing the ConditionalOnProperty! 
If you do not want to wait for a PR, feel free to change the Code yourself. :)

**Comment by joshiste** [comment]
cherry-picked c410be8 for 1.4.x
