### ISSUE TITLE
EnableDiscoveryClient with Zookeeper throws "Expected schema-specific part at index 5" when specifying a valid connection string 

### ISSUE THREAD

**Issue by afire007** [codecentric/spring-boot-admin#455]
Getting a strange error after following the guide using zookeeper as my discovery service to find spring apps hosted on my cluster that are connected to zookeeper.  One of the dependencies seems to be throwing back a "Expected scheme-specific part at index 5: http:" more than likely because its unable to parse out the connect string provided to it from my application.yml even though its a valid connection string.

While this issue does not prevent the application from working, nor does it prevent the application from finding spring applications on the cluster, im more curious as to why the stack trace below is being thrown when using the spring-cloud-zookeeper-discovery starter with this application.

application.yml
```yaml
PORT_ADMIN: 9084
ZK_HOST: localhost
ZK_PORT: 2181

server:
  port: ${PORT_ADMIN}
spring:
  application:
    name: zookeeper-admin
  cloud:
    config:
      enabled: false
    zookeeper:
      connect-string: ${ZK_HOST}:${ZK_PORT}
      discovery:
        metadata:
          management:
            context-path: /
          health:
            path: /health

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
```
Stack Trace:
```
java.lang.IllegalStateException: Could not create URI object: Expected scheme-specific part at index 5: http:
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:432) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at de.codecentric.boot.admin.discovery.DefaultServiceInstanceConverter.getManagementUrl(DefaultServiceInstanceConverter.java:105) ~[spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.DefaultServiceInstanceConverter.getHealthUrl(DefaultServiceInstanceConverter.java:92) ~[spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.DefaultServiceInstanceConverter.convert(DefaultServiceInstanceConverter.java:64) ~[spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.register(ApplicationDiscoveryListener.java:138) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:94) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discoverIfNeeded(ApplicationDiscoveryListener.java:85) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onApplicationEvent(ApplicationDiscoveryListener.java:80) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.cloud.zookeeper.discovery.ZookeeperServiceWatch.childEvent(ZookeeperServiceWatch.java:90) [spring-cloud-zookeeper-discovery-1.0.3.RELEASE.jar:1.0.3.RELEASE]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.10.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) [guava-18.0.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843) [curator-recipes-2.10.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: http:
	at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_60]
	at java.net.URI$Parser.failExpecting(URI.java:2854) ~[na:1.8.0_60]
	at java.net.URI$Parser.parse(URI.java:3057) ~[na:1.8.0_60]
	at java.net.URI.<init>(URI.java:673) ~[na:1.8.0_60]
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:428) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	... 34 common frames omitted

2017-05-16 13:37:29.129 ERROR 33676 --- [tor-TreeCache-0] d.c.b.a.d.ApplicationDiscoveryListener   : Couldn't register application for service DefaultServiceInstance(serviceId=ignite, host=0:0:0:0:0:0:0:1, port=47500, secure=false, metadata={})

java.lang.IllegalStateException: Could not create URI object: Expected scheme-specific part at index 5: http:
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:432) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at de.codecentric.boot.admin.discovery.DefaultServiceInstanceConverter.getManagementUrl(DefaultServiceInstanceConverter.java:105) ~[spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.DefaultServiceInstanceConverter.getHealthUrl(DefaultServiceInstanceConverter.java:92) ~[spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.DefaultServiceInstanceConverter.convert(DefaultServiceInstanceConverter.java:64) ~[spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.register(ApplicationDiscoveryListener.java:138) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:94) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discoverIfNeeded(ApplicationDiscoveryListener.java:85) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onApplicationEvent(ApplicationDiscoveryListener.java:80) [spring-boot-admin-server-1.5.0.jar:1.5.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.cloud.zookeeper.discovery.ZookeeperServiceWatch.childEvent(ZookeeperServiceWatch.java:90) [spring-cloud-zookeeper-discovery-1.0.3.RELEASE.jar:1.0.3.RELEASE]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.10.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) [guava-18.0.jar:na]
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71) [curator-recipes-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843) [curator-recipes-2.10.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: http:
	at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_60]
	at java.net.URI$Parser.failExpecting(URI.java:2854) ~[na:1.8.0_60]
	at java.net.URI$Parser.parse(URI.java:3057) ~[na:1.8.0_60]
	at java.net.URI.<init>(URI.java:673) ~[na:1.8.0_60]
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:428) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	... 34 common frames omitted
```

**Comment by joshiste** [comment]
could you please set the loglevel for  `de.codecentric.boot.admin.discovery.DefaultServiceInstanceConverter` to `DEBUG` and post the logging output please?

**Comment by joshiste** [comment]
closed due to missing feedback.
