### ISSUE TITLE
Spring-boot-admin access no response in Linux Tomcat

### ISSUE THREAD

**Issue by zhangjianbinJAVA** [codecentric/spring-boot-admin#492]
Hello, I'm deploying spring-boot-admin in Linux Tomcat because some of the addresses in the process are pull failures while pulling service information from the eureka,

Such as:
```
2017-07-07 18:42:09.250  WARN 176065 --- [freshExecutor-0] d.c.boot.admin.registry.StatusUpdater    : Couldn't retrieve status for Application [id=5a685ff2, name=SEARCH-SERVICE-LOCAL, managementUrl=http://10.12.128.157:8001, healthUrl=http://10.12.128.157:8001/health, serviceUrl=http://10.12.128.157:8001]

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://10.12.128.157:8001/health": Connect to 10.12.128.157:8001 [/10.12.128.157] failed: Connection timed out; nested exception is org.apache.http.conn.ConnectTimeoutException: Connect to 10.12.128.157:8001 [/10.12.128.157] failed: Connection timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:312)
	at de.codecentric.boot.admin.registry.StatusUpdater.queryStatus(StatusUpdater.java:78)
	at de.codecentric.boot.admin.registry.StatusUpdater.updateStatus(StatusUpdater.java:62)
	at de.codecentric.boot.admin.registry.StatusUpdateApplicationListener.onClientApplicationRegistered(StatusUpdateApplicationListener.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:350)
	at de.codecentric.boot.admin.registry.ApplicationRegistry.register(ApplicationRegistry.java:82)
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.register(ApplicationDiscoveryListener.java:113)
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discover(ApplicationDiscoveryListener.java:84)
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.discoverIfNeeded(ApplicationDiscoveryListener.java:75)
	at de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener.onApplicationEvent(ApplicationDiscoveryListener.java:70)
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.cloud.netflix.eureka.CloudEurekaClient.onCacheRefreshed(CloudEurekaClient.java:60)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:960)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1468)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1435)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 10.12.128.157:8001 [/10.12.128.157] failed: Connection timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:89)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
	... 40 common frames omitted
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 53 common frames omitted
```
But I don't think this should affect the startup of tomcat, but when Tomcat access is unresponsive;
The access address for this project is http://192.168.0.26:8010

The health of my visit to the project has been unresponsive:
[dev@hnc-server10 ~]$ curl  -v http://192.168.0.26:8010/health
```
* About to connect() to 192.168.0.26 port 8010 (#0)
*   Trying 192.168.0.26... connected
* Connected to 192.168.0.26 (192.168.0.26) port 8010 (#0)
> GET /health HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 192.168.0.26:8010
> Accept: */*
> 
```
No result,
I don't know what the reason is. Spring-boot-admin, if the client access error occurred during the startup, wouldn't spring-boot-admin be successful?
```
2017-07-07 17:34:56.237  INFO 26438 --- [freshExecutor-1] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=cf1689d4, name=PLATFORM-PASSPORT-SERVICE, managementUrl=http://192.168.0.52:8114, healthUrl=http://192.168.0.52:8114/health, serviceUrl=http://192.168.0.52:8114] registered 
2017-07-07 17:34:56.429  INFO 26438 --- [freshExecutor-1] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=c778c587, name=FLOW-SERVICE, managementUrl=http://192.168.0.26:8009, healthUrl=http://192.168.0.26:8009/health, serviceUrl=http://192.168.0.26:8009] registered 
2017-07-07 17:34:56.436  INFO 26438 --- [freshExecutor-1] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=72b53dcf, name=FLOW-SERVICE, managementUrl=http://192.168.0.34:8009, healthUrl=http://192.168.0.34:8009/health, serviceUrl=http://192.168.0.34:8009] registered 
2017-07-07 17:34:56.445  INFO 26438 --- [freshExecutor-1] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=2c217473, name=PLATFORM-ASSEMBLE-SERVICE, managementUrl=http://192.168.0.54:8115, healthUrl=http://192.168.0.54:8115/health, serviceUrl=http://192.168.0.54:8115] registered 
2017-07-07 17:34:56.454  INFO 26438 --- [freshExecutor-1] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=00be4a90, name=PLATFORM-ASSEMBLE-SERVICE, managementUrl=http://192.168.0.52:8115, healthUrl=http://192.168.0.52:8115/health, serviceUrl=http://192.168.0.52:8115] registered 
2017-07-07 17:34:56.462  INFO 26438 --- [freshExecutor-1] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=54262623, name=PASSPORT-SERVICE, managementUrl=http://192.168.0.52:8116, healthUrl=http://192.168.0.52:8116/health, serviceUrl=http://192.168.0.52:8116] registered 
2017-07-07 17:34:56.689  INFO 26438 --- [freshExecutor-1] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=051666a0, name=PASSPORT-SERVICE, managementUrl=http://192.168.0.54:8116, healthUrl=http://192.168.0.54:8116/health, serviceUrl=http://192.168.0.54:8116] registered 
2017-07-07 17:38:50.829  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 17:43:50.830  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 17:48:50.831  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 17:53:50.831  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 17:58:50.832  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:03:50.833  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:08:50.833  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:13:50.834  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:18:50.835  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:23:50.836  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:28:50.836  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:33:50.837  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:38:50.838  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:43:50.838  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:48:50.839  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-07-07 18:53:50.840  INFO 26438 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
```
The project has stayed in this state, and Tomcat has been unable to access it

**Comment by joshiste** [comment]
Basically you're telling (or at least your exception is), that your health endpoint of one of your services is not reachable. (also your failed curl is). This doesn't affect the startup of spring boot admin.

**Comment by zhangjianbinJAVA** [comment]
I think so, but Tomcat cannot access any of the request paths, and there are no successful strings in the Tomcat boot process
Such as:
FrameworkServlet 'dispatcherServlet': initialization started
 FrameworkServlet 'dispatcherServlet': initialization completed in 29 ms

I've never seen this information, so I can't access the request path in tomcat anyway;

 d.c.b.a.registry.ApplicationRegistry     : New Application Application

 I want to ask, spring boot admin when loading the Application client, if you don't finish loading, has no such information, or some Application can't access the client's state of health, tomcat startup is not complete it, may be the reason

**Comment by jprateekvmware** [comment]
+1
