### ISSUE TITLE
statusInfo must not be null!

### ISSUE THREAD

**Issue by junegod** [codecentric/spring-boot-admin#499]
spring boot admin version 1.5.2
```java
java.lang.IllegalArgumentException: statusInfo must not be null!
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at de.codecentric.boot.admin.model.Application.<init>(Application.java:61)
	at de.codecentric.boot.admin.model.Application$Builder.build(Application.java:159)
	at de.codecentric.boot.admin.registry.web.RegistryController.register(RegistryController.java:59)
	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)

```

**Comment by junegod** [comment]
client send info
Application [id=null, name=alpha-user, managementUrl=http://bogon:8081, healthUrl=http://bogon:8081/health, serviceUrl=http://bogon:8081]

client Application fields
```java
public class Application {
	private final String name;
	private final String managementUrl;
	private final String healthUrl;
	private final String serviceUrl;
	private final Map<String, String> metadata;
```

**Comment by joshiste** [comment]
The spring boot admin server relies on the jackson2 object mapper. Did you configure any other library for the json deserialization? Please provide a sample project to reproduce the issue.

**Comment by junegod** [comment]
my admin server project default use fastjson
```java
@Bean
    @ConditionalOnMissingBean(AbstractGenericHttpMessageConverter.class)
    public FastJsonHttpMessageConverter4 fastJsonHttpMessageConverters() {
        FastJsonHttpMessageConverter4 fastConverter = new FastJsonHttpMessageConverter4();

        FastJsonConfig fastJsonConfig = new FastJsonConfig();
        fastJsonConfig.setSerializerFeatures(
                SerializerFeature.PrettyFormat,
                SerializerFeature.WriteMapNullValue,
                SerializerFeature.DisableCircularReferenceDetect);
        fastConverter.setFastJsonConfig(fastJsonConfig);
        return fastConverter;
    }
```
I change to jackson2
```java
@Bean
    public AbstractGenericHttpMessageConverter mappingJackson2HttpMessageConverter(
            ObjectMapper objectMapper) {
        return new MappingJackson2HttpMessageConverter(objectMapper);
    }
```
admin client use fastjson

**Comment by joshiste** [comment]
Afaik the messageconverter should be configured using a WebConfigurer

**Comment by junegod** [comment]
Get it ! 
```java
@EnableDiscoveryClient
@EnableAdminServer
@EnableHystrixDashboard
@EnableConfigServer
@EnableEurekaServer
@SpringBootApplication(exclude = DataSourceAutoConfiguration.class)
public class AlphaRegistryApp extends WebMvcConfigurerAdapter implements ApplicationContextAware {

    private ApplicationContext applicationContext;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) {
        this.applicationContext = applicationContext;
    }

    @Bean
    public AbstractGenericHttpMessageConverter mappingJackson2HttpMessageConverter() {
        ObjectMapper objectMapper = Jackson2ObjectMapperBuilder.json()
                .applicationContext(this.applicationContext).build();
        return new MappingJackson2HttpMessageConverter(objectMapper);
    }

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        super.configureMessageConverters(converters);
        converters.add(mappingJackson2HttpMessageConverter());
    }

    public static void main(String[] args) {
        new SpringApplicationBuilder(AlphaRegistryApp.class).web(true).run(args);
    }

}

```
