### ISSUE TITLE
Unable to start spring boot with admin version 1.5.1

### ISSUE THREAD

**Issue by Japca** [codecentric/spring-boot-admin#508]
We have a problem to start spring boot app with admin version 1.5.0+ Please help.
With version 1.5.0 I'm able to start. I think problem appear after you solved this issue
https://github.com/codecentric/spring-boot-admin/commit/77767bff3e45d8656bbf90c9449f0dbdcd33512d

I added dependency tree at the bottom
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1589)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBe`anFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.onsemi.middleware.distribution.v2.config.Application.main(Application.java:52)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:617)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.isHandler(RequestMappingHandlerMapping.java:173)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:213)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:184)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1648)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1585)
	... 14 common frames omitted
```

Here is dependency tree
```
[INFO] +- org.springframework.cloud:spring-cloud-starter-consul-all:jar:1.1.2.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-consul-bus:jar:1.1.2.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-starter-consul:jar:1.1.2.RELEASE:compile
[INFO] |  |  |  +- org.springframework.cloud:spring-cloud-consul-core:jar:1.1.2.RELEASE:compile
[INFO] |  |  |  +- com.ecwid.consul:consul-api:jar:1.1.11:compile
[INFO] |  |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-consul-binder:jar:1.1.2.RELEASE:compile
[INFO] |  |  |  \- org.springframework.cloud:spring-cloud-stream:jar:1.1.0.RELEASE:compile
[INFO] |  |  |     +- org.springframework.boot:spring-boot-starter-validation:jar:1.4.3.RELEASE:compile
[INFO] |  |  |     +- org.springframework:spring-messaging:jar:4.3.5.RELEASE:compile
[INFO] |  |  |     +- org.springframework.integration:spring-integration-jmx:jar:4.3.6.RELEASE:compile
[INFO] |  |  |     +- org.springframework:spring-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  |  |     |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:compile
[INFO] |  |  |     |     \- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  |  |     \- org.springframework.integration:spring-integration-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-bus:jar:1.2.1.RELEASE:compile
[INFO] |  |     \- org.springframework.integration:spring-integration-core:jar:4.3.6.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-consul-config:jar:1.1.2.RELEASE:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-consul-config:jar:1.1.2.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-starter-consul-discovery:jar:1.1.2.RELEASE:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-consul-discovery:jar:1.1.2.RELEASE:compile
[INFO] |     \- org.springframework.cloud:spring-cloud-starter-ribbon:jar:1.2.4.RELEASE:compile
[INFO] |        +- org.springframework.retry:spring-retry:jar:1.1.5.RELEASE:compile
[INFO] |        +- org.springframework.cloud:spring-cloud-starter:jar:1.1.7.RELEASE:compile
[INFO] |        |  \- org.springframework.security:spring-security-rsa:jar:1.0.3.RELEASE:compile
[INFO] |        |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.55:compile
[INFO] |        |        \- org.bouncycastle:bcprov-jdk15on:jar:1.55:compile
[INFO] |        +- org.springframework.cloud:spring-cloud-starter-archaius:jar:1.2.4.RELEASE:compile
[INFO] |        +- com.netflix.ribbon:ribbon:jar:2.2.0:compile
[INFO] |        |  +- com.netflix.ribbon:ribbon-transport:jar:2.2.0:runtime
[INFO] |        |  |  +- io.reactivex:rxnetty-contexts:jar:0.4.9:runtime
[INFO] |        |  |  \- io.reactivex:rxnetty-servo:jar:0.4.9:runtime
[INFO] |        |  +- javax.inject:javax.inject:jar:1:runtime
[INFO] |        |  \- io.reactivex:rxnetty:jar:0.4.9:runtime
[INFO] |        |     +- io.netty:netty-codec-http:jar:4.0.27.Final:runtime
[INFO] |        |     |  +- io.netty:netty-codec:jar:4.0.27.Final:runtime
[INFO] |        |     |  \- io.netty:netty-handler:jar:4.0.27.Final:runtime
[INFO] |        |     \- io.netty:netty-transport-native-epoll:jar:4.0.27.Final:runtime
[INFO] |        |        +- io.netty:netty-common:jar:4.0.27.Final:runtime
[INFO] |        |        +- io.netty:netty-buffer:jar:4.0.27.Final:runtime
[INFO] |        |        \- io.netty:netty-transport:jar:4.0.27.Final:runtime
[INFO] |        +- com.netflix.ribbon:ribbon-core:jar:2.2.0:compile
[INFO] |        |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |        +- com.netflix.ribbon:ribbon-httpclient:jar:2.2.0:compile
[INFO] |        |  +- com.sun.jersey:jersey-client:jar:1.19.1:runtime
[INFO] |        |  |  \- com.sun.jersey:jersey-core:jar:1.19.1:runtime
[INFO] |        |  |     \- javax.ws.rs:jsr311-api:jar:1.1.1:runtime
[INFO] |        |  \- com.sun.jersey.contribs:jersey-apache-client4:jar:1.19.1:runtime
[INFO] |        \- com.netflix.ribbon:ribbon-loadbalancer:jar:2.2.0:compile
[INFO] |           \- com.netflix.netflix-commons:netflix-statistics:jar:0.1.1:runtime
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.4.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.4.3.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.4.3.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.4.3.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.4.3.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.8:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.1.8:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.22:compile
[INFO] |  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.22:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.4.3.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.6:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.6:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.6:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.5:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.5:compile
[INFO] |  +- org.springframework:spring-web:jar:4.3.5.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.3.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:4.3.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.3.5.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:4.3.5.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:1.4.3.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-actuator:jar:1.4.3.RELEASE:compile
[INFO] +- de.codecentric:spring-boot-admin-server:jar:1.5.2:compile
[INFO] |  +- com.netflix.zuul:zuul-core:jar:1.3.0:compile
[INFO] |  |  +- com.netflix.archaius:archaius-core:jar:0.7.4:compile
[INFO] |  |  |  +- com.google.code.findbugs:jsr305:jar:3.0.1:runtime
[INFO] |  |  |  \- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |  |  +- com.netflix.servo:servo-core:jar:0.10.1:runtime
[INFO] |  |  |  \- com.netflix.servo:servo-internal:jar:0.10.1:runtime
[INFO] |  |  \- com.netflix.netflix-commons:netflix-commons-util:jar:0.1.1:runtime
[INFO] |  +- com.netflix.hystrix:hystrix-core:jar:1.5.6:compile
[INFO] |  |  +- io.reactivex:rxjava:jar:1.1.10:compile
[INFO] |  |  \- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:1.2.4.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-context:jar:1.1.7.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:4.1.4.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-commons:jar:1.1.7.RELEASE:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |     \- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] +- de.codecentric:spring-boot-admin-server-ui:jar:1.5.2:compile
[INFO] +- org.springframework.boot:spring-boot-configuration-processor:jar:1.4.3.RELEASE:compile
[INFO] |  +- org.json:json:jar:20140107:compile
[INFO] |  \- org.springframework:spring-core:jar:4.3.5.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-jdbc:jar:1.4.3.RELEASE:compile
[INFO] |  +- org.apache.tomcat:tomcat-jdbc:jar:8.5.6:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-juli:jar:8.5.6:compile
[INFO] |  \- org.springframework:spring-jdbc:jar:4.3.5.RELEASE:compile
[INFO] |     \- org.springframework:spring-tx:jar:4.3.5.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.4.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:1.4.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:1.4.3.RELEASE:compile
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.2.0:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.2.1:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.1:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.3.0:compile
[INFO] |  \- org.springframework:spring-test:jar:4.3.5.RELEASE:compile
[INFO] +- com.onsemi.middleware.cloud:mdw-CloudUtils:jar:0.0.6:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-data-jpa:jar:1.4.3.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-aop:jar:1.4.3.RELEASE:compile
[INFO] |  |  |  \- org.aspectj:aspectjweaver:jar:1.8.9:compile
[INFO] |  |  +- org.hibernate:hibernate-core:jar:5.0.11.Final:compile
[INFO] |  |  |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] |  |  |  +- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO] |  |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  |  +- org.jboss:jandex:jar:2.0.0.Final:compile
[INFO] |  |  |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  |  |  \- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:compile
[INFO] |  |  +- org.hibernate:hibernate-entitymanager:jar:5.0.11.Final:compile
[INFO] |  |  +- javax.transaction:javax.transaction-api:jar:1.2:compile
[INFO] |  |  +- org.springframework.data:spring-data-jpa:jar:1.10.6.RELEASE:compile
[INFO] |  |  |  +- org.springframework.data:spring-data-commons:jar:1.12.6.RELEASE:compile
[INFO] |  |  |  \- org.springframework:spring-orm:jar:4.3.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-aspects:jar:4.3.5.RELEASE:compile
[INFO] |  \- com.onsemi.middleware:UECache:jar:2.2.3:compile
[INFO] |     +- com.hazelcast:hazelcast-all:jar:3.6:compile
[INFO] |     +- com.oracle:ojdbc7:jar:12.1.0.2.0:compile
[INFO] |     +- org.jgroups:jgroups:jar:3.4.4.Final:compile
[INFO] |     +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |     +- org.reflections:reflections:jar:0.9.9-RC1:compile
[INFO] |     \- jstl:jstl:jar:1.2:compile
[INFO] +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] +- org.aspectj:aspectjrt:jar:1.6.9:compile
[INFO] +- org.aspectj:aspectjtools:jar:1.6.9:compile
[INFO] +- net.bull.javamelody:javamelody-core:jar:1.67.0:compile
[INFO] |  \- org.jrobin:jrobin:jar:1.5.9:compile
[INFO] +- com.onsemi.middleware:mdw-dal-lite:jar:1.2.2:compile
[INFO] |  \- com.onsemi.middleware:jdbc-mapper:jar:1.0:compile
[INFO] +- com.onsemi.middleware:mdw-PGPToolkit:jar:1.6:compile
[INFO] |  +- com.onsemi.middleware:mdw-UtilityPack:jar:1.2:compile
[INFO] |  |  +- com.onsemi.middleware.uelibs:stcjcs:jar:1.0:compile
[INFO] |  |  \- com.onsemi.middleware:mdw-Messaging:jar:1.0:compile
[INFO] |  +- org.bouncycastle:bcpg-jdk16:jar:1.46:compile
[INFO] |  |  \- org.bouncycastle:bcprov-jdk16:jar:1.46:compile
[INFO] |  \- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |     \- commons-pool:commons-pool:jar:1.6:compile
[INFO] +- com.onsemi.middleware:SFTPUtil:jar:1.2:compile
[INFO] |  +- apache-vfs:commons-vfs:jar:1.0:compile
[INFO] |  \- com.jcraft:jsch:jar:0.1.532-MDW:compile
[INFO] +- com.onsemi.middleware:loggingDispatcher:jar:2.3.1:compile
[INFO] |  +- org.hsqldb:hsqldb:jar:2.3.3:compile
[INFO] |  \- org.springframework:spring-context:jar:4.3.5.RELEASE:compile
[INFO] +- com.onsemi.middleware:UECommon:jar:1.0.0-BUILD-SNAPSHOT:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.22:compile
[INFO] |  +- log4j:log4j:jar:1.2.17:runtime
[INFO] |  +- joda-time:joda-time:jar:2.9.6:compile
[INFO] |  +- com.onsemi.middleware:UEMonitor:jar:1.1.0:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.3.1:compile
[INFO] |  +- com.onsemi.middleware:mdw-client:jar:1.1:compile
[INFO] |  |  \- net.sf:jargs:jar:1.0:compile
[INFO] |  +- com.microsoft.sqlserver:sqljdbc4:jar:4.0:compile
[INFO] |  +- mysql:mysql-connector-java:jar:5.1.40:compile
[INFO] |  +- com.ibm.db2:db2jcc:jar:9.1:compile
[INFO] |  +- com.ibm.db2:db2jcc-license:jar:9.1:compile
[INFO] |  +- net.sf.jt400:jt400:jar:8.6:compile
[INFO] |  +- net.sourceforge.jtds:jtds:jar:1.3.1:compile
[INFO] |  +- commons-net:commons-net:jar:1.4.1:compile
[INFO] |  |  \- oro:oro:jar:2.0.8:compile
[INFO] |  +- com.oracle.weblogic:wljmsclient:jar:10.3.3.0:compile
[INFO] |  +- com.oracle.weblogic:wlthint3client:jar:10.3.3.0:compile
[INFO] |  +- org.apache.activemq:activemq-client:jar:5.13.4:compile
[INFO] |  |  +- org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1:compile
[INFO] |  |  +- org.fusesource.hawtbuf:hawtbuf:jar:1.11:compile
[INFO] |  |  \- org.apache.geronimo.specs:geronimo-j2ee-management_1.1_spec:jar:1.0.1:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.3:compile
[INFO] |  +- com.lowagie:itext:jar:2.1.7:compile
[INFO] |  +- org.apache.commons:commons-vfs2:jar:2.0:compile
[INFO] |  |  +- org.apache.maven.scm:maven-scm-api:jar:1.4:compile
[INFO] |  |  |  \- org.codehaus.plexus:plexus-utils:jar:1.5.6:compile
[INFO] |  |  \- org.apache.maven.scm:maven-scm-provider-svnexe:jar:1.4:compile
[INFO] |  |     +- org.apache.maven.scm:maven-scm-provider-svn-commons:jar:1.4:compile
[INFO] |  |     \- regexp:regexp:jar:1.3:compile
[INFO] |  +- jcifs:jcifs:jar:1.3.17:compile
[INFO] |  +- extweb-lib:extweb-mail:jar:1.3:compile
[INFO] |  +- com.onsemi.middleware.uelibs:ArchiveUtilityInterf:jar:1.1.0:compile
[INFO] |  \- com.oracle:rdb:jar:73.10:compile
[INFO] +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] +- com.oracle:ojdbc14:jar:10.2.0.2.0:compile
[INFO] +- javax.mail:mail:jar:1.5.0-b01:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- commons-io:commons-io:jar:1.3.1:compile
[INFO] +- commons-httpclient:commons-httpclient:jar:3.0:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.0.3:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- com.mchange:c3p0:jar:0.9.5.2:compile
[INFO] |  \- com.mchange:mchange-commons-java:jar:0.2.11:compile
[INFO] +- org.mockftpserver:MockFtpServer:jar:2.7.1:test
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.22:compile
[INFO] +- com.google.guava:guava:jar:19.0:compile
[INFO] +- pl.pragmatists:JUnitParams:jar:1.1.0:test
[INFO] \- org.assertj:assertj-core:jar:3.8.0:test
```

**Comment by joshiste** [comment]
For spring boot admin 1.5.x you need to use spring boot 1.5. You are using 1.4.x.
