### ISSUE TITLE
help me! IllegalStateException: service-base-url must be set when deployed to servlet-container

### ISSUE THREAD

**Issue by coison** [codecentric/spring-boot-admin#526]
Hi @joshiste excuse me,
When I was using SBA, I ran into the following problem.

- spring boot version:1.5.6.RELEASE
- spring boot admin:1.5.3

The boot server set properties:
````
server:
  port: 8761
  address: localhost
````
The SBA server set properties:
````
spring:
  boot:
    admin:
      username: ${security.user.name}
      password: ${security.user.password}
      url: http://${server.address}:${server.port}${spring.boot.admin.context-path}  
      discovery:
        enabled: true  
      monitor:
        period: 10000  
      client:
        prefer-ip: true 
        enabled: true
        name:  @project.name@
        metadata:
          user.name: "${security.user.name}"  
          user.password: "${security.user.password}"
      auto-registration: true  
      register-once: true
      context-path: /manage
````
Application.java
````
@Configuration
@EnableAutoConfiguration
@EnableAdminServer
public class ManageApplication extends SpringBootServletInitializer {

    private static final Logger logger = LoggerFactory.getLogger(ManageApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(ManageApplication.class, args);
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        logger.info("application running...");
        return application;
    }
}
````
pom.xml
````
        <packaging>war</packaging>
       
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
````

Here is the exception：
````
java.lang.IllegalStateException: service-base-url must be set when deployed to servlet-container
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceUrl(DefaultApplicationFactory.java:68) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getManagementUrl(DefaultApplicationFactory.java:95) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:115) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:49) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:140) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:65) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
	at de.codecentric.boot.admin.client.registration.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:80) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Disconnected from the target VM, address: '127.0.0.1:62681', transport: 'socket'
````

````
 protected String getServiceUrl() {
        if (client.getServiceUrl() != null) {
            return UriComponentsBuilder.fromUriString(client.getServiceUrl()).toUriString();
        }

        String baseUrl = client.getServiceBaseUrl();
        if (getLocalServerPort() == null && StringUtils.isEmpty(baseUrl)) {
            throw new IllegalStateException("service-base-url must be set when deployed to servlet-container");
        }

        UriComponentsBuilder builder;
        if (!StringUtils.isEmpty(baseUrl)) {
            builder = UriComponentsBuilder.fromUriString(baseUrl);
        } else {
            builder = UriComponentsBuilder.newInstance()
                                          .scheme(getScheme(server.getSsl()))
                                          .host(getServiceHost())
                                          .port(getLocalServerPort());
        }

        return builder.path("/").path(servletContext.getContextPath()).path("/").toUriString();
    }
````

I don't think `AdminClientProperties.java` can get the configuration information of the `application.yml` file in 'tomcat', but I don't know why.

Please help me, Thank you very much!

**Comment by joshiste** [comment]
when running as war the server.port and adress is not taken into account by sproing boot. So you need to then the `spring.boot.admin.base-url` to the address where your tomcat is running

**Comment by coison** [comment]
Thank you very much for the perfect solution to my problem, but I set `spring.boot.admin.cient.service-base-url` instead of `spring.boot.admin.service-base-url` because I didn't find it! Is there any problem with this setting?

**Comment by coison** [comment]
I've tried this property, but it failed. I guess I don't have `mvn clean`. That's my problem. I'm so sorry, but thank you very much!
