### ISSUE TITLE
build error while installing yar

### ISSUE THREAD

**Issue by dhruv-bansal** [codecentric/spring-boot-admin#538]
I am getting following error about the directory and the directory exists
```
java.io
.IOException: Cannot 
run program "yarn" (in directory "/Users/B0095258/Documents/airteldata/code/spring-boot-admin/spring-boot-admin/spring-boot-admin-server-ui"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spring Boot Admin .................................. SUCCESS [05:05 min]
[INFO] spring-boot-admin-server ........................... SUCCESS [08:09 min]
[INFO] spring-boot-admin-server-ui ........................ FAILURE [ 20.875 s]
[INFO] spring-boot-admin-server-ui-activiti ............... SKIPPED
[INFO] spring-boot-admin-server-ui-hystrix ................ SKIPPED
[INFO] spring-boot-admin-server-ui-turbine ................ SKIPPED
[INFO] spring-boot-admin-server-ui-login .................. SKIPPED
[INFO] spring-boot-admin-starter-client ................... SKIPPED
[INFO] Spring Boot Admin Samples .......................... SKIPPED
[INFO] spring-boot-admin-sample ........................... SKIPPED
[INFO] spring-boot-admin-sample-war ....................... SKIPPED
[INFO] spring-boot-admin-sample-eureka .................... SKIPPED
[INFO] spring-boot-admin-sample-consul .................... SKIPPED
[INFO] spring-boot-admin-sample-zookeeper ................. SKIPPED
[INFO] spring-boot-admin-sample-hazelcast ................. SKIPPED
[INFO] Spring Boot Admin Docs ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:18 min
[INFO] Finished at: 2017-09-02T22:55:10+05:30
[INFO] Final Memory: 56M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (yarn-install) on project spring-boot-admin-server-ui: Command execution failed.: Cannot run program "yarn" (in directory "/Users/B0095258/Documents/airteldata/code/spring-boot-admin/spring-boot-admin/spring-boot-admin-server-ui"): error=2, No such file or directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-boot-admin-server-ui
sh-3.2# yarn
sh: yarn: command not found

```

**Comment by joshiste** [comment]
You need to install [yarn](https://yarnpkg.com/lang/en/) on your machine for building the UI
