### ISSUE TITLE
error reported during "mvn clean package": service-base-url must be set when deployed to servlet-container...

### ISSUE THREAD

**Issue by xujijun** [codecentric/spring-boot-admin#555]
```
2017-09-14 15:17:06,701:ERROR registrationTask1 (TaskUtils.java:95) - Unexpected error occurred in scheduled task.
 java.lang.IllegalStateException: service-base-url must be set when deployed to servlet-container
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceUrl(DefaultApplicationFactory.java:68) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getManagementUrl(DefaultApplicationFactory.java:95) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:115) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
        at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:49) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
        at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:140) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
        at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:65) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
        at de.codecentric.boot.admin.client.registration.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:80) ~[spring-boot-admin-starter-client-1.5.3.jar:1.5.3]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by joshiste** [comment]
Does you build fail? I guess it's from one of the tests and can be ignored...

**Comment by q8tywolf** [comment]
hello I have the same error, when running test. When I run the spring boot applications I get

```
Parameter 2 of method applicationFactory in de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfiguration required a bean of type 'org.springframework.boot.autoconfigure.web.ServerProperties' that could not be found.
	- Bean method 'serverProperties' in 'ManagementServerPropertiesAutoConfiguration' not loaded because @ConditionalOnWebApplication (required) not a web application
	- Bean method 'serverProperties' not loaded because @ConditionalOnWebApplication (required) not a web application

```

I have multiple spring boot applications run with SpringApplicationbuilder 
Like so

```
SpringApplicationBuilder appBuilder
                = new SpringApplicationBuilder().listeners(new ContextsApplicationListener())
                        .parent(RootConfig.class)
                        .child(Child1Config.class)
                        .sibling(Child2Config.class);
        appBuilder.run();

```
They are all running non web context's. Does this library support non web.

If not, can I do a spring boot web application and have endpoint handled by it and keep the desktop apps run isolated
a bit like 
```
SpringApplicationBuilder appBuilder
                = new SpringApplicationBuilder().listeners(new ContextsApplicationListener())
                        .sources(EndpointConfig.class)
                         .parent(RootConfig.class)
                        .child(Child1Config.class)
                        .sibling(Child2Config.class);
        appBuilder.run();
```

Please let me know this Admin UI is really great and I have the server UI installed but cant wait to test my apps on it.

**Comment by joshiste** [comment]
> They are all running non web context's. Does this library support non web.

No. You need to provide the actuator endpoints via http.

**Comment by q8tywolf** [comment]
I managed to expose the endpoints for my child context.

```
SpringApplicationBuilder appBuilder
                = new SpringApplicationBuilder().listeners(new ContextsApplicationListener())
                         .parent(RootConfig.class) //non web
                        .child(Child1Config.class) //web
                        .sibling(Child2Config.class); //web
        appBuilder.run();
```
So that will expose the child contexts to the spring admin ui. 

but The Spring boot admin client library try to implement a client for my non web context which fails my application all together rather than skipping non web contexts.

Is there a way to add to @Configuration class to not implement auto config a spring boot client.
@joshiste

**Comment by joshiste** [comment]
you can exclude the `SpringBootAdminClientAutoConfiguration` and configure the components yourself...

**Comment by xujijun** [comment]
Hi, it can be built but just annoying. It could be during running UT cases when package.
