### ISSUE TITLE
ERROR service-base-url must be set when deployed to servlet-container

### ISSUE THREAD

**Issue by colaru** [codecentric/spring-boot-admin#558]
Hello!
I use:  compile("de.codecentric:spring-boot-admin-starter-client:1.5.4")
I get this error:

2017-09-21 09:19:26,981 [registrationTask1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: service-base-url must be set when deployed to servlet-container
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceUrl(DefaultApplicationFactory.java:68)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getManagementUrl(DefaultApplicationFactory.java:95)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:115)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:49)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:140)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:65)
	at de.codecentric.boot.admin.client.registration.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:80)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by joshiste** [comment]
This error appears when the client can't figure out the port of your web application. SBA client only supports web applications and when you do a war-file deployment you must tell the client where your application is running via setting `spring.boot.admin.client.management-base-url`

**Comment by magm3333** [comment]
Hi,
I have the same problem, and then from stableberspring.boot.admin.client.management-base-url, but the problem continues.

This is my **application.properties** file

```
server.port=8080
server.contextPath=/ti
spring.profiles.active=mysqllocal
spring.jackson.serialization.indent-outpu
endpoints.shutdown.sensitive=false
endpoints.shutdown.enabled=true

spring.boot.admin.url=http://sbahoost:8090  

management.context-path=/mgmt
management.security.enabled=true
management.security.roles=ADMIN
security.user.name=admin
security.user.password=admin
spring.boot.admin.client.metadata.user.name=${security.user.name}
spring.boot.admin.client.metadata.user.password=${security.user.password}
spring.boot.admin.client.management-base-url=http://clienthost/ti
```

I hope you can helpme
