### ISSUE TITLE
 No instance found for serviceId 'turbine'

### ISSUE THREAD

**Issue by iamnotgay** [codecentric/spring-boot-admin#630]
Caused by: java.lang.IllegalStateException: No instance found for serviceId 'turbine'
	at spring.boot.admin.turbine.zuul.filters.TurbineRouteLocator.resolveServiceId(TurbineRouteLocator.java:71) ~[spring-boot-admin-server-ui-turbine-1.5.3.jar:1.5.3]
	at spring.boot.admin.turbine.zuul.filters.TurbineRouteLocator.getMatchingRoute(TurbineRouteLocator.java:59) ~[spring-boot-admin-server-ui-turbine-1.5.3.jar:1.5.3]
	at org.springframework.cloud.netflix.zuul.filters.CompositeRouteLocator.getMatchingRoute(CompositeRouteLocator.java:63) ~[spring-cloud-netflix-core-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.cloud.netflix.zuul.filters.pre.PreDecorationFilter.run(PreDecorationFilter.java:113) ~[spring-cloud-netflix-core-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) ~[zuul-core-1.3.0.jar:1.3.0]
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) ~[zuul-core-1.3.0.jar:1.3.0]
	... 72 common frames omitted

**Comment by iamnotgay** [comment]
https://stackoverflow.com/questions/46492699/turbine-stream-zuul-path-api-turbine-streamcluster-sends-data-intermittently

**Comment by joshiste** [comment]
By default SBA expects a turbine server running registered with the service name `turbine`
