### ISSUE TITLE
java.lang.IllegalArgumentException: name must not be empty!

### ISSUE THREAD

**Issue by nycLive** [codecentric/spring-boot-admin#664]
Not sure if this is a Spring Boot 2.0 error or not?

Below is what I logged. 
```
java.lang.IllegalArgumentException: name must not be empty!
	at org.springframework.util.Assert.hasText(Assert.java:181) ~[spring-core-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at de.codecentric.boot.admin.client.registration.Application.<init>(Application.java:37) ~[spring-boot-admin-client-1.5.7.jar:na]
	at de.codecentric.boot.admin.client.registration.Application$Builder.build(Application.java:92) ~[spring-boot-admin-client-1.5.7.jar:na]
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:54) ~[spring-boot-admin-client-1.5.7.jar:na]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:140) ~[spring-boot-admin-client-1.5.7.jar:na]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:65) ~[spring-boot-admin-client-1.5.7.jar:na]
	at de.codecentric.boot.admin.client.registration.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:80) ~[spring-boot-admin-client-1.5.7.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

**Comment by joshiste** [comment]
you can't use Spring Boot Admin Client 1.5.7 with Spring Boot 2.0

**Comment by nycLive** [comment]
Thanks...I love your tool. 
I'm new to Spring Boot....but how can I help out upgrading your tool so it can work with Spring Boot 2.0?

**Comment by joshiste** [comment]
You could try our 2.0.0-SNAPHSOT version.
