### ISSUE TITLE
When can support the spring-boot 2.0.0.RELEASE version?

### ISSUE THREAD

**Issue by iGitHubJ** [codecentric/spring-boot-admin#679]
There will be the following errors when use spring-boot 2.0.0.RELEASE version,:
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.web.ServerProperties.getPath(Ljava/lang/String;)Ljava/lang/String;
	at de.codecentric.boot.admin.config.AdminServerWebConfiguration.addViewControllers(AdminServerWebConfiguration.java:122)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurerComposite.addViewControllers(WebMvcConfigurerComposite.java:109)
	at org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.addViewControllers(DelegatingWebMvcConfiguration.java:98)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.viewControllerHandlerMapping(WebMvcConfigurationSupport.java:446)
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$6f66dc.CGLIB$viewControllerHandlerMapping$34(<generated>)
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$6f66dc$$FastClassBySpringCGLIB$$9c384c8d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$6f66dc.viewControllerHandlerMapping(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 25 more

**Comment by joshiste** [comment]
duplicates #465
