### ISSUE TITLE
Application registers but it's always offline

### ISSUE THREAD

**Issue by marioconforti** [codecentric/spring-boot-admin#691]
The application register, but it shows offline.

I i try to POST to /api/applications on my Admin Server I get a 500 error
```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
mar 30 15:55:26 ip-172-31-26-216 bash[20029]: java.lang.NullPointerException: null
mar 30 15:55:26 ip-172-31-26-216 bash[20029]:         at de.codecentric.boot.admin.jackson.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:25) ~[spring-boot-admin-server-1.5.7.jar!/:na]
mar 30 15:55:26 ip-172-31-26-216 bash[20029]:         at de.codecentric.boot.admin.jackson.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:14) ~[spring-boot-admin-server-1.5.7.jar!/:na]
mar 30 15:55:26 ip-172-31-26-216 bash[20029]:         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814) ~[jackson-databind-2.8.10.jar!/:2.8.10]
mar 30 15:55:26 ip-172-31-26-216 bash[20029]:         at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2938) ~[jackson-databind-2.8.10.jar!/:2.8.10]

```

I I make a GET to the same address, i have this response

```
[
    {
        "id": "4b81eb38",
        "name": "My App",
        "managementUrl": "http://myapp.com/",
        "healthUrl": "http://myapp.com/health/",
        "serviceUrl": "http://myapp.com/",
        "statusInfo": {
            "status": "OFFLINE",
            "timestamp": 1522418122492,
            "details": {
                "exception": "org.springframework.web.client.RestClientException",
                "message": "Could not extract response: no suitable HttpMessageConverter found for response type [interface java.util.Map] and content type [text/html;charset=iso-8859-1]"
            }
        },
        "source": "http-api",
        "metadata": {
            "user.name": "username",
            "user.password": "******"
        },
        "info": {}
    }
]
```

If i try to directly access the actuator endpoints, i'll get the informations
for instance this is the health
```
{
    "status": "UP",
    "diskSpace": {
        "status": "UP",
        "total": 8259014656,
        "free": 5041758208,
        "threshold": 10485760
    },
    "db": {
        "status": "UP",
        "database": "MySQL",
        "hello": 1
    }
}
```

**Comment by joshiste** [comment]
Please provide a project to reproduce the issue.
The most likely cause is that you've customized jackson in some incompatible way.
The NPE during the post is due to a missing 'name' attribute.

**Comment by marioconforti** [comment]
i cannot reproduce the project... it's an existent Spring Boot application i added spring admin client to, same application works in local env with local SBA... No jackson customization

these are my properties in the client
```
##Spring Admin
spring.boot.admin.url=http://xxxxxxxxxxxx
spring.application.name=My WebApp
spring.boot.admin.username=testuser
spring.boot.admin.password=testpassword
spring.boot.admin.client.management-base-url=http://www.site.it
spring.boot.admin.client.service-base-url=http://www.site.it
management.security.enabled=true
security.user.name= testuser
security.user.password=testpassword
spring.boot.admin.client.metadata.user.name=${security.user.name}
spring.boot.admin.client.metadata.user.password=${security.user.password}
spring.boot.admin.auto-deregistration=false
spring.boot.admin.period=30000
spring.boot.admin.instance.metadata.user.name:${security.user.name}
spring.boot.admin.instance.metadata.user.password:${security.user.name}
```

**Comment by joshiste** [comment]
> i cannot reproduce the project... it's an existent Spring Boot application i added spring admin client to, same application works in local env with local SBA...

I can't help you without reproducing the issue.
