### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by Erlix322** [codecentric/spring-boot-admin#693]

**Comment by Erlix322** [comment]
Hi,

I created a new Spring Boot Application using Spring Initializer and put the following into my Buil script:
`dependencies {
	compile('org.springframework.boot:spring-boot-starter')
	testCompile('org.springframework.boot:spring-boot-starter-test')
	compile group: 'de.codecentric', name: 'spring-boot-admin-starter-server', version: '1.5.7'
}`

I followed the quick guide on your page and my Application class looks like this:

`package org.htwdd.admin;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;

import de.codecentric.boot.admin.config.EnableAdminServer;

@Configuration
@EnableAutoConfiguration
@EnableAdminServer
public class AdminApplication {

	public static void main(String[] args) {
		SpringApplication.run(AdminApplication.class, args);
	}
}`

But whe I'm trying to start the Application it fails with the following output:

`16:44:30.778 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [file:/C:/Program%20Files/Java/jre1.8.0_162/lib/resources.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/rt.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/jsse.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/jce.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/charsets.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/jfr.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jre1.8.0_162/lib/ext/zipfs.jar, file:/C:/Projects/Java/SpringAdmin/bin/main/, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/de.codecentric/spring-boot-admin-starter-server/1.5.7/74c2387b1fd12826683e05ee7777fa19cd457c45/spring-boot-admin-starter-server-1.5.7.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/de.codecentric/spring-boot-admin-server/1.5.7/2ef7066fb5c2be2e29afa62e3e31f73aa94a96c3/spring-boot-admin-server-1.5.7.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-web/2.0.0.RELEASE/fcb2a9e18f98382e626935841f85ed44d7153615/spring-boot-starter-web-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-actuator/2.0.0.RELEASE/22d7f64be5452ddad3fd0d651c818de658a18f3e/spring-boot-starter-actuator-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-json/2.0.0.RELEASE/5a09c939d8bd60d7f163c1c0c20a3127ba9fffa/spring-boot-starter-json-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter/2.0.0.RELEASE/6d7d8e4bf053cd1833f3c7dbce676bc274f0892f/spring-boot-starter-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-netflix-core/1.4.2.RELEASE/bb9965d162fc33001f77ed954ef5a44b854e2be/spring-cloud-netflix-core-1.4.2.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-actuator-autoconfigure/2.0.0.RELEASE/ffaa094aef881dbb30621f6f042dcfec125ffe9/spring-boot-actuator-autoconfigure-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.0.0.RELEASE/c89896a469ecf92996ecba40755919896ace5470/spring-boot-autoconfigure-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-actuator/2.0.0.RELEASE/309a5d45b09e361d29c9e7d1def644d70a50173b/spring-boot-actuator-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/2.0.0.RELEASE/771da2071ff14a47f108642a641c204ae4ef7b15/spring-boot-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-logging/2.0.0.RELEASE/fe939b71659ef1f98a53cce0b5bcf771685cf6a6/spring-boot-starter-logging-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-tomcat/2.0.0.RELEASE/908bc9de1a7cfa857edf44182d426f6e0d8a3008/spring-boot-starter-tomcat-2.0.0.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/javax.annotation/javax.annotation-api/1.3.2/934c04d3cfef185a8008e7bf34331b79730a9d43/javax.annotation-api-1.3.2.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/5.0.4.RELEASE/addcf1caa22613c474bd6dde8c7134fef940b1f0/spring-webmvc-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/5.0.4.RELEASE/3e76d08c851113077642c5704f0f94d5ce58e905/spring-context-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-aop/5.0.4.RELEASE/f8e029e54c0267dadb6b9f713f3feb54ec4f3a0e/spring-aop-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-web/5.0.4.RELEASE/9565bbc67bf1a850a6505deaa5103931712a7b80/spring-web-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-beans/5.0.4.RELEASE/7a8c3d48d4c33621e64d1399721d8e067450fcbd/spring-beans-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-expression/5.0.4.RELEASE/4bda161f2e34c1486f2527a23eb47293567f473c/spring-expression-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.0.4.RELEASE/2221a957b5561a34f044350ba4e30ef5870254a3/spring-core-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.19/2d998d3d674b172a588e54ab619854d073f555b5/snakeyaml-1.19.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/de.codecentric/spring-boot-admin-server-ui/1.5.7/1bdf981cfd314d4bef98843a33da80753adebb2b/spring-boot-admin-server-ui-1.5.7.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-to-slf4j/2.10.0/f7e631ccf49cfc0aefa4a2a728da7d374c05bd3c/log4j-to-slf4j-2.10.0.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/1.7.25/af5364cd6679bfffb114f0dec8a157aaa283b76/jul-to-slf4j-1.7.25.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework/spring-jcl/5.0.4.RELEASE/3053e2bad0a18571bdbb9596ce51f9d458f5934f/spring-jcl-5.0.4.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.9.4/63ac052d52a70a15820d3dc07ea757826fd51d40/jackson-datatype-jdk8-2.9.4.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.9.4/12d52679a6615c7972ea25bd8ebb60b191fe79b7/jackson-datatype-jsr310-2.9.4.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-parameter-names/2.9.4/5833c819877c3e85bad847f4d2fa4e70379217c6/jackson-module-parameter-names-2.9.4.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.9.4/498bbc3b94f566982c7f7c6d4d303fce365529be/jackson-databind-2.9.4.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.netflix.zuul/zuul-core/1.3.0/3974695eb1c9845a2fc575acfdea2d8d91deba1b/zuul-core-1.3.0.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.netflix.hystrix/hystrix-core/1.5.12/75379b6671fcaa9cec33035df684a68ec7741ca6/hystrix-core-1.5.12.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-context/1.3.1.RELEASE/d917a126751620aa62131858069374287d72d47/spring-cloud-context-1.3.1.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-commons/1.3.1.RELEASE/36bf49ae5e26d5401eb3ffcd9f1f962001bcbbfb/spring-cloud-commons-1.3.1.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.5.5/1603dfd56ebcd583ccdf337b6c3984ac55d89e58/httpclient-4.5.5.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.2.3/864344400c3d4d92dfeb0a305dc87d953677c03c/logback-core-1.2.3.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.netflix.servo/servo-core/0.7.2/b940f73ac9ddb440b79e801c8b936228dc0cc142/servo-core-0.7.2.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.netflix.netflix-commons/netflix-commons-util/0.1.1/39e67061780476f207b31465baaed84a91ff659f/netflix-commons-util-0.1.1.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.netflix.archaius/archaius-core/0.6.0/1ecb29ef5d4c0c98cae35d1038fd980688eab5f9/archaius-core-0.6.0.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.10.0/fec5797a55b786184a537abd39c3fa1449d752d6/log4j-api-2.10.0.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.hibernate.validator/hibernate-validator/6.0.7.Final/8b9d9c7ec8c73963ea0fe81912fc67711a4ef76/hibernate-validator-6.0.7.Final.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-core/1.0.1/698281b5829a16ddea19f3a5d4414d7ece1d3f11/micrometer-core-1.0.1.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.9.0/7c10d545325e3a6e72e06381afe469fd40eb701/jackson-annotations-2.9.0.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.9.4/a9a71ec1aa37da47db168fede9a4a5fb5e374320/jackson-core-2.9.4.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.4/b1b6ea3b7e4aa4f492509a4952029cd8e48019ad/commons-io-2.4.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/io.reactivex/rxjava/1.3.6/f8596dcb885d65c86f96cf96fe12772c56d51d1d/rxjava-1.3.6.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.hdrhistogram/HdrHistogram/2.1.10/9e1ac84eed220281841b75e72fb9de5a297fbf04/HdrHistogram-2.1.10.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-crypto/5.0.3.RELEASE/3781c0af8e85e18d1d8807f9731eb347641fac13/spring-security-crypto-5.0.3.RELEASE.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.9/a86ce739e5a7175b4b234c290a00a5fdb80957a0/httpcore-4.4.9.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.11/3acb4705652e16236558f0f4f2192cc33c3bd189/commons-codec-1.11.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/8.5.28/8a5a48740dd80cad644ceb541e77fd8e0809e3b7/tomcat-embed-websocket-8.5.28.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/8.5.28/b684c98cf77c6528079c4e59fc1feeb218bf82f1/tomcat-embed-core-8.5.28.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-el/8.5.28/75745598f60646ccf0c4b105468a9c8be9b8432e/tomcat-embed-el-8.5.28.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/2.0.1.Final/cb855558e6271b1b32e716d24cb85c7f583ce09e/validation-api-2.0.1.Final.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.jboss.logging/jboss-logging/3.3.2.Final/3789d00e859632e6c6206adc0c71625559e6e3b0/jboss-logging-3.3.2.Final.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.fasterxml/classmate/1.3.4/3d5f48f10bbe4eb7bd862f10c0583be2e0053c6/classmate-1.3.4.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.latencyutils/LatencyUtils/2.0.3/769c0b82cb2421c8256300e907298a9410a2a3d3/LatencyUtils-2.0.3.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/14.0.1/69e12f4c6aeac392555f1ea86fab82b5e5e31ad4/guava-14.0.1.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/annotations/2.0.0/d8dff1d83a79f0c0609c360f02bcd2f2fc1f1369/annotations-2.0.0.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.codehaus.jackson/jackson-mapper-asl/1.9.11/45d70862fa016993193075a1e8e32a01dcf438e8/jackson-mapper-asl-1.9.11.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/commons-configuration/commons-configuration/1.8/6cce40435bcd8018018f16898de01976b319941a/commons-configuration-1.8.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/org.codehaus.jackson/jackson-core-asl/1.9.11/e32303ef8bd18a5c9272780d49b81c95e05ddf43/jackson-core-asl-1.9.11.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.6/ce1edb914c94ebc388f086c6827e8bdeec71ac2/commons-lang-2.6.jar, file:/C:/Users/alf/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.1.1/5043bfebc3db072ed80fbd362e7caf00e885d8ae/commons-logging-1.1.1.jar]
16:44:30.783 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:161)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:102)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:68)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at org.htwdd.admin.AdminApplication.main(AdminApplication.java:11)
`

I hope you can give me a hint about what I'm doing wrong. :)
