### ISSUE TITLE
Problems with up in docker container

### ISSUE THREAD

**Issue by RostyslavPaliuha** [codecentric/spring-boot-admin#703]
Hello, please help me, if I run my services in IDE or up docker containers without SBA all works fine. When I added SBA server/client dependencies and configured and ran in IntelliJ on windows 10 it worked fine, but don`t work properly in docker. I try change images from OpenJDK: alpine to OpenJDK:8u162-jre-stretch and nothing changed.

> ERROR

```
config_1  | 2018-04-12 10:29:41.918 ERROR 1 --- [gistrationTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpec
ted error occurred in scheduled task.
config_1  |
config_1  | java.lang.IllegalArgumentException: linuxkit-00155d002420: linuxkit-00155d002420: Name or service not kn
own
config_1  |     at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getLocalHost(DefaultAppli
cationFactory.java:183) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceHost(DefaultApp
licationFactory.java:166) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceBaseUrl(Default
ApplicationFactory.java:103) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getServiceUrl(ServletAppl
icationFactory.java:58) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementBaseUrl(Serv
letApplicationFactory.java:73) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultAppli
cationFactory.java:150) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(Default
ApplicationFactory.java:71) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(Applicatio
nRegistrator.java:154) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistra
tor.java:71) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlin
gRunnable.java:54) ~[spring-context-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
config_1  |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_162]
config_1  |     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_162]
config_1  |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPo
olExecutor.java:180) [na:1.8.0_162]
config_1  |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecu
tor.java:294) [na:1.8.0_162]
config_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
config_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
config_1  |     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
config_1  | Caused by: java.net.UnknownHostException: linuxkit-00155d002420: linuxkit-00155d002420: Name or service
not known
config_1  |     at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_162]
config_1  |     at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getLocalHost(DefaultAppli
cationFactory.java:181) ~[spring-boot-admin-client-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
config_1  |     ... 16 common frames omitted
config_1  | Caused by: java.net.UnknownHostException: linuxkit-00155d002420: Name or service not known
config_1  |     at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_162]
config_1  |     at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_162]
config_1  |     at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_162]
config_1  |     at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_162]
config_1  |     ... 17 common frames omitted
```

**Comment by joshiste** [comment]
Looks like the client can't resolve the local hostname. `spring.boot.admin.client.instance.prefer-ip=true` should do the trick.

**Comment by RostyslavPaliuha** [comment]
I think that I must set this info into docker container, I try your way and write about the result.

**Comment by joshiste** [comment]
same error?

**Comment by RostyslavPaliuha** [comment]
yeah only set manualy the hostname property in docker-compose or docker run  resolve this error.

**Comment by grkajac** [comment]
@RostyslavPaliuha make sure that you execute docker run properly.
First, ports from docker container must be published or set container network to --network host.

Second, check host firewall settings, check if published port isn't on the deny list.
