### ISSUE TITLE
AWS ECS Fargate client registration issue

### ISSUE THREAD

**Issue by andreyzhm** [codecentric/spring-boot-admin#718]
My SBA clients are fail to register due to the following error:
```
22:19:32
Caused by: java.net.UnknownHostException: 06db59557bed: Name or service not known
22:19:32
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_141]
22:19:32
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_141]
22:19:32
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_141]
22:19:32
at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[?:1.8.0_141]
22:19:32
at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getLocalHost(DefaultApplicationFactory.java:144) ~[spring-boot-admin-client-1.5.7.jar!/:?]
22:19:32
... 16 more
```
Looks like it tries to resolve its own address and fails

**Comment by andreyzhm** [comment]
Yea, I see, I guess it worth adding cloud support like in eureka that works with AWS ecs.

**Comment by joshiste** [comment]
I wonder wether the Eureka Client has the same issue... 
Otherwise we could just choose the first ip address from the NICs we find...

**Comment by andreyzhm** [comment]
Yea, kinda they have a special configuration for AWS, https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java
I am pretty close to resolve it by fetching the ip from aws task meatadat endpoint, I will post the solution once done.

**Comment by bhanu0684** [comment]
https://medium.com/@bhanu.pratap/service-discovery-in-spring-cloud-using-netflix-eureka-in-aws-fargate-2c5c294fee5c
