### ISSUE TITLE
boot2.0.2   cloud Finchley.RC1   admin2.0.0

### ISSUE THREAD

**Issue by javanan** [codecentric/spring-boot-admin#759]
management:
  endpoints:
    web:
      exposure:
        include: *

aused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning an alias
 in 'reader', line 76, column 18:
            include: *
                     ^
(13)
 in 'reader', line 76, column 19:
            include: *
                      ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1447)

management:
  endpoints:
    web:
      exposure:
        include: "*"

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping]: Factory method 'webEndpointServletHandlerMapping' threw exception; nested exception is java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	... 52 common frames omitted
Caused by: java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.convertToEndpoint(EndpointDiscoverer.java:199)

**Comment by javanan** [comment]
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env

**Comment by ycg000344** [comment]
@javanan what's the meaning of dev? spring.profiles? can you give more info?plz...

**Comment by tinnapat** [comment]
I think to use spring cloud with boot 2.0.0 use need Finchley.RC2
