### ISSUE TITLE
CouldNotConnectException with ElasticsearchJestHealthIndicator inspite of disabling actuator endpoints

### ISSUE THREAD

**Issue by pc-cchandragiri** [codecentric/spring-boot-admin#769]
Hi,

I am new to Spring Boot admin and am trying to use spring-boot-admin-starter-client in one of my Spring Boot Application. The application has no dependencies on elastic search nor invokes any external service related to elastic search. However, it does have an dependency on JestClient. I see the following error when I do a health checkup on server startup at `http://localhost:8080/health`. As per the [spring actuator endoint document](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#_auto_configured_healthindicators)  I did disable the health defaults and my application properties looks something like this:

management.health.defaults.enabled=false
management.health.elasticsearch.enabled=false

Any suggestions would be appreciated. Thanks!

`15:54:11.689 [http-nio-8080-exec-1] WARN  o.s.b.a.h.ElasticsearchJestHealthIndicator - Health check failed
io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://localhost:9200
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:60)
	at org.springframework.boot.actuate.health.ElasticsearchJestHealthIndicator.doHealthCheck(ElasticsearchJestHealthIndicator.java:44)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:43)
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68)
	at org.springframework.boot.actuate.endpoint.HealthEndpoint.invoke(HealthEndpoint.java:85)
	at org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.getCurrentHealth(HealthMvcEndpoint.java:177)
	at org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.getHealth(HealthMvcEndpoint.java:166)`

**Comment by pc-cchandragiri** [comment]
No worries, I was able to solve this issue by adding @SpringBootApplication(exclude = JestAutoConfiguration.class). Not sure why spring boot tried to auto configure elasticsearch by default
