### ISSUE TITLE
Type definition error: [simple type, class de.codecentric.boot.admin.server.domain.values.Registration];

### ISSUE THREAD

**Issue by vladimirvilinski** [codecentric/spring-boot-admin#777]
Client cannot register itself in admin, some JSON deserialization issue. Tried it in different configurations and app constellations -> spent about half a day without success.

"Application" JSON does not contan "source" and "Registration" seems to have a problem with it.

Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
2018-06-08 08:08:52 [main] DEBUG com.shc.basng.admin.AdminApplication - Running with Spring Boot v2.0.2.RELEASE, Spring v5.0.6.RELEASE
2018-06-08 08:08:52 [main] INFO  com.shc.basng.admin.AdminApplication - No active profile set, falling back to default profiles: default
2018-06-08 08:08:52 [main] INFO  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@61443d8f: startup date [Fri Jun 08 08:08:52 CEST 2018]; root of context hierarchy
2018-06-08 08:08:54 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 7000 (http)
2018-06-08 08:08:54 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2018-06-08 08:08:54 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.31
2018-06-08 08:08:54 [localhost-startStop-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2018-06-08 08:08:54 [localhost-startStop-1] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 2287 ms
2018-06-08 08:08:55 [localhost-startStop-1] INFO  o.s.b.w.s.ServletRegistrationBean - Servlet dispatcherServlet mapped to [/]
2018-06-08 08:08:55 [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'characterEncodingFilter' to: [/*]
2018-06-08 08:08:55 [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'httpTraceFilter' to: [/*]
2018-06-08 08:08:55 [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-06-08 08:08:55 [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'logFilter' to: [/*]
2018-06-08 08:08:55 [localhost-startStop-1] DEBUG o.s.w.f.CommonsRequestLoggingFilter - Initializing filter 'logFilter'
2018-06-08 08:08:55 [localhost-startStop-1] DEBUG o.s.w.f.CommonsRequestLoggingFilter - Filter 'logFilter' configured successfully
2018-06-08 08:08:55 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2018-06-08 08:08:55 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-06-08 08:08:55 [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-06-08 08:08:55 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerAdapter - Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@61443d8f: startup date [Fri Jun 08 08:08:52 CEST 2018]; root of context hierarchy
2018-06-08 08:08:56 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService
2018-06-08 08:08:57 [main] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - Looking for request mappings in application context: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@61443d8f: startup date [Fri Jun 08 08:08:52 CEST 2018]; root of context hierarchy
2018-06-08 08:08:57 [main] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - 1 request handler methods found on class de.codecentric.boot.admin.server.web.servlet.InstancesProxyController: {public reactor.core.publisher.Mono de.codecentric.boot.admin.server.web.servlet.InstancesProxyController.endpointProxy(java.lang.String,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException={[/instances/{instanceId}/actuator/**],methods=[GET || HEAD || POST || PUT || PATCH || DELETE || OPTIONS]}}
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances/{instanceId}/actuator/**],methods=[GET || HEAD || POST || PUT || PATCH || DELETE || OPTIONS]}" onto public reactor.core.publisher.Mono<java.lang.Void> de.codecentric.boot.admin.server.web.servlet.InstancesProxyController.endpointProxy(java.lang.String,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException
2018-06-08 08:08:57 [main] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - 7 request handler methods found on class de.codecentric.boot.admin.server.web.InstancesController: {public reactor.core.publisher.Mono de.codecentric.boot.admin.server.web.InstancesController.register(de.codecentric.boot.admin.server.domain.values.Registration,org.springframework.web.util.UriComponentsBuilder)={[/instances],methods=[POST],consumes=[application/json]}, public reactor.core.publisher.Mono de.codecentric.boot.admin.server.web.InstancesController.instance(java.lang.String)={[/instances/{id}],methods=[GET],produces=[application/json]}, public reactor.core.publisher.Flux de.codecentric.boot.admin.server.web.InstancesController.instances(java.lang.String)={[/instances],methods=[GET],produces=[application/json]}, public reactor.core.publisher.Flux de.codecentric.boot.admin.server.web.InstancesController.events()={[/instances/events],methods=[GET],produces=[application/json]}, public reactor.core.publisher.Flux de.codecentric.boot.admin.server.web.InstancesController.eventStream()={[/instances/events],methods=[GET],produces=[text/event-stream]}, public reactor.core.publisher.Flux de.codecentric.boot.admin.server.web.InstancesController.instanceStream(java.lang.String)={[/instances/{id}],methods=[GET],produces=[text/event-stream]}, public reactor.core.publisher.Mono de.codecentric.boot.admin.server.web.InstancesController.unregister(java.lang.String)={[/instances/{id}],methods=[DELETE]}}
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances],methods=[POST],consumes=[application/json]}" onto public reactor.core.publisher.Mono<org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, de.codecentric.boot.admin.server.domain.values.InstanceId>>> de.codecentric.boot.admin.server.web.InstancesController.register(de.codecentric.boot.admin.server.domain.values.Registration,org.springframework.web.util.UriComponentsBuilder)
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances/{id}],methods=[GET],produces=[application/json]}" onto public reactor.core.publisher.Mono<org.springframework.http.ResponseEntity<de.codecentric.boot.admin.server.domain.entities.Instance>> de.codecentric.boot.admin.server.web.InstancesController.instance(java.lang.String)
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances],methods=[GET],produces=[application/json]}" onto public reactor.core.publisher.Flux<de.codecentric.boot.admin.server.domain.entities.Instance> de.codecentric.boot.admin.server.web.InstancesController.instances(java.lang.String)
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances/events],methods=[GET],produces=[application/json]}" onto public reactor.core.publisher.Flux<de.codecentric.boot.admin.server.domain.events.InstanceEvent> de.codecentric.boot.admin.server.web.InstancesController.events()
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances/events],methods=[GET],produces=[text/event-stream]}" onto public reactor.core.publisher.Flux<org.springframework.http.codec.ServerSentEvent<de.codecentric.boot.admin.server.domain.events.InstanceEvent>> de.codecentric.boot.admin.server.web.InstancesController.eventStream()
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances/{id}],methods=[GET],produces=[text/event-stream]}" onto public reactor.core.publisher.Flux<org.springframework.http.codec.ServerSentEvent<de.codecentric.boot.admin.server.domain.entities.Instance>> de.codecentric.boot.admin.server.web.InstancesController.instanceStream(java.lang.String)
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/instances/{id}],methods=[DELETE]}" onto public reactor.core.publisher.Mono<org.springframework.http.ResponseEntity<java.lang.Void>> de.codecentric.boot.admin.server.web.InstancesController.unregister(java.lang.String)
2018-06-08 08:08:57 [main] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - 3 request handler methods found on class de.codecentric.boot.admin.server.web.ApplicationsController: {public reactor.core.publisher.Flux de.codecentric.boot.admin.server.web.ApplicationsController.applications()={[/applications],methods=[GET],produces=[application/json]}, public reactor.core.publisher.Flux de.codecentric.boot.admin.server.web.ApplicationsController.applicationsStream()={[/applications],methods=[GET],produces=[text/event-stream]}, public reactor.core.publisher.Mono de.codecentric.boot.admin.server.web.ApplicationsController.unregister(java.lang.String)={[/applications/{name}],methods=[DELETE]}}
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/applications],methods=[GET],produces=[application/json]}" onto public reactor.core.publisher.Flux<de.codecentric.boot.admin.server.web.ApplicationsController$Application> de.codecentric.boot.admin.server.web.ApplicationsController.applications()
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/applications],methods=[GET],produces=[text/event-stream]}" onto public reactor.core.publisher.Flux<org.springframework.http.codec.ServerSentEvent<de.codecentric.boot.admin.server.web.ApplicationsController$Application>> de.codecentric.boot.admin.server.web.ApplicationsController.applicationsStream()
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/applications/{name}],methods=[DELETE]}" onto public reactor.core.publisher.Mono<org.springframework.http.ResponseEntity<java.lang.Void>> de.codecentric.boot.admin.server.web.ApplicationsController.unregister(java.lang.String)
2018-06-08 08:08:57 [main] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - 2 request handler methods found on class de.codecentric.boot.admin.server.ui.web.UiController: {public java.lang.String de.codecentric.boot.admin.server.ui.web.UiController.index()={[/],methods=[GET],produces=[text/html]}, public java.lang.String de.codecentric.boot.admin.server.ui.web.UiController.login()={[/login],methods=[GET],produces=[text/html]}}
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/],methods=[GET],produces=[text/html]}" onto public java.lang.String de.codecentric.boot.admin.server.ui.web.UiController.index()
2018-06-08 08:08:57 [main] INFO  d.c.b.a.s.w.s.AdminControllerHandlerMapping - Mapped "{[/login],methods=[GET],produces=[text/html]}" onto public java.lang.String de.codecentric.boot.admin.server.ui.web.UiController.login()
2018-06-08 08:08:57 [status-monitor-2] DEBUG d.c.b.a.s.s.StatusUpdateTrigger - Scheduled status update every PT10S
2018-06-08 08:08:57 [status-updater-1] DEBUG d.c.b.a.s.s.StatusUpdateTrigger - Subscribed to class de.codecentric.boot.admin.server.domain.events.InstanceRegisteredEvent events
2018-06-08 08:08:57 [endpoint-detector-3] DEBUG d.c.b.a.s.s.EndpointDetectionTrigger - Subscribed to class de.codecentric.boot.admin.server.domain.events.InstanceStatusChangedEvent events
2018-06-08 08:08:57 [info-updater-4] DEBUG d.c.b.a.s.services.InfoUpdateTrigger - Subscribed to class de.codecentric.boot.admin.server.domain.events.InstanceEvent events
2018-06-08 08:08:57 [main] WARN  o.s.b.a.t.ThymeleafAutoConfiguration$DefaultTemplateResolverConfiguration - Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2018-06-08 08:08:57 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 2 endpoint(s) beneath base path '/actuator'
2018-06-08 08:08:57 [main] INFO  o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping - Mapped "{[/actuator/health],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2018-06-08 08:08:57 [main] INFO  o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping - Mapped "{[/actuator/info],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2018-06-08 08:08:57 [main] INFO  o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping - Mapped "{[/actuator],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto protected java.util.Map<java.lang.String, java.util.Map<java.lang.String, org.springframework.boot.actuate.endpoint.web.Link>> org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping.links(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-06-08 08:08:57 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2018-06-08 08:08:57 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 7000 (http) with context path ''
2018-06-08 08:08:57 [main] INFO  com.shc.basng.admin.AdminApplication - Started AdminApplication in 5.976 seconds (JVM running for 6.473)
2018-06-08 08:08:57 [main] DEBUG d.c.b.a.c.r.RegistrationApplicationListener - Scheduled registration task for every PT10Sms
2018-06-08 08:09:02 [http-nio-7000-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-06-08 08:09:02 [http-nio-7000-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
2018-06-08 08:09:02 [http-nio-7000-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 28 ms
2018-06-08 08:09:02 [http-nio-7000-exec-1] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - Looking up handler method for path /instances
2018-06-08 08:09:02 [http-nio-7000-exec-1] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - Returning handler method [public reactor.core.publisher.Mono<org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, de.codecentric.boot.admin.server.domain.values.InstanceId>>> de.codecentric.boot.admin.server.web.InstancesController.register(de.codecentric.boot.admin.server.domain.values.Registration,org.springframework.web.util.UriComponentsBuilder)]
2018-06-08 08:09:02 [http-nio-7000-exec-1] DEBUG o.s.w.f.CommonsRequestLoggingFilter - Before request [uri=/instances]
2018-06-08 08:09:02 [http-nio-7000-exec-1] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - Looking up handler method for path /instances
2018-06-08 08:09:02 [http-nio-7000-exec-1] DEBUG d.c.b.a.s.w.s.AdminControllerHandlerMapping - Returning handler method [public reactor.core.publisher.Mono<org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, de.codecentric.boot.admin.server.domain.values.InstanceId>>> de.codecentric.boot.admin.server.web.InstancesController.register(de.codecentric.boot.admin.server.domain.values.Registration,org.springframework.web.util.UriComponentsBuilder)]
2018-06-08 08:09:02 [http-nio-7000-exec-1] DEBUG o.s.w.f.CommonsRequestLoggingFilter - REQUEST DATA : uri=/instances;payload={"name":"admin","managementUrl":"http://notebook:7000/actuator","healthUrl":"http://notebook:7000/actuator/health","serviceUrl":"http://notebook:7000/","metadata":{"user.name":"admin","user.password":"zah0d1te","startup":"2018-06-08T08:08:56.095+02:00"}}]
2018-06-08 08:09:02 [http-nio-7000-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class de.codecentric.boot.admin.server.domain.values.Registration]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `de.codecentric.boot.admin.server.domain.values.Registration` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 1, column: 2]] with root cause
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `de.codecentric.boot.admin.server.domain.values.Registration` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1290)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:223)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:206)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:157)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:130)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:124)
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:161)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:131)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:245)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:84)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
2018-06-08 08:09:02 [registrationTask1] WARN  d.c.b.a.c.r.ApplicationRegistrator - Failed to register application as Application(name=admin, managementUrl=http://notebook:7000/actuator, healthUrl=http://notebook:7000/actuator/health, serviceUrl=http://notebook:7000/, metadata={user.name=admin, user.password=zah0d1te, startup=2018-06-08T08:08:56.095+02:00}) at spring-boot-admin ([http://localhost:7000/instances]): 500 null. Further attempts are logged on DEBUG level
2018-06-08 08:09:05 [Thread-14] INFO  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@61443d8f: startup date [Fri Jun 08 08:08:52 CEST 2018]; root of context hierarchy
2018-06-08 08:09:05 [Thread-14] DEBUG d.c.b.a.c.r.RegistrationApplicationListener - Canceled registration task
2018-06-08 08:09:05 [Thread-14] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2018-06-08 08:09:05 [Thread-14] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService

[basng-admin.zip](https://github.com/codecentric/spring-boot-admin/files/2083112/basng-admin.zip)

**Comment by joshiste** [comment]
could you please provide a sample project (GH repo or zip file) to reproduce the issue?

**Comment by vladimirvilinski** [comment]
Hi joshiste. The whole project is attached (see the last line in error description). Thank you for fast response.

**Comment by alfonz19** [comment]
please see update to 955: this error happens also without @EnableWebMvc

**Comment by whaty** [comment]
-       hello,everyone,i find the real reason for this problem!Spring Boot Admin define AdminServerUiProperties.java,this file pre-define 'resourceLocations' as 'classpath:/META-INF/spring-boot-admin-server-ui/',you can look the origin code  to find this.

-     To resolve this problem ,you just make dir '/META-INF/spring-boot-admin-server-ui' in 'resources' path and move you static resource to this new path.
![image](https://user-images.githubusercontent.com/26294919/94399576-37f00400-019a-11eb-800e-c8761fde8cf2.png)

**Comment by 1264116203** [comment]
@whaty thanks for you response ,my project is Front and rear separated，and the path of '/META-INF/spring-boot-admin-server-ui' in 'resources' already existed in 'spring-boot-admin-server-ui' ,so I'm still not know how to solve this error

**Comment by ironman19933** [comment]
I am facing the same issue. what @whaty has mentioned, I really didn't understand how to implement that.
