### ISSUE TITLE
Docker run application Error

### ISSUE THREAD

**Issue by cherrishccl** [codecentric/spring-boot-admin#820]
My spring-boot-admin2.0 was working well in my Idea IDE, but when I deployed in a docker and some errors occured, Would someone tell me why?
```Caused by: de.codecentric.boot.admin.server.eventstore.OptimisticLockingException: Verison 0 was overtaken by 0 for a99c06bdd05b
	at de.codecentric.boot.admin.server.eventstore.ConcurrentMapEventStore.createOptimisticLockException(ConcurrentMapEventStore.java:123) ~[spring-boot-admin-server-2.0.1.jar!/:2.0.1]
	at de.codecentric.boot.admin.server.eventstore.ConcurrentMapEventStore.doAppend(ConcurrentMapEventStore.java:93) ~[spring-boot-admin-server-2.0.1.jar!/:2.0.1]
	at de.codecentric.boot.admin.server.eventstore.ConcurrentMapEventStore.lambda$append$2(ConcurrentMapEventStore.java:71) ~[spring-boot-admin-server-2.0.1.jar!/:2.0.1]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:67) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:30) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:160) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1640) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1454) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1328) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:174) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Operators.complete(Operators.java:128) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(FluxRetryWhen.java:180) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onNext(FluxRetryWhen.java:226) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:271) [reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:803) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	... 8 common frames omitted
```

**Comment by joshiste** [comment]
This error occurs if there are concurrent writes to the repository storing the instances information. Usually the operations are retried a couple of times until they are successful. Does this happen all the time or rarely? Could you provide the full logs as attachment?

**Comment by cherrishccl** [comment]
[spring-boot-admin.log](https://github.com/codecentric/spring-boot-admin/files/2183369/spring-boot-admin.log)

This is the full logs，thanks.

**Comment by cherrishccl** [comment]
[themis-admin.log](https://github.com/codecentric/spring-boot-admin/files/2183431/themis-admin.log)
![error_2](https://user-images.githubusercontent.com/9584385/42557170-56a544a8-8520-11e8-8930-a9cd868d0f01.png)
![error-1](https://user-images.githubusercontent.com/9584385/42557171-56f0955c-8520-11e8-989f-b97a7cdc5fc6.png)
This is the full logs, thanks.

**Comment by joshiste** [comment]
the mentioned exception is not in the log, so I guess the issue is resolved.
