### ISSUE TITLE
Missing information in SBA 2.0.1 UI when monitoring Spring Boot 1.x applications

### ISSUE THREAD

**Issue by djgeary** [codecentric/spring-boot-admin#828]
We have just upgraded to SBA 2.0.1 and our services that we are monitoring are still Spring Boot 1.x applications (we are using eureka cloud discovery)

By default we see a lot of missing information in the UI - only some services show all the tabs whereas some only show the details tab. This appears to be random.

We also see a lot of stack traces in Spring Boot Admin: 

```
2018-07-16 11:20:59.253 ERROR 22690 --- [client-epoll-16] d.c.b.a.s.s.EndpointDetectionTrigger     : Resubscribing after uncaught error

java.lang.IllegalStateException: Duplicate key Endpoint(id=threaddump, url=http://172.31.50.79:12005/dump)
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.codecentric.boot.admin.server.domain.values.Endpoints.<init>(Endpoints.java:46)
	at de.codecentric.boot.admin.server.domain.values.Endpoints.of(Endpoints.java:72)
	at de.codecentric.boot.admin.server.services.endpoints.ProbeEndpointsStrategy.lambda$detectEndpoints$2(ProbeEndpointsStrategy.java:52)
```

I had a look into the code found the 'endpoints' list is obtained from the AdminServerProperties class and defaults to 

```
{"health", "env", "metrics", "httptrace:trace", "httptrace", "threaddump:dump",
        "threaddump", "jolokia", "info", "logfile", "refresh", "flyway", "liquibase", "heapdump", "loggers",
        "auditevents"};
```
The problem with the duplicate key seems to be caused by the presence of both "httptrace:trace" and "httptrace" (and similarly for threaddump)

Overriding this in config by adding the line

```
spring.boot.admin.probed-endpoints: [ "health", "env", "metrics", "httptrace:trace", "threaddump:dump", "jolokia", "info", "logfile", "refresh", "flyway", "liquibase", "heapdump", "loggers", "auditevents" ]
```

seems to fix the problem, we no longer get the exceptions and the UI is stable and shows all expected information.

**Comment by joshiste** [comment]
Usual your application should either respond for the option request on either `/dump` or `/threaddump` and not on both so it suprises me a bit that both endpoints are discovered.
Nonetheless we should protect the server against just blowing up.

**Comment by wendlm** [comment]
Unfortunately I encounter exactly the same problem in our Spring Boot 1.5.10 application
