### ISSUE TITLE
Retry failed actuator requests

### ISSUE THREAD

**Issue by djgeary** [codecentric/spring-boot-admin#862]
I'm testing out SBA 2.0.2 and occasionally see timeout exceptions on startup eg 

```
2018-08-01 16:04:56.517  WARN 28448 --- [client-epoll-16] d.c.b.a.s.s.e.ProbeEndpointsStrategy     : Duplicate endpoints for id 'httptrace' detected. Omitting: [ProbeEndpointsStrategy.DetectedEndpoint(definition=ProbeEndpointsStrategy.EndpointDefinition(id=httptrace, path=httptrace), endpoint=Endpoint(id=httptrace, url=http://172.31.50.79:12005/httptrace))]
2018-08-01 16:04:56.518  WARN 28448 --- [client-epoll-16] d.c.b.a.s.s.e.ProbeEndpointsStrategy     : Duplicate endpoints for id 'threaddump' detected. Omitting: [ProbeEndpointsStrategy.DetectedEndpoint(definition=ProbeEndpointsStrategy.EndpointDefinition(id=threaddump, path=threaddump), endpoint=Endpoint(id=threaddump, url=http://172.31.50.79:12005/threaddump))]
2018-08-01 16:04:57.859 ERROR 28448 --- [client-epoll-12] r.i.n.c.PooledClientContextHandler       : Failed releasing channel

java.util.concurrent.ExecutionException: io.netty.channel.ConnectTimeoutException: connection timed out: /172.31.50.79:11105
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
	at reactor.ipc.netty.channel.PooledClientContextHandler.dispose(PooledClientContextHandler.java:218)
	at reactor.core.publisher.FluxCreate$SinkDisposable.cancel(FluxCreate.java:945)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.disposeResource(MonoCreate.java:275)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.cancel(MonoCreate.java:265)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1511)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1480)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1292)
	at reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:154)
	at reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:154)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:145)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:145)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:145)
	at reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:154)
	at reactor.core.publisher.Operators.terminate(Operators.java:649)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.cancel(MonoFlatMap.java:264)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:181)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1511)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1480)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1292)
	at reactor.core.publisher.Operators.terminate(Operators.java:649)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:180)
	at reactor.core.publisher.Operators.terminate(Operators.java:649)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.cancel(FluxFlatMap.java:952)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:302)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:182)
	at reactor.core.publisher.FlatMapTracker.unsubscribe(FluxFlatMap.java:1011)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:767)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:543)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:523)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:788)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:923)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:1323)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:207)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:207)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:207)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:100)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:166)
	at reactor.ipc.netty.channel.ContextHandler.fireContextError(ContextHandler.java:272)
	at reactor.ipc.netty.channel.PooledClientContextHandler.operationComplete(PooledClientContextHandler.java:153)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:322)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.31.50.79:11105
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:568)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	... 5 common frames omitted

2018-08-01 16:04:57.865 ERROR 28448 --- [client-epoll-12] r.i.n.c.PooledClientContextHandler       : Failed releasing channel
```

The effect of this is the same as https://github.com/codecentric/spring-boot-admin/issues/828 (which we had previously) ie it results in tabs missing from the UI.

Mostly the exceptions don't occur and there is no missing information. 

We are using eureka discovery and most of our microservices are still Spring Boot 1 if thats relevant

**Comment by djgeary** [comment]
Even if its a network issue (I was testing a local SBA against Eureka and Services in AWS) shouldn't SBA catch / handle the timeout? When this happens I need to restart SBA to fix it, otherwise information is permanently missing in the UI.

**Comment by joshiste** [comment]
Agreed. The probing should do a retry of a timeout/connection error occurs.

**Comment by Sarvesh-D** [comment]
Any updates on this issue? We too are facing similar problem. In our case, the `ReadTimeOutException` is resulting in SBA to consider the registered application is down and it triggers the notification. This is causing false positives. Any idea how to increase the read time out would be appreciated if the retry mechanism will be complex to implement. I am using SBA 2.0.1. Thanks.
