### ISSUE TITLE
SBA 2.0.2 - Error loading HTTP Trace vue

### ISSUE THREAD

**Issue by GaetanWi** [codecentric/spring-boot-admin#914]
Hello there!

We're currently trying to setup Spring Boot Admin. 
Every single tab seems to work correctly except the HttpTrace one. 

When clicking on the Http Trace tab, chrome is loading the `traces-charts.vue` vue then suddenly dies. 
I can access debug in the Chrome Console though, and I can see that I cannot reach `const interval` value. 

When overring interval, this stack shows up :
```"ReferenceError: interval is not defined
    at eval (eval at chartData (http://localhost:9000/assets/js/sba-core.js:1:187092), <anonymous>:1:1)
    at i.chartData (http://localhost:9000/assets/js/sba-core.js:1:187092)
    at Os.get (http://localhost:9000/assets/js/vendors.js:16:5661)
    at Os.evaluate (http://localhost:9000/assets/js/vendors.js:16:6653)
    at i.chartData (http://localhost:9000/assets/js/vendors.js:11:421127)
    at i.<anonymous> (http://localhost:9000/assets/js/vendors.js:11:408779)
    at Os.get (http://localhost:9000/assets/js/vendors.js:16:5661)
    at new Os (http://localhost:9000/assets/js/vendors.js:16:5584)
    at i.e.$watch (http://localhost:9000/assets/js/vendors.js:16:8274)
    at tt (http://localhost:9000/assets/js/vendors.js:11:421450)"
```

Knowing that interval is not defined, I guess chrome is crashing because this: 
`for (let time = Math.floor(oldest.valueOf() / interval) * interval; time < now; time += interval) `

I don't really know about VueJS so I don't know if that's because the const is wrapped so cannot access it, but I would seriously doubt it. Seems weird to me. 

I may be missing something, that may be configuration issue on my side, I don't really know what to search for, but if anyone is having informations about this, I'd gladly take it. 

-- ALSO : I had the issue on SBA 2.0.1 so went for the 2.0.2 hoping for a fix, but no result, so same issue on SBA 2.0.1

**Comment by GaetanWi** [comment]
Closing, related to this issue : 
https://github.com/codecentric/spring-boot-admin/issues/861
