### ISSUE TITLE
java.lang.IllegalStateException: Either health or status endpoint must be enabled!

### ISSUE THREAD

**Issue by wzlee** [codecentric/spring-boot-admin#945]
spring boot version:
`2.0.5.RELEASE`

client properties:
```
server.port=8090
spring.boot.admin.client.url: "http://localhost:8080"  
management.endpoints.web.exposure.include: "*"
management.endpoint.health.enabled=true
```
and the exception
```
java.lang.IllegalStateException: Either health or status endpoint must be enabled!
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthEndpointPath(DefaultApplicationFactory.java:204) ~[spring-boot-admin-client-2.0.2.jar:2.0.2]
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:152) ~[spring-boot-admin-client-2.0.2.jar:2.0.2]
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:71) ~[spring-boot-admin-client-2.0.2.jar:2.0.2]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:154) ~[spring-boot-admin-client-2.0.2.jar:2.0.2]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:71) ~[spring-boot-admin-client-2.0.2.jar:2.0.2]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```
i don't known how to set the 'status' in the properties

**Comment by joshiste** [comment]
when this is a `application.properties` (and not `.yml`) it must look like this:

```
server.port=8090
spring.boot.admin.client.url=http://localhost:8080
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
```
