### ISSUE TITLE
logging file mapping error 

### ISSUE THREAD

**Issue by linux-china** [codecentric/spring-boot-admin#98]
Spring Boot 1.3.0.M4, add logging.file=/tmp/boot-demo.log in application.properties, then throw following stacktrace: 

```
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'de.codecentric.boot.admin.actuate.LogfileMvcEndpoint@7dc111f0' method 
public void de.codecentric.boot.admin.actuate.LogfileMvcEndpoint.invoke(javax.servlet.http.HttpServletResponse) throws java.io.IOException
to {[/logfile],methods=[GET]}: There is already 'org.springframework.boot.actuate.endpoint.mvc.LogFileMvcEndpoint@7718c23a' bean method
public org.springframework.http.ResponseEntity<?> org.springframework.boot.actuate.endpoint.mvc.LogFileMvcEndpoint.invoke() throws java.io.IOException mapped.
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.assertUniqueMethodMapping(AbstractHandlerMethodMapping.java:565)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.register(AbstractHandlerMethodMapping.java:529)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.registerHandlerMethod(AbstractHandlerMethodMapping.java:252)
	at org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.registerHandlerMethod(EndpointHandlerMapping.java:115)
	at org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.registerHandlerMethod(EndpointHandlerMapping.java:51)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:223)
	at org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.afterPropertiesSet(EndpointHandlerMapping.java:93)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 40 more
```

**Comment by joshiste** [comment]
When spring boot admin is updated to spring boot 1.3.0 this should be fixed. Since the logfile endpoint is being removed (since this version spring.boot includes it).
[You can have a look at my personal repo. There is a branch for 1.3.](https://github.com/joshiste/spring-boot-admin/tree/boot-1.3)
