### ISSUE TITLE
ServletApplicationFactory.getDispatcherServletPrefix

### ISSUE THREAD

**Issue by jameycai** [codecentric/spring-boot-admin#989]
The error of the program is reported after upgrading the 2.1.0 version of spring boot in the program and integrating spring-admin-client.

java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.web.ServerProperties$Servlet.getServletPrefix()Ljava/lang/String;
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getDispatcherServletPrefix(ServletApplicationFactory.java:98)
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementBaseUrl(ServletApplicationFactory.java:75)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:150)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:71)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:154)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:71)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)

**Comment by joshiste** [comment]
Our 2.1.0-SNAPSHOT is compatible with Spring boot 2.1.0.

**Comment by jameycai** [comment]
That Maven warehouse? I can download spring-boot-admin 2.1.0-SNAPSHOT.

**Comment by jameycai** [comment]
That Maven ? I can download spring-boot-admin 2.1.0-SNAPSHOT.

**Comment by jameycai** [comment]
https://mvnrepository.com/artifact/de.codecentric/spring-boot-admin-starter-client

The latest is 2.0.4.

**Comment by joshiste** [comment]
snapshots are available here: 
```
<repository>
	<id>sonatype-nexus-snapshots</id>
	<name>Sonatype Nexus Snapshots</name>
	<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
	<releases>
		<enabled>false</enabled>
	</releases>
</repository>
```

**Comment by jameycai** [comment]
thank you!
