### ISSUE TITLE
Client not registering in spring boot 2.1.0.RELEASE

### ISSUE THREAD

**Issue by ckoutsouridis** [codecentric/spring-boot-admin#992]
registration flow of `spring-boot-admin-starter-client` seems broken in spring boot 2.1.0.RELEASE:

```
java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.web.ServerProperties$Servlet.getServletPrefix()Ljava/lang/String;
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getDispatcherServletPrefix(ServletApplicationFactory.java:98)
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementBaseUrl(ServletApplicationFactory.java:75)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:150)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:71)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:154)
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:71)```

**Comment by joshiste** [comment]
you need to use spring boot 2.1.0 with spring boot admin 2.1.0
